// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Breakdown pagination.
 *
 * @param totalGroups Always present.
 * @param returnedGroups Always present.
 * @param nextCursor Always present; may be null.
 * @param truncated Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AnalyticsPagination(
        @JsonProperty("total_groups") Long totalGroups,
        @JsonProperty("returned_groups") Long returnedGroups,
        @JsonProperty("next_cursor") String nextCursor,
        @JsonProperty("truncated") Boolean truncated
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this AnalyticsPagination. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.totalGroups = totalGroups;
        builder.returnedGroups = returnedGroups;
        builder.nextCursor = nextCursor;
        builder.truncated = truncated;
        return builder;
    }

    /** Builds a {@link AnalyticsPagination}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long totalGroups;
        private Long returnedGroups;
        private String nextCursor;
        private Boolean truncated;

        private Builder() {
        }

        /** Sets {@code total_groups}. */
        public Builder totalGroups(Long totalGroups) {
            this.totalGroups = totalGroups;
            return this;
        }

        /** Sets {@code total_groups}. */
        public Builder totalGroups(long totalGroups) {
            this.totalGroups = totalGroups;
            return this;
        }

        /** Sets {@code returned_groups}. */
        public Builder returnedGroups(Long returnedGroups) {
            this.returnedGroups = returnedGroups;
            return this;
        }

        /** Sets {@code returned_groups}. */
        public Builder returnedGroups(long returnedGroups) {
            this.returnedGroups = returnedGroups;
            return this;
        }

        /** Sets {@code next_cursor}. */
        public Builder nextCursor(String nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        /** Sets {@code truncated}. */
        public Builder truncated(Boolean truncated) {
            this.truncated = truncated;
            return this;
        }

        /** Returns the {@link AnalyticsPagination}. */
        public AnalyticsPagination build() {
            return new AnalyticsPagination(totalGroups, returnedGroups, nextCursor, truncated);
        }
    }
}
