// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class AnalyticsCatalogueGroupDimension {
    /** {@code "project_id"} */
    public static final AnalyticsCatalogueGroupDimension PROJECT_ID = new AnalyticsCatalogueGroupDimension("project_id");

    /** {@code "route_id"} */
    public static final AnalyticsCatalogueGroupDimension ROUTE_ID = new AnalyticsCatalogueGroupDimension("route_id");

    /** {@code "message_type"} */
    public static final AnalyticsCatalogueGroupDimension MESSAGE_TYPE = new AnalyticsCatalogueGroupDimension("message_type");

    /** {@code "sending_domain"} */
    public static final AnalyticsCatalogueGroupDimension SENDING_DOMAIN = new AnalyticsCatalogueGroupDimension("sending_domain");

    /** {@code "recipient_domain"} */
    public static final AnalyticsCatalogueGroupDimension RECIPIENT_DOMAIN = new AnalyticsCatalogueGroupDimension("recipient_domain");

    /** {@code "provider_family"} */
    public static final AnalyticsCatalogueGroupDimension PROVIDER_FAMILY = new AnalyticsCatalogueGroupDimension("provider_family");

    /** {@code "provider_subtype"} */
    public static final AnalyticsCatalogueGroupDimension PROVIDER_SUBTYPE = new AnalyticsCatalogueGroupDimension("provider_subtype");

    /** {@code "from_address"} */
    public static final AnalyticsCatalogueGroupDimension FROM_ADDRESS = new AnalyticsCatalogueGroupDimension("from_address");

    /** {@code "subject"} */
    public static final AnalyticsCatalogueGroupDimension SUBJECT = new AnalyticsCatalogueGroupDimension("subject");

    /** {@code "dedicated_ip"} */
    public static final AnalyticsCatalogueGroupDimension DEDICATED_IP = new AnalyticsCatalogueGroupDimension("dedicated_ip");

    /** {@code "dedicated_pool_id"} */
    public static final AnalyticsCatalogueGroupDimension DEDICATED_POOL_ID = new AnalyticsCatalogueGroupDimension("dedicated_pool_id");

    /** {@code "infrastructure_state"} */
    public static final AnalyticsCatalogueGroupDimension INFRASTRUCTURE_STATE = new AnalyticsCatalogueGroupDimension("infrastructure_state");

    /** {@code "smtp_code"} */
    public static final AnalyticsCatalogueGroupDimension SMTP_CODE = new AnalyticsCatalogueGroupDimension("smtp_code");

    /** {@code "enhanced_status_code"} */
    public static final AnalyticsCatalogueGroupDimension ENHANCED_STATUS_CODE = new AnalyticsCatalogueGroupDimension("enhanced_status_code");

    /** {@code "enhanced_status_category"} */
    public static final AnalyticsCatalogueGroupDimension ENHANCED_STATUS_CATEGORY = new AnalyticsCatalogueGroupDimension("enhanced_status_category");

    /** {@code "bounce_classification"} */
    public static final AnalyticsCatalogueGroupDimension BOUNCE_CLASSIFICATION = new AnalyticsCatalogueGroupDimension("bounce_classification");

    /** {@code "failure_reason"} */
    public static final AnalyticsCatalogueGroupDimension FAILURE_REASON = new AnalyticsCatalogueGroupDimension("failure_reason");

    /** {@code "smtp_response_group"} */
    public static final AnalyticsCatalogueGroupDimension SMTP_RESPONSE_GROUP = new AnalyticsCatalogueGroupDimension("smtp_response_group");

    /** {@code "engagement_state"} */
    public static final AnalyticsCatalogueGroupDimension ENGAGEMENT_STATE = new AnalyticsCatalogueGroupDimension("engagement_state");

    /** {@code "request_actor"} */
    public static final AnalyticsCatalogueGroupDimension REQUEST_ACTOR = new AnalyticsCatalogueGroupDimension("request_actor");

    /** {@code "proxy_type"} */
    public static final AnalyticsCatalogueGroupDimension PROXY_TYPE = new AnalyticsCatalogueGroupDimension("proxy_type");

    private static final Map<String, AnalyticsCatalogueGroupDimension> KNOWN;
    private static final List<AnalyticsCatalogueGroupDimension> VALUES;

    static {
        Map<String, AnalyticsCatalogueGroupDimension> known = new LinkedHashMap<>();
        known.put(PROJECT_ID.value, PROJECT_ID);
        known.put(ROUTE_ID.value, ROUTE_ID);
        known.put(MESSAGE_TYPE.value, MESSAGE_TYPE);
        known.put(SENDING_DOMAIN.value, SENDING_DOMAIN);
        known.put(RECIPIENT_DOMAIN.value, RECIPIENT_DOMAIN);
        known.put(PROVIDER_FAMILY.value, PROVIDER_FAMILY);
        known.put(PROVIDER_SUBTYPE.value, PROVIDER_SUBTYPE);
        known.put(FROM_ADDRESS.value, FROM_ADDRESS);
        known.put(SUBJECT.value, SUBJECT);
        known.put(DEDICATED_IP.value, DEDICATED_IP);
        known.put(DEDICATED_POOL_ID.value, DEDICATED_POOL_ID);
        known.put(INFRASTRUCTURE_STATE.value, INFRASTRUCTURE_STATE);
        known.put(SMTP_CODE.value, SMTP_CODE);
        known.put(ENHANCED_STATUS_CODE.value, ENHANCED_STATUS_CODE);
        known.put(ENHANCED_STATUS_CATEGORY.value, ENHANCED_STATUS_CATEGORY);
        known.put(BOUNCE_CLASSIFICATION.value, BOUNCE_CLASSIFICATION);
        known.put(FAILURE_REASON.value, FAILURE_REASON);
        known.put(SMTP_RESPONSE_GROUP.value, SMTP_RESPONSE_GROUP);
        known.put(ENGAGEMENT_STATE.value, ENGAGEMENT_STATE);
        known.put(REQUEST_ACTOR.value, REQUEST_ACTOR);
        known.put(PROXY_TYPE.value, PROXY_TYPE);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private AnalyticsCatalogueGroupDimension(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AnalyticsCatalogueGroupDimension of(String value) {
        Objects.requireNonNull(value, "value");
        AnalyticsCatalogueGroupDimension known = KNOWN.get(value);
        return known != null ? known : new AnalyticsCatalogueGroupDimension(value);
    }

    /** The known values, in the order of the specification. */
    public static List<AnalyticsCatalogueGroupDimension> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof AnalyticsCatalogueGroupDimension that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
