// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Change of a metric against the comparison period.
 *
 * @param absolute Optional and nullable: null when absent or null.
 * @param relative Optional and nullable: null when absent or null.
 * @param percentagePoints Optional and nullable: null when absent or null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AnalyticsMetricChange(
        @JsonProperty("absolute") Double absolute,
        @JsonProperty("relative") Double relative,
        @JsonProperty("percentage_points") Double percentagePoints
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this AnalyticsMetricChange. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.absolute = absolute;
        builder.relative = relative;
        builder.percentagePoints = percentagePoints;
        return builder;
    }

    /** Builds a {@link AnalyticsMetricChange}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Double absolute;
        private Double relative;
        private Double percentagePoints;

        private Builder() {
        }

        /** Sets {@code absolute}. */
        public Builder absolute(Double absolute) {
            this.absolute = absolute;
            return this;
        }

        /** Sets {@code absolute}. */
        public Builder absolute(double absolute) {
            this.absolute = absolute;
            return this;
        }

        /** Sets {@code relative}. */
        public Builder relative(Double relative) {
            this.relative = relative;
            return this;
        }

        /** Sets {@code relative}. */
        public Builder relative(double relative) {
            this.relative = relative;
            return this;
        }

        /** Sets {@code percentage_points}. */
        public Builder percentagePoints(Double percentagePoints) {
            this.percentagePoints = percentagePoints;
            return this;
        }

        /** Sets {@code percentage_points}. */
        public Builder percentagePoints(double percentagePoints) {
            this.percentagePoints = percentagePoints;
            return this;
        }

        /** Returns the {@link AnalyticsMetricChange}. */
        public AnalyticsMetricChange build() {
            return new AnalyticsMetricChange(absolute, relative, percentagePoints);
        }
    }
}
