// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Numerators and denominators of the selected rate metrics.
 *
 * @param deliveryRate Optional: null when absent.
 * @param effectiveDeliveryRate Optional: null when absent.
 * @param bounceRate Optional: null when absent.
 * @param deferralRate Optional: null when absent.
 * @param complaintRate Optional: null when absent.
 * @param humanOpenRate Optional: null when absent.
 * @param humanClickRate Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AnalyticsRateBases(
        @JsonProperty("delivery_rate") AnalyticsRateBase deliveryRate,
        @JsonProperty("effective_delivery_rate") AnalyticsRateBase effectiveDeliveryRate,
        @JsonProperty("bounce_rate") AnalyticsRateBase bounceRate,
        @JsonProperty("deferral_rate") AnalyticsRateBase deferralRate,
        @JsonProperty("complaint_rate") AnalyticsRateBase complaintRate,
        @JsonProperty("human_open_rate") AnalyticsRateBase humanOpenRate,
        @JsonProperty("human_click_rate") AnalyticsRateBase humanClickRate
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this AnalyticsRateBases. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.deliveryRate = deliveryRate;
        builder.effectiveDeliveryRate = effectiveDeliveryRate;
        builder.bounceRate = bounceRate;
        builder.deferralRate = deferralRate;
        builder.complaintRate = complaintRate;
        builder.humanOpenRate = humanOpenRate;
        builder.humanClickRate = humanClickRate;
        return builder;
    }

    /** Builds a {@link AnalyticsRateBases}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private AnalyticsRateBase deliveryRate;
        private AnalyticsRateBase effectiveDeliveryRate;
        private AnalyticsRateBase bounceRate;
        private AnalyticsRateBase deferralRate;
        private AnalyticsRateBase complaintRate;
        private AnalyticsRateBase humanOpenRate;
        private AnalyticsRateBase humanClickRate;

        private Builder() {
        }

        /** Sets {@code delivery_rate}. */
        public Builder deliveryRate(AnalyticsRateBase deliveryRate) {
            this.deliveryRate = deliveryRate;
            return this;
        }

        /** Sets {@code effective_delivery_rate}. */
        public Builder effectiveDeliveryRate(AnalyticsRateBase effectiveDeliveryRate) {
            this.effectiveDeliveryRate = effectiveDeliveryRate;
            return this;
        }

        /** Sets {@code bounce_rate}. */
        public Builder bounceRate(AnalyticsRateBase bounceRate) {
            this.bounceRate = bounceRate;
            return this;
        }

        /** Sets {@code deferral_rate}. */
        public Builder deferralRate(AnalyticsRateBase deferralRate) {
            this.deferralRate = deferralRate;
            return this;
        }

        /** Sets {@code complaint_rate}. */
        public Builder complaintRate(AnalyticsRateBase complaintRate) {
            this.complaintRate = complaintRate;
            return this;
        }

        /** Sets {@code human_open_rate}. */
        public Builder humanOpenRate(AnalyticsRateBase humanOpenRate) {
            this.humanOpenRate = humanOpenRate;
            return this;
        }

        /** Sets {@code human_click_rate}. */
        public Builder humanClickRate(AnalyticsRateBase humanClickRate) {
            this.humanClickRate = humanClickRate;
            return this;
        }

        /** Returns the {@link AnalyticsRateBases}. */
        public AnalyticsRateBases build() {
            return new AnalyticsRateBases(deliveryRate, effectiveDeliveryRate, bounceRate, deferralRate, complaintRate, humanOpenRate, humanClickRate);
        }
    }
}
