// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * A metric from the analytics catalogue.
 *
 * An open enum: values that the API adds later decode as well and keep their raw value.
 */
public final class AnalyticsMetric {
    /** {@code "accepted"} */
    public static final AnalyticsMetric ACCEPTED = new AnalyticsMetric("accepted");

    /** {@code "processed"} */
    public static final AnalyticsMetric PROCESSED = new AnalyticsMetric("processed");

    /** {@code "suppressed"} */
    public static final AnalyticsMetric SUPPRESSED = new AnalyticsMetric("suppressed");

    /** {@code "policy_rejected"} */
    public static final AnalyticsMetric POLICY_REJECTED = new AnalyticsMetric("policy_rejected");

    /** {@code "application_failed"} */
    public static final AnalyticsMetric APPLICATION_FAILED = new AnalyticsMetric("application_failed");

    /** {@code "mta_accepted"} */
    public static final AnalyticsMetric MTA_ACCEPTED = new AnalyticsMetric("mta_accepted");

    /** {@code "canceled"} */
    public static final AnalyticsMetric CANCELED = new AnalyticsMetric("canceled");

    /** {@code "messages"} */
    public static final AnalyticsMetric MESSAGES = new AnalyticsMetric("messages");

    /** {@code "delivered"} */
    public static final AnalyticsMetric DELIVERED = new AnalyticsMetric("delivered");

    /** {@code "bounced"} */
    public static final AnalyticsMetric BOUNCED = new AnalyticsMetric("bounced");

    /** {@code "soft_bounced"} */
    public static final AnalyticsMetric SOFT_BOUNCED = new AnalyticsMetric("soft_bounced");

    /** {@code "administratively_bounced"} */
    public static final AnalyticsMetric ADMINISTRATIVELY_BOUNCED = new AnalyticsMetric("administratively_bounced");

    /** {@code "deferred_recipients"} */
    public static final AnalyticsMetric DEFERRED_RECIPIENTS = new AnalyticsMetric("deferred_recipients");

    /** {@code "deferred_events"} */
    public static final AnalyticsMetric DEFERRED_EVENTS = new AnalyticsMetric("deferred_events");

    /** {@code "delivery_attempts"} */
    public static final AnalyticsMetric DELIVERY_ATTEMPTS = new AnalyticsMetric("delivery_attempts");

    /** {@code "attempted_recipients"} */
    public static final AnalyticsMetric ATTEMPTED_RECIPIENTS = new AnalyticsMetric("attempted_recipients");

    /** {@code "transport_outcome_recipients"} */
    public static final AnalyticsMetric TRANSPORT_OUTCOME_RECIPIENTS = new AnalyticsMetric("transport_outcome_recipients");

    /** {@code "effective_delivered"} */
    public static final AnalyticsMetric EFFECTIVE_DELIVERED = new AnalyticsMetric("effective_delivered");

    /** {@code "open_tracked_delivered"} */
    public static final AnalyticsMetric OPEN_TRACKED_DELIVERED = new AnalyticsMetric("open_tracked_delivered");

    /** {@code "click_tracked_delivered"} */
    public static final AnalyticsMetric CLICK_TRACKED_DELIVERED = new AnalyticsMetric("click_tracked_delivered");

    /** {@code "out_of_band_bounced_recipients"} */
    public static final AnalyticsMetric OUT_OF_BAND_BOUNCED_RECIPIENTS = new AnalyticsMetric("out_of_band_bounced_recipients");

    /** {@code "out_of_band_bounce_events"} */
    public static final AnalyticsMetric OUT_OF_BAND_BOUNCE_EVENTS = new AnalyticsMetric("out_of_band_bounce_events");

    /** {@code "complained"} */
    public static final AnalyticsMetric COMPLAINED = new AnalyticsMetric("complained");

    /** {@code "unsubscribed"} */
    public static final AnalyticsMetric UNSUBSCRIBED = new AnalyticsMetric("unsubscribed");

    /** {@code "human_opens"} */
    public static final AnalyticsMetric HUMAN_OPENS = new AnalyticsMetric("human_opens");

    /** {@code "human_opens_events"} */
    public static final AnalyticsMetric HUMAN_OPENS_EVENTS = new AnalyticsMetric("human_opens_events");

    /** {@code "human_clicks"} */
    public static final AnalyticsMetric HUMAN_CLICKS = new AnalyticsMetric("human_clicks");

    /** {@code "human_clicks_events"} */
    public static final AnalyticsMetric HUMAN_CLICKS_EVENTS = new AnalyticsMetric("human_clicks_events");

    /** {@code "machine_opens"} */
    public static final AnalyticsMetric MACHINE_OPENS = new AnalyticsMetric("machine_opens");

    /** {@code "machine_opens_events"} */
    public static final AnalyticsMetric MACHINE_OPENS_EVENTS = new AnalyticsMetric("machine_opens_events");

    /** {@code "machine_clicks"} */
    public static final AnalyticsMetric MACHINE_CLICKS = new AnalyticsMetric("machine_clicks");

    /** {@code "machine_clicks_events"} */
    public static final AnalyticsMetric MACHINE_CLICKS_EVENTS = new AnalyticsMetric("machine_clicks_events");

    /** {@code "privacy_opens"} */
    public static final AnalyticsMetric PRIVACY_OPENS = new AnalyticsMetric("privacy_opens");

    /** {@code "privacy_opens_events"} */
    public static final AnalyticsMetric PRIVACY_OPENS_EVENTS = new AnalyticsMetric("privacy_opens_events");

    /** {@code "privacy_clicks"} */
    public static final AnalyticsMetric PRIVACY_CLICKS = new AnalyticsMetric("privacy_clicks");

    /** {@code "privacy_clicks_events"} */
    public static final AnalyticsMetric PRIVACY_CLICKS_EVENTS = new AnalyticsMetric("privacy_clicks_events");

    /** {@code "bot_opens"} */
    public static final AnalyticsMetric BOT_OPENS = new AnalyticsMetric("bot_opens");

    /** {@code "bot_opens_events"} */
    public static final AnalyticsMetric BOT_OPENS_EVENTS = new AnalyticsMetric("bot_opens_events");

    /** {@code "bot_clicks"} */
    public static final AnalyticsMetric BOT_CLICKS = new AnalyticsMetric("bot_clicks");

    /** {@code "bot_clicks_events"} */
    public static final AnalyticsMetric BOT_CLICKS_EVENTS = new AnalyticsMetric("bot_clicks_events");

    /** {@code "scanner_opens"} */
    public static final AnalyticsMetric SCANNER_OPENS = new AnalyticsMetric("scanner_opens");

    /** {@code "scanner_opens_events"} */
    public static final AnalyticsMetric SCANNER_OPENS_EVENTS = new AnalyticsMetric("scanner_opens_events");

    /** {@code "scanner_clicks"} */
    public static final AnalyticsMetric SCANNER_CLICKS = new AnalyticsMetric("scanner_clicks");

    /** {@code "scanner_clicks_events"} */
    public static final AnalyticsMetric SCANNER_CLICKS_EVENTS = new AnalyticsMetric("scanner_clicks_events");

    /** {@code "observed_opens"} */
    public static final AnalyticsMetric OBSERVED_OPENS = new AnalyticsMetric("observed_opens");

    /** {@code "observed_opens_events"} */
    public static final AnalyticsMetric OBSERVED_OPENS_EVENTS = new AnalyticsMetric("observed_opens_events");

    /** {@code "observed_clicks"} */
    public static final AnalyticsMetric OBSERVED_CLICKS = new AnalyticsMetric("observed_clicks");

    /** {@code "observed_clicks_events"} */
    public static final AnalyticsMetric OBSERVED_CLICKS_EVENTS = new AnalyticsMetric("observed_clicks_events");

    /** {@code "delivery_rate"} */
    public static final AnalyticsMetric DELIVERY_RATE = new AnalyticsMetric("delivery_rate");

    /** {@code "effective_delivery_rate"} */
    public static final AnalyticsMetric EFFECTIVE_DELIVERY_RATE = new AnalyticsMetric("effective_delivery_rate");

    /** {@code "bounce_rate"} */
    public static final AnalyticsMetric BOUNCE_RATE = new AnalyticsMetric("bounce_rate");

    /** {@code "deferral_rate"} */
    public static final AnalyticsMetric DEFERRAL_RATE = new AnalyticsMetric("deferral_rate");

    /** {@code "complaint_rate"} */
    public static final AnalyticsMetric COMPLAINT_RATE = new AnalyticsMetric("complaint_rate");

    /** {@code "human_open_rate"} */
    public static final AnalyticsMetric HUMAN_OPEN_RATE = new AnalyticsMetric("human_open_rate");

    /** {@code "human_click_rate"} */
    public static final AnalyticsMetric HUMAN_CLICK_RATE = new AnalyticsMetric("human_click_rate");

    /** {@code "processing_latency_p50_ms"} */
    public static final AnalyticsMetric PROCESSING_LATENCY_P50_MS = new AnalyticsMetric("processing_latency_p50_ms");

    /** {@code "processing_latency_p95_ms"} */
    public static final AnalyticsMetric PROCESSING_LATENCY_P95_MS = new AnalyticsMetric("processing_latency_p95_ms");

    /** {@code "processing_latency_p99_ms"} */
    public static final AnalyticsMetric PROCESSING_LATENCY_P99_MS = new AnalyticsMetric("processing_latency_p99_ms");

    /** {@code "processing_latency_samples"} */
    public static final AnalyticsMetric PROCESSING_LATENCY_SAMPLES = new AnalyticsMetric("processing_latency_samples");

    /** {@code "delivery_latency_p50_ms"} */
    public static final AnalyticsMetric DELIVERY_LATENCY_P50_MS = new AnalyticsMetric("delivery_latency_p50_ms");

    /** {@code "delivery_latency_p95_ms"} */
    public static final AnalyticsMetric DELIVERY_LATENCY_P95_MS = new AnalyticsMetric("delivery_latency_p95_ms");

    /** {@code "delivery_latency_p99_ms"} */
    public static final AnalyticsMetric DELIVERY_LATENCY_P99_MS = new AnalyticsMetric("delivery_latency_p99_ms");

    /** {@code "delivery_latency_samples"} */
    public static final AnalyticsMetric DELIVERY_LATENCY_SAMPLES = new AnalyticsMetric("delivery_latency_samples");

    /** {@code "total_latency_p50_ms"} */
    public static final AnalyticsMetric TOTAL_LATENCY_P50_MS = new AnalyticsMetric("total_latency_p50_ms");

    /** {@code "total_latency_p95_ms"} */
    public static final AnalyticsMetric TOTAL_LATENCY_P95_MS = new AnalyticsMetric("total_latency_p95_ms");

    /** {@code "total_latency_p99_ms"} */
    public static final AnalyticsMetric TOTAL_LATENCY_P99_MS = new AnalyticsMetric("total_latency_p99_ms");

    /** {@code "total_latency_samples"} */
    public static final AnalyticsMetric TOTAL_LATENCY_SAMPLES = new AnalyticsMetric("total_latency_samples");

    private static final Map<String, AnalyticsMetric> KNOWN;
    private static final List<AnalyticsMetric> VALUES;

    static {
        Map<String, AnalyticsMetric> known = new LinkedHashMap<>();
        known.put(ACCEPTED.value, ACCEPTED);
        known.put(PROCESSED.value, PROCESSED);
        known.put(SUPPRESSED.value, SUPPRESSED);
        known.put(POLICY_REJECTED.value, POLICY_REJECTED);
        known.put(APPLICATION_FAILED.value, APPLICATION_FAILED);
        known.put(MTA_ACCEPTED.value, MTA_ACCEPTED);
        known.put(CANCELED.value, CANCELED);
        known.put(MESSAGES.value, MESSAGES);
        known.put(DELIVERED.value, DELIVERED);
        known.put(BOUNCED.value, BOUNCED);
        known.put(SOFT_BOUNCED.value, SOFT_BOUNCED);
        known.put(ADMINISTRATIVELY_BOUNCED.value, ADMINISTRATIVELY_BOUNCED);
        known.put(DEFERRED_RECIPIENTS.value, DEFERRED_RECIPIENTS);
        known.put(DEFERRED_EVENTS.value, DEFERRED_EVENTS);
        known.put(DELIVERY_ATTEMPTS.value, DELIVERY_ATTEMPTS);
        known.put(ATTEMPTED_RECIPIENTS.value, ATTEMPTED_RECIPIENTS);
        known.put(TRANSPORT_OUTCOME_RECIPIENTS.value, TRANSPORT_OUTCOME_RECIPIENTS);
        known.put(EFFECTIVE_DELIVERED.value, EFFECTIVE_DELIVERED);
        known.put(OPEN_TRACKED_DELIVERED.value, OPEN_TRACKED_DELIVERED);
        known.put(CLICK_TRACKED_DELIVERED.value, CLICK_TRACKED_DELIVERED);
        known.put(OUT_OF_BAND_BOUNCED_RECIPIENTS.value, OUT_OF_BAND_BOUNCED_RECIPIENTS);
        known.put(OUT_OF_BAND_BOUNCE_EVENTS.value, OUT_OF_BAND_BOUNCE_EVENTS);
        known.put(COMPLAINED.value, COMPLAINED);
        known.put(UNSUBSCRIBED.value, UNSUBSCRIBED);
        known.put(HUMAN_OPENS.value, HUMAN_OPENS);
        known.put(HUMAN_OPENS_EVENTS.value, HUMAN_OPENS_EVENTS);
        known.put(HUMAN_CLICKS.value, HUMAN_CLICKS);
        known.put(HUMAN_CLICKS_EVENTS.value, HUMAN_CLICKS_EVENTS);
        known.put(MACHINE_OPENS.value, MACHINE_OPENS);
        known.put(MACHINE_OPENS_EVENTS.value, MACHINE_OPENS_EVENTS);
        known.put(MACHINE_CLICKS.value, MACHINE_CLICKS);
        known.put(MACHINE_CLICKS_EVENTS.value, MACHINE_CLICKS_EVENTS);
        known.put(PRIVACY_OPENS.value, PRIVACY_OPENS);
        known.put(PRIVACY_OPENS_EVENTS.value, PRIVACY_OPENS_EVENTS);
        known.put(PRIVACY_CLICKS.value, PRIVACY_CLICKS);
        known.put(PRIVACY_CLICKS_EVENTS.value, PRIVACY_CLICKS_EVENTS);
        known.put(BOT_OPENS.value, BOT_OPENS);
        known.put(BOT_OPENS_EVENTS.value, BOT_OPENS_EVENTS);
        known.put(BOT_CLICKS.value, BOT_CLICKS);
        known.put(BOT_CLICKS_EVENTS.value, BOT_CLICKS_EVENTS);
        known.put(SCANNER_OPENS.value, SCANNER_OPENS);
        known.put(SCANNER_OPENS_EVENTS.value, SCANNER_OPENS_EVENTS);
        known.put(SCANNER_CLICKS.value, SCANNER_CLICKS);
        known.put(SCANNER_CLICKS_EVENTS.value, SCANNER_CLICKS_EVENTS);
        known.put(OBSERVED_OPENS.value, OBSERVED_OPENS);
        known.put(OBSERVED_OPENS_EVENTS.value, OBSERVED_OPENS_EVENTS);
        known.put(OBSERVED_CLICKS.value, OBSERVED_CLICKS);
        known.put(OBSERVED_CLICKS_EVENTS.value, OBSERVED_CLICKS_EVENTS);
        known.put(DELIVERY_RATE.value, DELIVERY_RATE);
        known.put(EFFECTIVE_DELIVERY_RATE.value, EFFECTIVE_DELIVERY_RATE);
        known.put(BOUNCE_RATE.value, BOUNCE_RATE);
        known.put(DEFERRAL_RATE.value, DEFERRAL_RATE);
        known.put(COMPLAINT_RATE.value, COMPLAINT_RATE);
        known.put(HUMAN_OPEN_RATE.value, HUMAN_OPEN_RATE);
        known.put(HUMAN_CLICK_RATE.value, HUMAN_CLICK_RATE);
        known.put(PROCESSING_LATENCY_P50_MS.value, PROCESSING_LATENCY_P50_MS);
        known.put(PROCESSING_LATENCY_P95_MS.value, PROCESSING_LATENCY_P95_MS);
        known.put(PROCESSING_LATENCY_P99_MS.value, PROCESSING_LATENCY_P99_MS);
        known.put(PROCESSING_LATENCY_SAMPLES.value, PROCESSING_LATENCY_SAMPLES);
        known.put(DELIVERY_LATENCY_P50_MS.value, DELIVERY_LATENCY_P50_MS);
        known.put(DELIVERY_LATENCY_P95_MS.value, DELIVERY_LATENCY_P95_MS);
        known.put(DELIVERY_LATENCY_P99_MS.value, DELIVERY_LATENCY_P99_MS);
        known.put(DELIVERY_LATENCY_SAMPLES.value, DELIVERY_LATENCY_SAMPLES);
        known.put(TOTAL_LATENCY_P50_MS.value, TOTAL_LATENCY_P50_MS);
        known.put(TOTAL_LATENCY_P95_MS.value, TOTAL_LATENCY_P95_MS);
        known.put(TOTAL_LATENCY_P99_MS.value, TOTAL_LATENCY_P99_MS);
        known.put(TOTAL_LATENCY_SAMPLES.value, TOTAL_LATENCY_SAMPLES);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private AnalyticsMetric(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AnalyticsMetric of(String value) {
        Objects.requireNonNull(value, "value");
        AnalyticsMetric known = KNOWN.get(value);
        return known != null ? known : new AnalyticsMetric(value);
    }

    /** The known values, in the order of the specification. */
    public static List<AnalyticsMetric> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof AnalyticsMetric that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
