// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * The selected result sections.
 *
 * @param summary Optional: null when absent.
 * @param timeSeries Optional: null when absent.
 * @param breakdown Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AnalyticsResults(
        @JsonProperty("summary") AnalyticsSummary summary,
        @JsonProperty("time_series") List<AnalyticsTimeSeriesPoint> timeSeries,
        @JsonProperty("breakdown") List<AnalyticsBreakdownRow> breakdown
) {
    /** Copies lists and maps into unmodifiable collections. */
    public AnalyticsResults {
        timeSeries = Copies.list(timeSeries);
        breakdown = Copies.list(breakdown);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this AnalyticsResults. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.summary = summary;
        builder.timeSeries = timeSeries;
        builder.breakdown = breakdown;
        return builder;
    }

    /** Builds a {@link AnalyticsResults}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private AnalyticsSummary summary;
        private List<AnalyticsTimeSeriesPoint> timeSeries;
        private List<AnalyticsBreakdownRow> breakdown;

        private Builder() {
        }

        /** Sets {@code summary}. */
        public Builder summary(AnalyticsSummary summary) {
            this.summary = summary;
            return this;
        }

        /** Sets {@code time_series}. */
        public Builder timeSeries(List<AnalyticsTimeSeriesPoint> timeSeries) {
            this.timeSeries = timeSeries;
            return this;
        }

        /** Sets {@code breakdown}. */
        public Builder breakdown(List<AnalyticsBreakdownRow> breakdown) {
            this.breakdown = breakdown;
            return this;
        }

        /** Returns the {@link AnalyticsResults}. */
        public AnalyticsResults build() {
            return new AnalyticsResults(summary, timeSeries, breakdown);
        }
    }
}
