// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;

/**
 * Metric values for one time-series bucket.
 *
 * @param metrics Always present.
 * @param rateBases Always present.
 * @param previous Optional: null when absent.
 * @param change Optional: null when absent.
 * @param from Always present.
 * @param to Always present.
 * @param available Always present.
 * @param partial Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AnalyticsTimeSeriesPoint(
        @JsonProperty("metrics") AnalyticsMetricValues metrics,
        @JsonProperty("rate_bases") AnalyticsRateBases rateBases,
        @JsonProperty("previous") AnalyticsComparisonValues previous,
        @JsonProperty("change") Map<String, AnalyticsMetricChange> change,
        @JsonProperty("from") String from,
        @JsonProperty("to") String to,
        @JsonProperty("available") Boolean available,
        @JsonProperty("partial") Boolean partial
) {
    /** Copies lists and maps into unmodifiable collections. */
    public AnalyticsTimeSeriesPoint {
        change = Copies.map(change);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this AnalyticsTimeSeriesPoint. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.metrics = metrics;
        builder.rateBases = rateBases;
        builder.previous = previous;
        builder.change = change;
        builder.from = from;
        builder.to = to;
        builder.available = available;
        builder.partial = partial;
        return builder;
    }

    /** Builds a {@link AnalyticsTimeSeriesPoint}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private AnalyticsMetricValues metrics;
        private AnalyticsRateBases rateBases;
        private AnalyticsComparisonValues previous;
        private Map<String, AnalyticsMetricChange> change;
        private String from;
        private String to;
        private Boolean available;
        private Boolean partial;

        private Builder() {
        }

        /** Sets {@code metrics}. */
        public Builder metrics(AnalyticsMetricValues metrics) {
            this.metrics = metrics;
            return this;
        }

        /** Sets {@code rate_bases}. */
        public Builder rateBases(AnalyticsRateBases rateBases) {
            this.rateBases = rateBases;
            return this;
        }

        /** Sets {@code previous}. */
        public Builder previous(AnalyticsComparisonValues previous) {
            this.previous = previous;
            return this;
        }

        /** Sets {@code change}. */
        public Builder change(Map<String, AnalyticsMetricChange> change) {
            this.change = change;
            return this;
        }

        /** Sets {@code from}. */
        public Builder from(String from) {
            this.from = from;
            return this;
        }

        /** Sets {@code to}. */
        public Builder to(String to) {
            this.to = to;
            return this;
        }

        /** Sets {@code available}. */
        public Builder available(Boolean available) {
            this.available = available;
            return this;
        }

        /** Sets {@code partial}. */
        public Builder partial(Boolean partial) {
            this.partial = partial;
            return this;
        }

        /** Returns the {@link AnalyticsTimeSeriesPoint}. */
        public AnalyticsTimeSeriesPoint build() {
            return new AnalyticsTimeSeriesPoint(metrics, rateBases, previous, change, from, to, available, partial);
        }
    }
}
