// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param code Machine-readable error code, for example <code>RESOURCE_NOT_FOUND</code>. Always present.
 * @param message Human-readable error message. Always present.
 * @param details Additional context. Its shape depends on the error code. Optional and nullable: null when absent or null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ApiErrorDetail(
        @JsonProperty("code") String code,
        @JsonProperty("message") String message,
        @JsonProperty("details") Object details
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ApiErrorDetail. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.code = code;
        builder.message = message;
        builder.details = details;
        return builder;
    }

    /** Builds a {@link ApiErrorDetail}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String code;
        private String message;
        private Object details;

        private Builder() {
        }

        /** Sets {@code code}. */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /** Sets {@code message}. */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /** Sets {@code details}. */
        public Builder details(Object details) {
            this.details = details;
            return this;
        }

        /** Returns the {@link ApiErrorDetail}. */
        public ApiErrorDetail build() {
            return new ApiErrorDetail(code, message, details);
        }
    }
}
