// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * File types that cannot be sent as email attachments.
 *
 * @param extensions Blocked file extensions, without the leading dot. Always present.
 * @param mimeTypes Blocked MIME types. Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record BlockedFileTypes(
        @JsonProperty("extensions") List<String> extensions,
        @JsonProperty("mime_types") List<String> mimeTypes
) {
    /** Copies lists and maps into unmodifiable collections. */
    public BlockedFileTypes {
        extensions = Copies.list(extensions);
        mimeTypes = Copies.list(mimeTypes);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this BlockedFileTypes. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.extensions = extensions;
        builder.mimeTypes = mimeTypes;
        return builder;
    }

    /** Builds a {@link BlockedFileTypes}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private List<String> extensions;
        private List<String> mimeTypes;

        private Builder() {
        }

        /** Sets {@code extensions}. */
        public Builder extensions(List<String> extensions) {
            this.extensions = extensions;
            return this;
        }

        /** Sets {@code mime_types}. */
        public Builder mimeTypes(List<String> mimeTypes) {
            this.mimeTypes = mimeTypes;
            return this;
        }

        /** Returns the {@link BlockedFileTypes}. */
        public BlockedFileTypes build() {
            return new BlockedFileTypes(extensions, mimeTypes);
        }
    }
}
