// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A page of a cursor-paginated list. Pass <code>nextCursor</code> back as the cursor query parameter to read the next page; it is null on the last page.
 *
 * @param data The items of this page.
 * @param path Base path for paginator generated URLs. May be null.
 * @param perPage Number of items shown per page.
 * @param nextCursor The "cursor" that points to the next set of items. May be null.
 * @param nextPageUrl May be null.
 * @param prevCursor The "cursor" that points to the previous set of items. May be null.
 * @param prevPageUrl May be null.
 * @param <T> the item type
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CursorPage<T>(
        @JsonProperty("data") List<T> data,
        @JsonProperty("path") String path,
        @JsonProperty("per_page") Long perPage,
        @JsonProperty("next_cursor") String nextCursor,
        @JsonProperty("next_page_url") String nextPageUrl,
        @JsonProperty("prev_cursor") String prevCursor,
        @JsonProperty("prev_page_url") String prevPageUrl
) {
    /** Copies {@code data} into an unmodifiable list. */
    public CursorPage {
        data = Copies.list(data);
    }

    /** Whether there is a next page. */
    public boolean hasNextPage() {
        return nextCursor != null && !nextCursor.isEmpty();
    }
}
