// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param success Always present.
 * @param status Always present.
 * @param message Human-readable confirmation. Always present.
 * @param confidence Confidence of the automated removal assessment, when one ran. Optional: null when absent.
 * @param ticketIdentifier The identifier of the support ticket that reviews the removal. Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DeleteSuppressionResponse(
        @JsonProperty("success") Boolean success,
        @JsonProperty("status") DeleteSuppressionResponseStatus status,
        @JsonProperty("message") String message,
        @JsonProperty("confidence") Double confidence,
        @JsonProperty("ticket_identifier") String ticketIdentifier
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this DeleteSuppressionResponse. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.success = success;
        builder.status = status;
        builder.message = message;
        builder.confidence = confidence;
        builder.ticketIdentifier = ticketIdentifier;
        return builder;
    }

    /** Builds a {@link DeleteSuppressionResponse}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Boolean success;
        private DeleteSuppressionResponseStatus status;
        private String message;
        private Double confidence;
        private String ticketIdentifier;

        private Builder() {
        }

        /** Sets {@code success}. */
        public Builder success(Boolean success) {
            this.success = success;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(DeleteSuppressionResponseStatus status) {
            this.status = status;
            return this;
        }

        /** Sets {@code message}. */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /** Sets {@code confidence}. */
        public Builder confidence(Double confidence) {
            this.confidence = confidence;
            return this;
        }

        /** Sets {@code confidence}. */
        public Builder confidence(double confidence) {
            this.confidence = confidence;
            return this;
        }

        /** Sets {@code ticket_identifier}. */
        public Builder ticketIdentifier(String ticketIdentifier) {
            this.ticketIdentifier = ticketIdentifier;
            return this;
        }

        /** Returns the {@link DeleteSuppressionResponse}. */
        public DeleteSuppressionResponse build() {
            return new DeleteSuppressionResponse(success, status, message, confidence, ticketIdentifier);
        }
    }
}
