// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param dmarcSpfAlignmentIssue Always present; may be null.
 * @param verified Always present.
 * @param error Always present; may be null.
 * @param expectedRecord Always present; may be null.
 * @param foundRecord Always present; may be null.
 * @param dmarcPolicyDomain Always present; may be null.
 * @param dmarcEffectivePolicy Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DnsVerificationResultData(
        @JsonProperty("dmarc_spf_alignment_issue") DnsVerificationResultDataDmarcSpfAlignmentIssue dmarcSpfAlignmentIssue,
        @JsonProperty("verified") Boolean verified,
        @JsonProperty("error") String error,
        @JsonProperty("expected_record") String expectedRecord,
        @JsonProperty("found_record") String foundRecord,
        @JsonProperty("dmarc_policy_domain") String dmarcPolicyDomain,
        @JsonProperty("dmarc_effective_policy") DmarcPolicy dmarcEffectivePolicy
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this DnsVerificationResultData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.dmarcSpfAlignmentIssue = dmarcSpfAlignmentIssue;
        builder.verified = verified;
        builder.error = error;
        builder.expectedRecord = expectedRecord;
        builder.foundRecord = foundRecord;
        builder.dmarcPolicyDomain = dmarcPolicyDomain;
        builder.dmarcEffectivePolicy = dmarcEffectivePolicy;
        return builder;
    }

    /** Builds a {@link DnsVerificationResultData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private DnsVerificationResultDataDmarcSpfAlignmentIssue dmarcSpfAlignmentIssue;
        private Boolean verified;
        private String error;
        private String expectedRecord;
        private String foundRecord;
        private String dmarcPolicyDomain;
        private DmarcPolicy dmarcEffectivePolicy;

        private Builder() {
        }

        /** Sets {@code dmarc_spf_alignment_issue}. */
        public Builder dmarcSpfAlignmentIssue(DnsVerificationResultDataDmarcSpfAlignmentIssue dmarcSpfAlignmentIssue) {
            this.dmarcSpfAlignmentIssue = dmarcSpfAlignmentIssue;
            return this;
        }

        /** Sets {@code verified}. */
        public Builder verified(Boolean verified) {
            this.verified = verified;
            return this;
        }

        /** Sets {@code error}. */
        public Builder error(String error) {
            this.error = error;
            return this;
        }

        /** Sets {@code expected_record}. */
        public Builder expectedRecord(String expectedRecord) {
            this.expectedRecord = expectedRecord;
            return this;
        }

        /** Sets {@code found_record}. */
        public Builder foundRecord(String foundRecord) {
            this.foundRecord = foundRecord;
            return this;
        }

        /** Sets {@code dmarc_policy_domain}. */
        public Builder dmarcPolicyDomain(String dmarcPolicyDomain) {
            this.dmarcPolicyDomain = dmarcPolicyDomain;
            return this;
        }

        /** Sets {@code dmarc_effective_policy}. */
        public Builder dmarcEffectivePolicy(DmarcPolicy dmarcEffectivePolicy) {
            this.dmarcEffectivePolicy = dmarcEffectivePolicy;
            return this;
        }

        /** Returns the {@link DnsVerificationResultData}. */
        public DnsVerificationResultData build() {
            return new DnsVerificationResultData(dmarcSpfAlignmentIssue, verified, error, expectedRecord, foundRecord, dmarcPolicyDomain, dmarcEffectivePolicy);
        }
    }
}
