// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class DnsVerificationScope {
    /** {@code "required"} */
    public static final DnsVerificationScope REQUIRED = new DnsVerificationScope("required");

    /** {@code "recommended"} */
    public static final DnsVerificationScope RECOMMENDED = new DnsVerificationScope("recommended");

    /** {@code "migration"} */
    public static final DnsVerificationScope MIGRATION = new DnsVerificationScope("migration");

    /** {@code "deprecated"} */
    public static final DnsVerificationScope DEPRECATED = new DnsVerificationScope("deprecated");

    private static final Map<String, DnsVerificationScope> KNOWN;
    private static final List<DnsVerificationScope> VALUES;

    static {
        Map<String, DnsVerificationScope> known = new LinkedHashMap<>();
        known.put(REQUIRED.value, REQUIRED);
        known.put(RECOMMENDED.value, RECOMMENDED);
        known.put(MIGRATION.value, MIGRATION);
        known.put(DEPRECATED.value, DEPRECATED);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private DnsVerificationScope(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DnsVerificationScope of(String value) {
        Objects.requireNonNull(value, "value");
        DnsVerificationScope known = KNOWN.get(value);
        return known != null ? known : new DnsVerificationScope(value);
    }

    /** The known values, in the order of the specification. */
    public static List<DnsVerificationScope> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof DnsVerificationScope that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
