// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A DNS record that did not pass verification.
 *
 * @param id The DNS record ID. Always present.
 * @param type Always present.
 * @param name The record hostname. Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DnsVerificationFailedRecord(
        @JsonProperty("id") String id,
        @JsonProperty("type") RecordType type,
        @JsonProperty("name") String name
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this DnsVerificationFailedRecord. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.type = type;
        builder.name = name;
        return builder;
    }

    /** Builds a {@link DnsVerificationFailedRecord}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private RecordType type;
        private String name;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code type}. */
        public Builder type(RecordType type) {
            this.type = type;
            return this;
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Returns the {@link DnsVerificationFailedRecord}. */
        public DnsVerificationFailedRecord build() {
            return new DnsVerificationFailedRecord(id, type, name);
        }
    }
}
