// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Why a DNS record did not pass verification.
 *
 * @param recordId The DNS record ID. Always present.
 * @param error Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DnsVerificationError(
        @JsonProperty("record_id") String recordId,
        @JsonProperty("error") String error
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this DnsVerificationError. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.recordId = recordId;
        builder.error = error;
        return builder;
    }

    /** Builds a {@link DnsVerificationError}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String recordId;
        private String error;

        private Builder() {
        }

        /** Sets {@code record_id}. */
        public Builder recordId(String recordId) {
            this.recordId = recordId;
            return this;
        }

        /** Sets {@code error}. */
        public Builder error(String error) {
            this.error = error;
            return this;
        }

        /** Returns the {@link DnsVerificationError}. */
        public DnsVerificationError build() {
            return new DnsVerificationError(recordId, error);
        }
    }
}
