// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * One or more required DNS records of the domain did not pass verification.
 *
 * @param message Human-readable verification result. Always present.
 * @param failedRecords Required records that did not pass verification. Always present.
 * @param errors Verification errors of every failed record, including recommended records. Always present.
 * @param failedCount The number of required records that failed. Always present.
 * @param totalCount The number of required records. Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DnsVerificationFailureResponse(
        @JsonProperty("message") String message,
        @JsonProperty("failed_records") List<DnsVerificationFailedRecord> failedRecords,
        @JsonProperty("errors") List<DnsVerificationError> errors,
        @JsonProperty("failed_count") Long failedCount,
        @JsonProperty("total_count") Long totalCount
) {
    /** Copies lists and maps into unmodifiable collections. */
    public DnsVerificationFailureResponse {
        failedRecords = Copies.list(failedRecords);
        errors = Copies.list(errors);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this DnsVerificationFailureResponse. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.message = message;
        builder.failedRecords = failedRecords;
        builder.errors = errors;
        builder.failedCount = failedCount;
        builder.totalCount = totalCount;
        return builder;
    }

    /** Builds a {@link DnsVerificationFailureResponse}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String message;
        private List<DnsVerificationFailedRecord> failedRecords;
        private List<DnsVerificationError> errors;
        private Long failedCount;
        private Long totalCount;

        private Builder() {
        }

        /** Sets {@code message}. */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /** Sets {@code failed_records}. */
        public Builder failedRecords(List<DnsVerificationFailedRecord> failedRecords) {
            this.failedRecords = failedRecords;
            return this;
        }

        /** Sets {@code errors}. */
        public Builder errors(List<DnsVerificationError> errors) {
            this.errors = errors;
            return this;
        }

        /** Sets {@code failed_count}. */
        public Builder failedCount(Long failedCount) {
            this.failedCount = failedCount;
            return this;
        }

        /** Sets {@code failed_count}. */
        public Builder failedCount(long failedCount) {
            this.failedCount = failedCount;
            return this;
        }

        /** Sets {@code total_count}. */
        public Builder totalCount(Long totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /** Sets {@code total_count}. */
        public Builder totalCount(long totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /** Returns the {@link DnsVerificationFailureResponse}. */
        public DnsVerificationFailureResponse build() {
            return new DnsVerificationFailureResponse(message, failedRecords, errors, failedCount, totalCount);
        }
    }
}
