// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param id Always present.
 * @param domain Always present.
 * @param dkimMode Always present.
 * @param rotationReady Always present.
 * @param statusChangedAt Always present; may be null.
 * @param dnsRecords Optional: null when absent.
 * @param projects Optional: null when absent.
 * @param createdAt Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DomainData(
        @JsonProperty("id") String id,
        @JsonProperty("domain") String domain,
        @JsonProperty("dkim_mode") DkimMode dkimMode,
        @JsonProperty("rotation_ready") Boolean rotationReady,
        @JsonProperty("status_changed_at") String statusChangedAt,
        @JsonProperty("dns_records") List<DomainDnsRecordData> dnsRecords,
        @JsonProperty("projects") List<DomainDataProjectsItem> projects,
        @JsonProperty("created_at") String createdAt
) {
    /** Copies lists and maps into unmodifiable collections. */
    public DomainData {
        dnsRecords = Copies.list(dnsRecords);
        projects = Copies.list(projects);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this DomainData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.domain = domain;
        builder.dkimMode = dkimMode;
        builder.rotationReady = rotationReady;
        builder.statusChangedAt = statusChangedAt;
        builder.dnsRecords = dnsRecords;
        builder.projects = projects;
        builder.createdAt = createdAt;
        return builder;
    }

    /** Builds a {@link DomainData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private String domain;
        private DkimMode dkimMode;
        private Boolean rotationReady;
        private String statusChangedAt;
        private List<DomainDnsRecordData> dnsRecords;
        private List<DomainDataProjectsItem> projects;
        private String createdAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code domain}. */
        public Builder domain(String domain) {
            this.domain = domain;
            return this;
        }

        /** Sets {@code dkim_mode}. */
        public Builder dkimMode(DkimMode dkimMode) {
            this.dkimMode = dkimMode;
            return this;
        }

        /** Sets {@code rotation_ready}. */
        public Builder rotationReady(Boolean rotationReady) {
            this.rotationReady = rotationReady;
            return this;
        }

        /** Sets {@code status_changed_at}. */
        public Builder statusChangedAt(String statusChangedAt) {
            this.statusChangedAt = statusChangedAt;
            return this;
        }

        /** Sets {@code dns_records}. */
        public Builder dnsRecords(List<DomainDnsRecordData> dnsRecords) {
            this.dnsRecords = dnsRecords;
            return this;
        }

        /** Sets {@code projects}. */
        public Builder projects(List<DomainDataProjectsItem> projects) {
            this.projects = projects;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Returns the {@link DomainData}. */
        public DomainData build() {
            return new DomainData(id, domain, dkimMode, rotationReady, statusChangedAt, dnsRecords, projects, createdAt);
        }
    }
}
