// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class GetProjectQueryIncludeItem {
    /** {@code "routes"} */
    public static final GetProjectQueryIncludeItem ROUTES = new GetProjectQueryIncludeItem("routes");

    /** {@code "routesCount"} */
    public static final GetProjectQueryIncludeItem ROUTES_COUNT = new GetProjectQueryIncludeItem("routesCount");

    /** {@code "routesExists"} */
    public static final GetProjectQueryIncludeItem ROUTES_EXISTS = new GetProjectQueryIncludeItem("routesExists");

    /** {@code "domains"} */
    public static final GetProjectQueryIncludeItem DOMAINS = new GetProjectQueryIncludeItem("domains");

    /** {@code "domainsCount"} */
    public static final GetProjectQueryIncludeItem DOMAINS_COUNT = new GetProjectQueryIncludeItem("domainsCount");

    /** {@code "domainsExists"} */
    public static final GetProjectQueryIncludeItem DOMAINS_EXISTS = new GetProjectQueryIncludeItem("domainsExists");

    /** {@code "messageStats"} */
    public static final GetProjectQueryIncludeItem MESSAGE_STATS = new GetProjectQueryIncludeItem("messageStats");

    /** {@code "messageStatsCount"} */
    public static final GetProjectQueryIncludeItem MESSAGE_STATS_COUNT = new GetProjectQueryIncludeItem("messageStatsCount");

    /** {@code "messageStatsExists"} */
    public static final GetProjectQueryIncludeItem MESSAGE_STATS_EXISTS = new GetProjectQueryIncludeItem("messageStatsExists");

    private static final Map<String, GetProjectQueryIncludeItem> KNOWN;
    private static final List<GetProjectQueryIncludeItem> VALUES;

    static {
        Map<String, GetProjectQueryIncludeItem> known = new LinkedHashMap<>();
        known.put(ROUTES.value, ROUTES);
        known.put(ROUTES_COUNT.value, ROUTES_COUNT);
        known.put(ROUTES_EXISTS.value, ROUTES_EXISTS);
        known.put(DOMAINS.value, DOMAINS);
        known.put(DOMAINS_COUNT.value, DOMAINS_COUNT);
        known.put(DOMAINS_EXISTS.value, DOMAINS_EXISTS);
        known.put(MESSAGE_STATS.value, MESSAGE_STATS);
        known.put(MESSAGE_STATS_COUNT.value, MESSAGE_STATS_COUNT);
        known.put(MESSAGE_STATS_EXISTS.value, MESSAGE_STATS_EXISTS);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private GetProjectQueryIncludeItem(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static GetProjectQueryIncludeItem of(String value) {
        Objects.requireNonNull(value, "value");
        GetProjectQueryIncludeItem known = KNOWN.get(value);
        return known != null ? known : new GetProjectQueryIncludeItem(value);
    }

    /** The known values, in the order of the specification. */
    public static List<GetProjectQueryIncludeItem> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof GetProjectQueryIncludeItem that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
