// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class GetRouteQueryIncludeItem {
    /** {@code "project"} */
    public static final GetRouteQueryIncludeItem PROJECT = new GetRouteQueryIncludeItem("project");

    /** {@code "projectCount"} */
    public static final GetRouteQueryIncludeItem PROJECT_COUNT = new GetRouteQueryIncludeItem("projectCount");

    /** {@code "projectExists"} */
    public static final GetRouteQueryIncludeItem PROJECT_EXISTS = new GetRouteQueryIncludeItem("projectExists");

    /** {@code "statistics"} */
    public static final GetRouteQueryIncludeItem STATISTICS = new GetRouteQueryIncludeItem("statistics");

    private static final Map<String, GetRouteQueryIncludeItem> KNOWN;
    private static final List<GetRouteQueryIncludeItem> VALUES;

    static {
        Map<String, GetRouteQueryIncludeItem> known = new LinkedHashMap<>();
        known.put(PROJECT.value, PROJECT);
        known.put(PROJECT_COUNT.value, PROJECT_COUNT);
        known.put(PROJECT_EXISTS.value, PROJECT_EXISTS);
        known.put(STATISTICS.value, STATISTICS);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private GetRouteQueryIncludeItem(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static GetRouteQueryIncludeItem of(String value) {
        Objects.requireNonNull(value, "value");
        GetRouteQueryIncludeItem known = KNOWN.get(value);
        return known != null ? known : new GetRouteQueryIncludeItem(value);
    }

    /** The known values, in the order of the specification. */
    public static List<GetRouteQueryIncludeItem> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof GetRouteQueryIncludeItem that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
