// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Query parameters of <code>GET /routes/&#123;routeId&#125;</code> (getRoute).
 *
 * @param includeMachine Include legacy machine observations in open and click totals. Privacy opens are reported in the observed and privacy fields without this option. Optional: null omits it. Sent as <code>include_machine</code>.
 * @param include Optional: null omits it. Sent as <code>include</code>.
 */
public record GetRouteQuery(
        Boolean includeMachine,
        List<GetRouteQueryIncludeItem> include
) implements QueryParameters {
    /** Copies lists and maps into unmodifiable collections. */
    public GetRouteQuery {
        include = Copies.list(include);
    }

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("include_machine", includeMachine);
        parameters.put("include", include);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this GetRouteQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.includeMachine = includeMachine;
        builder.include = include;
        return builder;
    }

    /** Builds a {@link GetRouteQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Boolean includeMachine;
        private List<GetRouteQueryIncludeItem> include;

        private Builder() {
        }

        /** Sets {@code include_machine}. */
        public Builder includeMachine(Boolean includeMachine) {
            this.includeMachine = includeMachine;
            return this;
        }

        /** Sets {@code include}. */
        public Builder include(List<GetRouteQueryIncludeItem> include) {
            this.include = include;
            return this;
        }

        /** Returns the {@link GetRouteQuery}. */
        public GetRouteQuery build() {
            return new GetRouteQuery(includeMachine, include);
        }
    }
}
