// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Query parameters of <code>GET /stats</code> (getStats).
 *
 * @param from Required. Sent as <code>from</code>.
 * @param to Required. Sent as <code>to</code>.
 * @param projectId Optional and nullable: null when absent or null. Sent as <code>project_id</code>.
 * @param includeMachine Optional: null omits it. Sent as <code>include_machine</code>.
 */
public record GetStatsQuery(
        String from,
        String to,
        String projectId,
        Boolean includeMachine
) implements QueryParameters {

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("from", from);
        parameters.put("to", to);
        parameters.put("project_id", projectId);
        parameters.put("include_machine", includeMachine);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this GetStatsQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.from = from;
        builder.to = to;
        builder.projectId = projectId;
        builder.includeMachine = includeMachine;
        return builder;
    }

    /** Builds a {@link GetStatsQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String from;
        private String to;
        private String projectId;
        private Boolean includeMachine;

        private Builder() {
        }

        /** Sets {@code from}. */
        public Builder from(String from) {
            this.from = from;
            return this;
        }

        /** Sets {@code to}. */
        public Builder to(String to) {
            this.to = to;
            return this;
        }

        /** Sets {@code project_id}. */
        public Builder projectId(String projectId) {
            this.projectId = projectId;
            return this;
        }

        /** Sets {@code include_machine}. */
        public Builder includeMachine(Boolean includeMachine) {
            this.includeMachine = includeMachine;
            return this;
        }

        /** Returns the {@link GetStatsQuery}. */
        public GetStatsQuery build() {
            return new GetStatsQuery(from, to, projectId, includeMachine);
        }
    }
}
