// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Query parameters of <code>GET /team</code> (getTeam).
 *
 * @param include Optional: null omits it. Sent as <code>include</code>.
 */
public record GetTeamQuery(
        List<GetTeamQueryIncludeItem> include
) implements QueryParameters {
    /** Copies lists and maps into unmodifiable collections. */
    public GetTeamQuery {
        include = Copies.list(include);
    }

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("include", include);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this GetTeamQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.include = include;
        return builder;
    }

    /** Builds a {@link GetTeamQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private List<GetTeamQueryIncludeItem> include;

        private Builder() {
        }

        /** Sets {@code include}. */
        public Builder include(List<GetTeamQueryIncludeItem> include) {
            this.include = include;
            return this;
        }

        /** Returns the {@link GetTeamQuery}. */
        public GetTeamQuery build() {
            return new GetTeamQuery(include);
        }
    }
}
