// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Query parameters of <code>GET /suppressions</code> (listSuppressions).
 *
 * @param pageSize The number of results that will be returned per page. Optional: null omits it. Sent as <code>page[size]</code>.
 * @param pageCursor The cursor to start the pagination from. Optional: null omits it. Sent as <code>page[cursor]</code>.
 * @param sort Optional: null omits it. Sent as <code>sort</code>.
 * @param filterScope Filter by scope (team, project, route). Optional: null omits it. Sent as <code>filter[scope]</code>.
 * @param filterRouteId Filter by route ID. Optional: null omits it. Sent as <code>filter[route_id]</code>.
 * @param filterProjectId Filter by project ID. Optional: null omits it. Sent as <code>filter[project_id]</code>.
 * @param filterValue Search by email/domain value (partial match). Optional: null omits it. Sent as <code>filter[value]</code>.
 * @param filterReason Optional: null omits it. Sent as <code>filter[reason]</code>.
 * @param filterStartDate Filter suppressions created or updated on or after this ISO 8601 date or datetime. Optional: null omits it. Sent as <code>filter[startDate]</code>.
 * @param filterEndDate Filter suppressions created or updated on or before this ISO 8601 date or datetime. Optional: null omits it. Sent as <code>filter[endDate]</code>.
 */
public record ListSuppressionsQuery(
        Long pageSize,
        String pageCursor,
        List<ListSuppressionsQuerySortItem> sort,
        String filterScope,
        String filterRouteId,
        String filterProjectId,
        String filterValue,
        SuppressionReason filterReason,
        String filterStartDate,
        String filterEndDate
) implements QueryParameters {
    /** Copies lists and maps into unmodifiable collections. */
    public ListSuppressionsQuery {
        sort = Copies.list(sort);
    }

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("page[size]", pageSize);
        parameters.put("page[cursor]", pageCursor);
        parameters.put("sort", sort);
        parameters.put("filter[scope]", filterScope);
        parameters.put("filter[route_id]", filterRouteId);
        parameters.put("filter[project_id]", filterProjectId);
        parameters.put("filter[value]", filterValue);
        parameters.put("filter[reason]", filterReason);
        parameters.put("filter[startDate]", filterStartDate);
        parameters.put("filter[endDate]", filterEndDate);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ListSuppressionsQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.pageSize = pageSize;
        builder.pageCursor = pageCursor;
        builder.sort = sort;
        builder.filterScope = filterScope;
        builder.filterRouteId = filterRouteId;
        builder.filterProjectId = filterProjectId;
        builder.filterValue = filterValue;
        builder.filterReason = filterReason;
        builder.filterStartDate = filterStartDate;
        builder.filterEndDate = filterEndDate;
        return builder;
    }

    /** Builds a {@link ListSuppressionsQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long pageSize;
        private String pageCursor;
        private List<ListSuppressionsQuerySortItem> sort;
        private String filterScope;
        private String filterRouteId;
        private String filterProjectId;
        private String filterValue;
        private SuppressionReason filterReason;
        private String filterStartDate;
        private String filterEndDate;

        private Builder() {
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(Long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[cursor]}. */
        public Builder pageCursor(String pageCursor) {
            this.pageCursor = pageCursor;
            return this;
        }

        /** Sets {@code sort}. */
        public Builder sort(List<ListSuppressionsQuerySortItem> sort) {
            this.sort = sort;
            return this;
        }

        /** Sets {@code filter[scope]}. */
        public Builder filterScope(String filterScope) {
            this.filterScope = filterScope;
            return this;
        }

        /** Sets {@code filter[route_id]}. */
        public Builder filterRouteId(String filterRouteId) {
            this.filterRouteId = filterRouteId;
            return this;
        }

        /** Sets {@code filter[project_id]}. */
        public Builder filterProjectId(String filterProjectId) {
            this.filterProjectId = filterProjectId;
            return this;
        }

        /** Sets {@code filter[value]}. */
        public Builder filterValue(String filterValue) {
            this.filterValue = filterValue;
            return this;
        }

        /** Sets {@code filter[reason]}. */
        public Builder filterReason(SuppressionReason filterReason) {
            this.filterReason = filterReason;
            return this;
        }

        /** Sets {@code filter[startDate]}. */
        public Builder filterStartDate(String filterStartDate) {
            this.filterStartDate = filterStartDate;
            return this;
        }

        /** Sets {@code filter[endDate]}. */
        public Builder filterEndDate(String filterEndDate) {
            this.filterEndDate = filterEndDate;
            return this;
        }

        /** Returns the {@link ListSuppressionsQuery}. */
        public ListSuppressionsQuery build() {
            return new ListSuppressionsQuery(pageSize, pageCursor, sort, filterScope, filterRouteId, filterProjectId, filterValue, filterReason, filterStartDate, filterEndDate);
        }
    }
}
