// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Query parameters of <code>GET /team/members</code> (listTeamMembers).
 *
 * @param pageSize The number of results that will be returned per page. Optional: null omits it. Sent as <code>page[size]</code>.
 * @param pageCursor The cursor to start the pagination from. Optional: null omits it. Sent as <code>page[cursor]</code>.
 */
public record ListTeamMembersQuery(
        Long pageSize,
        String pageCursor
) implements QueryParameters {

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("page[size]", pageSize);
        parameters.put("page[cursor]", pageCursor);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ListTeamMembersQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.pageSize = pageSize;
        builder.pageCursor = pageCursor;
        return builder;
    }

    /** Builds a {@link ListTeamMembersQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long pageSize;
        private String pageCursor;

        private Builder() {
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(Long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[cursor]}. */
        public Builder pageCursor(String pageCursor) {
            this.pageCursor = pageCursor;
            return this;
        }

        /** Returns the {@link ListTeamMembersQuery}. */
        public ListTeamMembersQuery build() {
            return new ListTeamMembersQuery(pageSize, pageCursor);
        }
    }
}
