// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Query parameters of <code>GET /projects/&#123;projectId&#125;/routes</code> (listRoutes).
 *
 * @param pageSize The number of results that will be returned per page. Optional: null omits it. Sent as <code>page[size]</code>.
 * @param pageCursor The cursor to start the pagination from. Optional: null omits it. Sent as <code>page[cursor]</code>.
 * @param sort Optional: null omits it. Sent as <code>sort</code>.
 * @param filterRouteType Optional: null omits it. Sent as <code>filter[route_type]</code>.
 * @param filterIsDefault Optional: null omits it. Sent as <code>filter[is_default]</code>.
 * @param filterSearch Search by name or slug. Optional: null omits it. Sent as <code>filter[search]</code>.
 */
public record ListRoutesQuery(
        Long pageSize,
        String pageCursor,
        List<ListRoutesQuerySortItem> sort,
        RouteType filterRouteType,
        Boolean filterIsDefault,
        String filterSearch
) implements QueryParameters {
    /** Copies lists and maps into unmodifiable collections. */
    public ListRoutesQuery {
        sort = Copies.list(sort);
    }

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("page[size]", pageSize);
        parameters.put("page[cursor]", pageCursor);
        parameters.put("sort", sort);
        parameters.put("filter[route_type]", filterRouteType);
        parameters.put("filter[is_default]", filterIsDefault);
        parameters.put("filter[search]", filterSearch);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ListRoutesQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.pageSize = pageSize;
        builder.pageCursor = pageCursor;
        builder.sort = sort;
        builder.filterRouteType = filterRouteType;
        builder.filterIsDefault = filterIsDefault;
        builder.filterSearch = filterSearch;
        return builder;
    }

    /** Builds a {@link ListRoutesQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long pageSize;
        private String pageCursor;
        private List<ListRoutesQuerySortItem> sort;
        private RouteType filterRouteType;
        private Boolean filterIsDefault;
        private String filterSearch;

        private Builder() {
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(Long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[cursor]}. */
        public Builder pageCursor(String pageCursor) {
            this.pageCursor = pageCursor;
            return this;
        }

        /** Sets {@code sort}. */
        public Builder sort(List<ListRoutesQuerySortItem> sort) {
            this.sort = sort;
            return this;
        }

        /** Sets {@code filter[route_type]}. */
        public Builder filterRouteType(RouteType filterRouteType) {
            this.filterRouteType = filterRouteType;
            return this;
        }

        /** Sets {@code filter[is_default]}. */
        public Builder filterIsDefault(Boolean filterIsDefault) {
            this.filterIsDefault = filterIsDefault;
            return this;
        }

        /** Sets {@code filter[search]}. */
        public Builder filterSearch(String filterSearch) {
            this.filterSearch = filterSearch;
            return this;
        }

        /** Returns the {@link ListRoutesQuery}. */
        public ListRoutesQuery build() {
            return new ListRoutesQuery(pageSize, pageCursor, sort, filterRouteType, filterIsDefault, filterSearch);
        }
    }
}
