// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Query parameters of <code>GET /webhooks</code> (listWebhooks).
 *
 * @param pageSize Optional: null omits it. Sent as <code>page[size]</code>.
 * @param cursor Cursor for the next or previous page. Optional: null omits it. Sent as <code>cursor</code>.
 * @param sort Optional: null omits it. Sent as <code>sort</code>.
 * @param filterProject Filter by project ID. Optional: null omits it. Sent as <code>filter[project]</code>.
 * @param filterEnabled Filter by enabled status. Optional: null omits it. Sent as <code>filter[enabled]</code>.
 * @param filterEvent Filter by specific event type. Optional: null omits it. Sent as <code>filter[event]</code>.
 * @param filterRouteId Filter by route ID. Optional: null omits it. Sent as <code>filter[route_id]</code>.
 * @param filterScope Filter by webhook scope. Optional: null omits it. Sent as <code>filter[scope]</code>.
 * @param filterSearch Search by webhook name or URL. Optional: null omits it. Sent as <code>filter[search]</code>.
 */
public record ListWebhooksQuery(
        Long pageSize,
        String cursor,
        List<ListWebhooksQuerySortItem> sort,
        String filterProject,
        Boolean filterEnabled,
        WebhookEvent filterEvent,
        String filterRouteId,
        WebhookScope filterScope,
        String filterSearch
) implements QueryParameters {
    /** Copies lists and maps into unmodifiable collections. */
    public ListWebhooksQuery {
        sort = Copies.list(sort);
    }

    /** The parameters by wire name, in the order of the specification. {@code null} values are left out when sent. */
    @Override
    public Map<String, Object> toParameters() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("page[size]", pageSize);
        parameters.put("cursor", cursor);
        parameters.put("sort", sort);
        parameters.put("filter[project]", filterProject);
        parameters.put("filter[enabled]", filterEnabled);
        parameters.put("filter[event]", filterEvent);
        parameters.put("filter[route_id]", filterRouteId);
        parameters.put("filter[scope]", filterScope);
        parameters.put("filter[search]", filterSearch);
        return parameters;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ListWebhooksQuery. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.pageSize = pageSize;
        builder.cursor = cursor;
        builder.sort = sort;
        builder.filterProject = filterProject;
        builder.filterEnabled = filterEnabled;
        builder.filterEvent = filterEvent;
        builder.filterRouteId = filterRouteId;
        builder.filterScope = filterScope;
        builder.filterSearch = filterSearch;
        return builder;
    }

    /** Builds a {@link ListWebhooksQuery}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long pageSize;
        private String cursor;
        private List<ListWebhooksQuerySortItem> sort;
        private String filterProject;
        private Boolean filterEnabled;
        private WebhookEvent filterEvent;
        private String filterRouteId;
        private WebhookScope filterScope;
        private String filterSearch;

        private Builder() {
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(Long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code page[size]}. */
        public Builder pageSize(long pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /** Sets {@code cursor}. */
        public Builder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        /** Sets {@code sort}. */
        public Builder sort(List<ListWebhooksQuerySortItem> sort) {
            this.sort = sort;
            return this;
        }

        /** Sets {@code filter[project]}. */
        public Builder filterProject(String filterProject) {
            this.filterProject = filterProject;
            return this;
        }

        /** Sets {@code filter[enabled]}. */
        public Builder filterEnabled(Boolean filterEnabled) {
            this.filterEnabled = filterEnabled;
            return this;
        }

        /** Sets {@code filter[event]}. */
        public Builder filterEvent(WebhookEvent filterEvent) {
            this.filterEvent = filterEvent;
            return this;
        }

        /** Sets {@code filter[route_id]}. */
        public Builder filterRouteId(String filterRouteId) {
            this.filterRouteId = filterRouteId;
            return this;
        }

        /** Sets {@code filter[scope]}. */
        public Builder filterScope(WebhookScope filterScope) {
            this.filterScope = filterScope;
            return this;
        }

        /** Sets {@code filter[search]}. */
        public Builder filterSearch(String filterSearch) {
            this.filterSearch = filterSearch;
            return this;
        }

        /** Returns the {@link ListWebhooksQuery}. */
        public ListWebhooksQuery build() {
            return new ListWebhooksQuery(pageSize, cursor, sort, filterProject, filterEnabled, filterEvent, filterRouteId, filterScope, filterSearch);
        }
    }
}
