// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class ListWebhookDeliveriesQuerySortItem {
    /** {@code "created_at"} */
    public static final ListWebhookDeliveriesQuerySortItem CREATED_AT = new ListWebhookDeliveriesQuerySortItem("created_at");

    /** {@code "-created_at"} */
    public static final ListWebhookDeliveriesQuerySortItem CREATED_AT_DESC = new ListWebhookDeliveriesQuerySortItem("-created_at");

    /** {@code "attempt_number"} */
    public static final ListWebhookDeliveriesQuerySortItem ATTEMPT_NUMBER = new ListWebhookDeliveriesQuerySortItem("attempt_number");

    /** {@code "-attempt_number"} */
    public static final ListWebhookDeliveriesQuerySortItem ATTEMPT_NUMBER_DESC = new ListWebhookDeliveriesQuerySortItem("-attempt_number");

    private static final Map<String, ListWebhookDeliveriesQuerySortItem> KNOWN;
    private static final List<ListWebhookDeliveriesQuerySortItem> VALUES;

    static {
        Map<String, ListWebhookDeliveriesQuerySortItem> known = new LinkedHashMap<>();
        known.put(CREATED_AT.value, CREATED_AT);
        known.put(CREATED_AT_DESC.value, CREATED_AT_DESC);
        known.put(ATTEMPT_NUMBER.value, ATTEMPT_NUMBER);
        known.put(ATTEMPT_NUMBER_DESC.value, ATTEMPT_NUMBER_DESC);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private ListWebhookDeliveriesQuerySortItem(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListWebhookDeliveriesQuerySortItem of(String value) {
        Objects.requireNonNull(value, "value");
        ListWebhookDeliveriesQuerySortItem known = KNOWN.get(value);
        return known != null ? known : new ListWebhookDeliveriesQuerySortItem(value);
    }

    /** The known values, in the order of the specification. */
    public static List<ListWebhookDeliveriesQuerySortItem> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof ListWebhookDeliveriesQuerySortItem that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
