// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class ListMessagesQuerySortItem {
    /** {@code "type"} */
    public static final ListMessagesQuerySortItem TYPE = new ListMessagesQuerySortItem("type");

    /** {@code "-type"} */
    public static final ListMessagesQuerySortItem TYPE_DESC = new ListMessagesQuerySortItem("-type");

    /** {@code "status"} */
    public static final ListMessagesQuerySortItem STATUS = new ListMessagesQuerySortItem("status");

    /** {@code "-status"} */
    public static final ListMessagesQuerySortItem STATUS_DESC = new ListMessagesQuerySortItem("-status");

    /** {@code "from_email"} */
    public static final ListMessagesQuerySortItem FROM_EMAIL = new ListMessagesQuerySortItem("from_email");

    /** {@code "-from_email"} */
    public static final ListMessagesQuerySortItem FROM_EMAIL_DESC = new ListMessagesQuerySortItem("-from_email");

    /** {@code "subject"} */
    public static final ListMessagesQuerySortItem SUBJECT = new ListMessagesQuerySortItem("subject");

    /** {@code "-subject"} */
    public static final ListMessagesQuerySortItem SUBJECT_DESC = new ListMessagesQuerySortItem("-subject");

    /** {@code "created_at"} */
    public static final ListMessagesQuerySortItem CREATED_AT = new ListMessagesQuerySortItem("created_at");

    /** {@code "-created_at"} */
    public static final ListMessagesQuerySortItem CREATED_AT_DESC = new ListMessagesQuerySortItem("-created_at");

    /** {@code "status_changed_at"} */
    public static final ListMessagesQuerySortItem STATUS_CHANGED_AT = new ListMessagesQuerySortItem("status_changed_at");

    /** {@code "-status_changed_at"} */
    public static final ListMessagesQuerySortItem STATUS_CHANGED_AT_DESC = new ListMessagesQuerySortItem("-status_changed_at");

    /** {@code "scheduled_at"} */
    public static final ListMessagesQuerySortItem SCHEDULED_AT = new ListMessagesQuerySortItem("scheduled_at");

    /** {@code "-scheduled_at"} */
    public static final ListMessagesQuerySortItem SCHEDULED_AT_DESC = new ListMessagesQuerySortItem("-scheduled_at");

    private static final Map<String, ListMessagesQuerySortItem> KNOWN;
    private static final List<ListMessagesQuerySortItem> VALUES;

    static {
        Map<String, ListMessagesQuerySortItem> known = new LinkedHashMap<>();
        known.put(TYPE.value, TYPE);
        known.put(TYPE_DESC.value, TYPE_DESC);
        known.put(STATUS.value, STATUS);
        known.put(STATUS_DESC.value, STATUS_DESC);
        known.put(FROM_EMAIL.value, FROM_EMAIL);
        known.put(FROM_EMAIL_DESC.value, FROM_EMAIL_DESC);
        known.put(SUBJECT.value, SUBJECT);
        known.put(SUBJECT_DESC.value, SUBJECT_DESC);
        known.put(CREATED_AT.value, CREATED_AT);
        known.put(CREATED_AT_DESC.value, CREATED_AT_DESC);
        known.put(STATUS_CHANGED_AT.value, STATUS_CHANGED_AT);
        known.put(STATUS_CHANGED_AT_DESC.value, STATUS_CHANGED_AT_DESC);
        known.put(SCHEDULED_AT.value, SCHEDULED_AT);
        known.put(SCHEDULED_AT_DESC.value, SCHEDULED_AT_DESC);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private ListMessagesQuerySortItem(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListMessagesQuerySortItem of(String value) {
        Objects.requireNonNull(value, "value");
        ListMessagesQuerySortItem known = KNOWN.get(value);
        return known != null ? known : new ListMessagesQuerySortItem(value);
    }

    /** The known values, in the order of the specification. */
    public static List<ListMessagesQuerySortItem> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof ListMessagesQuerySortItem that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
