// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param email Always present.
 * @param name Always present; may be null.
 * @param sandboxResult The simulated result for this recipient in a Sandbox project. Lettermint test addresses override the message result. Null for Live messages. Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MessageRecipientData(
        @JsonProperty("email") String email,
        @JsonProperty("name") String name,
        @JsonProperty("sandbox_result") SandboxResult sandboxResult
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this MessageRecipientData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.email = email;
        builder.name = name;
        builder.sandboxResult = sandboxResult;
        return builder;
    }

    /** Builds a {@link MessageRecipientData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String email;
        private String name;
        private SandboxResult sandboxResult;

        private Builder() {
        }

        /** Sets {@code email}. */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code sandbox_result}. */
        public Builder sandboxResult(SandboxResult sandboxResult) {
            this.sandboxResult = sandboxResult;
            return this;
        }

        /** Returns the {@link MessageRecipientData}. */
        public MessageRecipientData build() {
            return new MessageRecipientData(email, name, sandboxResult);
        }
    }
}
