// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param messagesTransactional Always present.
 * @param messagesBroadcast Always present.
 * @param messagesInbound Always present.
 * @param deliverability Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MessageStatsData(
        @JsonProperty("messages_transactional") Long messagesTransactional,
        @JsonProperty("messages_broadcast") Long messagesBroadcast,
        @JsonProperty("messages_inbound") Long messagesInbound,
        @JsonProperty("deliverability") Double deliverability
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this MessageStatsData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.messagesTransactional = messagesTransactional;
        builder.messagesBroadcast = messagesBroadcast;
        builder.messagesInbound = messagesInbound;
        builder.deliverability = deliverability;
        return builder;
    }

    /** Builds a {@link MessageStatsData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long messagesTransactional;
        private Long messagesBroadcast;
        private Long messagesInbound;
        private Double deliverability;

        private Builder() {
        }

        /** Sets {@code messages_transactional}. */
        public Builder messagesTransactional(Long messagesTransactional) {
            this.messagesTransactional = messagesTransactional;
            return this;
        }

        /** Sets {@code messages_transactional}. */
        public Builder messagesTransactional(long messagesTransactional) {
            this.messagesTransactional = messagesTransactional;
            return this;
        }

        /** Sets {@code messages_broadcast}. */
        public Builder messagesBroadcast(Long messagesBroadcast) {
            this.messagesBroadcast = messagesBroadcast;
            return this;
        }

        /** Sets {@code messages_broadcast}. */
        public Builder messagesBroadcast(long messagesBroadcast) {
            this.messagesBroadcast = messagesBroadcast;
            return this;
        }

        /** Sets {@code messages_inbound}. */
        public Builder messagesInbound(Long messagesInbound) {
            this.messagesInbound = messagesInbound;
            return this;
        }

        /** Sets {@code messages_inbound}. */
        public Builder messagesInbound(long messagesInbound) {
            this.messagesInbound = messagesInbound;
            return this;
        }

        /** Sets {@code deliverability}. */
        public Builder deliverability(Double deliverability) {
            this.deliverability = deliverability;
            return this;
        }

        /** Sets {@code deliverability}. */
        public Builder deliverability(double deliverability) {
            this.deliverability = deliverability;
            return this;
        }

        /** Returns the {@link MessageStatsData}. */
        public MessageStatsData build() {
            return new MessageStatsData(messagesTransactional, messagesBroadcast, messagesInbound, deliverability);
        }
    }
}
