// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.Map;

/**
 * @param messageId Always present.
 * @param event Always present.
 * @param tag Always present; may be null.
 * @param tags Always present.
 * @param metadata Always present; may be null.
 * @param timestamp Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MessageEventData(
        @JsonProperty("message_id") String messageId,
        @JsonProperty("event") MessageEventType event,
        @JsonProperty("tag") String tag,
        @JsonProperty("tags") List<MessageTag> tags,
        @JsonProperty("metadata") Map<String, Object> metadata,
        @JsonProperty("timestamp") String timestamp
) {
    /** Copies lists and maps into unmodifiable collections. */
    public MessageEventData {
        tags = Copies.list(tags);
        metadata = Copies.map(metadata);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this MessageEventData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.messageId = messageId;
        builder.event = event;
        builder.tag = tag;
        builder.tags = tags;
        builder.metadata = metadata;
        builder.timestamp = timestamp;
        return builder;
    }

    /** Builds a {@link MessageEventData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String messageId;
        private MessageEventType event;
        private String tag;
        private List<MessageTag> tags;
        private Map<String, Object> metadata;
        private String timestamp;

        private Builder() {
        }

        /** Sets {@code message_id}. */
        public Builder messageId(String messageId) {
            this.messageId = messageId;
            return this;
        }

        /** Sets {@code event}. */
        public Builder event(MessageEventType event) {
            this.event = event;
            return this;
        }

        /** Sets {@code tag}. */
        public Builder tag(String tag) {
            this.tag = tag;
            return this;
        }

        /** Sets {@code tags}. */
        public Builder tags(List<MessageTag> tags) {
            this.tags = tags;
            return this;
        }

        /** Sets {@code metadata}. */
        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = metadata;
            return this;
        }

        /** Sets {@code timestamp}. */
        public Builder timestamp(String timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /** Returns the {@link MessageEventData}. */
        public MessageEventData build() {
            return new MessageEventData(messageId, event, tag, tags, metadata, timestamp);
        }
    }
}
