// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A file attached to the message.
 *
 * @param filename Required.
 * @param content Required.
 * @param contentType The MIME type of the attachment. Supports parameters (e.g. <code>text/calendar; method=REQUEST</code>). If omitted, detected automatically from content or filename. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param contentId Content ID for inline attachments, referenced via <code>cid:</code> in HTML body. If no <code>&#64;</code> is present, <code>&#64;lm</code> is appended automatically. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MessageAttachmentInput(
        @JsonProperty("filename") String filename,
        @JsonProperty("content") String content,
        @JsonProperty("content_type") OptionalNullable<String> contentType,
        @JsonProperty("content_id") OptionalNullable<String> contentId
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this MessageAttachmentInput. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.filename = filename;
        builder.content = content;
        builder.contentType = contentType;
        builder.contentId = contentId;
        return builder;
    }

    /** Builds a {@link MessageAttachmentInput}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String filename;
        private String content;
        private OptionalNullable<String> contentType;
        private OptionalNullable<String> contentId;

        private Builder() {
        }

        /** Sets {@code filename}. */
        public Builder filename(String filename) {
            this.filename = filename;
            return this;
        }

        /** Sets {@code content}. */
        public Builder content(String content) {
            this.content = content;
            return this;
        }

        /** Sets {@code content_type}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder contentType(String contentType) {
            this.contentType = OptionalNullable.of(contentType);
            return this;
        }

        /** Sets {@code content_id}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder contentId(String contentId) {
            this.contentId = OptionalNullable.of(contentId);
            return this;
        }

        /** Returns the {@link MessageAttachmentInput}. */
        public MessageAttachmentInput build() {
            return new MessageAttachmentInput(filename, content, contentType, contentId);
        }
    }
}
