// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.Map;

/**
 * @param id Always present.
 * @param type Always present.
 * @param status Always present.
 * @param deliveryMode Always present.
 * @param sandboxResult Always present; may be null.
 * @param statusChangedAt Always present; may be null.
 * @param scheduledAt Always present; may be null.
 * @param tag Always present; may be null.
 * @param tags Always present.
 * @param fromEmail Always present.
 * @param fromName Always present; may be null.
 * @param replyTo Always present; may be null.
 * @param subject Always present; may be null.
 * @param to Always present; may be null.
 * @param cc Always present; may be null.
 * @param bcc Always present; may be null.
 * @param attachments Always present; may be null.
 * @param metadata Always present; may be null.
 * @param spamScore Overall spam assessment score. Scores below 5 are clean, 5 through 10 indicate potential spam, scores above 10 and below 15 are likely spam, and 15 or higher is definite spam. Null means no assessment is available. Available on plans with Spam Insights. Optional and nullable: null when absent or null.
 * @param spamSymbols Detailed rules that contributed to the spam assessment. Available on plans with Spam Insights in individual-message responses. Optional: null when absent.
 * @param routeId Always present.
 * @param createdAt Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MessageData(
        @JsonProperty("id") String id,
        @JsonProperty("type") MessageType type,
        @JsonProperty("status") MessageStatus status,
        @JsonProperty("delivery_mode") DeliveryMode deliveryMode,
        @JsonProperty("sandbox_result") SandboxResult sandboxResult,
        @JsonProperty("status_changed_at") String statusChangedAt,
        @JsonProperty("scheduled_at") String scheduledAt,
        @JsonProperty("tag") String tag,
        @JsonProperty("tags") List<MessageTag> tags,
        @JsonProperty("from_email") String fromEmail,
        @JsonProperty("from_name") String fromName,
        @JsonProperty("reply_to") List<String> replyTo,
        @JsonProperty("subject") String subject,
        @JsonProperty("to") List<MessageRecipientData> to,
        @JsonProperty("cc") List<MessageRecipientData> cc,
        @JsonProperty("bcc") List<MessageRecipientData> bcc,
        @JsonProperty("attachments") List<MessageAttachmentData> attachments,
        @JsonProperty("metadata") Map<String, String> metadata,
        @JsonProperty("spam_score") Double spamScore,
        @JsonProperty("spam_symbols") List<SpamSymbol> spamSymbols,
        @JsonProperty("route_id") String routeId,
        @JsonProperty("created_at") String createdAt
) {
    /** Copies lists and maps into unmodifiable collections. */
    public MessageData {
        tags = Copies.list(tags);
        replyTo = Copies.list(replyTo);
        to = Copies.list(to);
        cc = Copies.list(cc);
        bcc = Copies.list(bcc);
        attachments = Copies.list(attachments);
        metadata = Copies.map(metadata);
        spamSymbols = Copies.list(spamSymbols);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this MessageData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.type = type;
        builder.status = status;
        builder.deliveryMode = deliveryMode;
        builder.sandboxResult = sandboxResult;
        builder.statusChangedAt = statusChangedAt;
        builder.scheduledAt = scheduledAt;
        builder.tag = tag;
        builder.tags = tags;
        builder.fromEmail = fromEmail;
        builder.fromName = fromName;
        builder.replyTo = replyTo;
        builder.subject = subject;
        builder.to = to;
        builder.cc = cc;
        builder.bcc = bcc;
        builder.attachments = attachments;
        builder.metadata = metadata;
        builder.spamScore = spamScore;
        builder.spamSymbols = spamSymbols;
        builder.routeId = routeId;
        builder.createdAt = createdAt;
        return builder;
    }

    /** Builds a {@link MessageData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private MessageType type;
        private MessageStatus status;
        private DeliveryMode deliveryMode;
        private SandboxResult sandboxResult;
        private String statusChangedAt;
        private String scheduledAt;
        private String tag;
        private List<MessageTag> tags;
        private String fromEmail;
        private String fromName;
        private List<String> replyTo;
        private String subject;
        private List<MessageRecipientData> to;
        private List<MessageRecipientData> cc;
        private List<MessageRecipientData> bcc;
        private List<MessageAttachmentData> attachments;
        private Map<String, String> metadata;
        private Double spamScore;
        private List<SpamSymbol> spamSymbols;
        private String routeId;
        private String createdAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code type}. */
        public Builder type(MessageType type) {
            this.type = type;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(MessageStatus status) {
            this.status = status;
            return this;
        }

        /** Sets {@code delivery_mode}. */
        public Builder deliveryMode(DeliveryMode deliveryMode) {
            this.deliveryMode = deliveryMode;
            return this;
        }

        /** Sets {@code sandbox_result}. */
        public Builder sandboxResult(SandboxResult sandboxResult) {
            this.sandboxResult = sandboxResult;
            return this;
        }

        /** Sets {@code status_changed_at}. */
        public Builder statusChangedAt(String statusChangedAt) {
            this.statusChangedAt = statusChangedAt;
            return this;
        }

        /** Sets {@code scheduled_at}. */
        public Builder scheduledAt(String scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /** Sets {@code tag}. */
        public Builder tag(String tag) {
            this.tag = tag;
            return this;
        }

        /** Sets {@code tags}. */
        public Builder tags(List<MessageTag> tags) {
            this.tags = tags;
            return this;
        }

        /** Sets {@code from_email}. */
        public Builder fromEmail(String fromEmail) {
            this.fromEmail = fromEmail;
            return this;
        }

        /** Sets {@code from_name}. */
        public Builder fromName(String fromName) {
            this.fromName = fromName;
            return this;
        }

        /** Sets {@code reply_to}. */
        public Builder replyTo(List<String> replyTo) {
            this.replyTo = replyTo;
            return this;
        }

        /** Sets {@code subject}. */
        public Builder subject(String subject) {
            this.subject = subject;
            return this;
        }

        /** Sets {@code to}. */
        public Builder to(List<MessageRecipientData> to) {
            this.to = to;
            return this;
        }

        /** Sets {@code cc}. */
        public Builder cc(List<MessageRecipientData> cc) {
            this.cc = cc;
            return this;
        }

        /** Sets {@code bcc}. */
        public Builder bcc(List<MessageRecipientData> bcc) {
            this.bcc = bcc;
            return this;
        }

        /** Sets {@code attachments}. */
        public Builder attachments(List<MessageAttachmentData> attachments) {
            this.attachments = attachments;
            return this;
        }

        /** Sets {@code metadata}. */
        public Builder metadata(Map<String, String> metadata) {
            this.metadata = metadata;
            return this;
        }

        /** Sets {@code spam_score}. */
        public Builder spamScore(Double spamScore) {
            this.spamScore = spamScore;
            return this;
        }

        /** Sets {@code spam_score}. */
        public Builder spamScore(double spamScore) {
            this.spamScore = spamScore;
            return this;
        }

        /** Sets {@code spam_symbols}. */
        public Builder spamSymbols(List<SpamSymbol> spamSymbols) {
            this.spamSymbols = spamSymbols;
            return this;
        }

        /** Sets {@code route_id}. */
        public Builder routeId(String routeId) {
            this.routeId = routeId;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Returns the {@link MessageData}. */
        public MessageData build() {
            return new MessageData(id, type, status, deliveryMode, sandboxResult, statusChangedAt, scheduledAt, tag, tags, fromEmail, fromName, replyTo, subject, to, cc, bcc, attachments, metadata, spamScore, spamSymbols, routeId, createdAt);
        }
    }
}
