// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.BeanProperty;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.ContextualDeserializer;

import java.io.IOException;
import java.util.Objects;

/**
 * A field that is optional and nullable in a request: a <code>null</code> reference omits the field, <code>OptionalNullable.ofNull()</code> sends JSON <code>null</code>, and <code>OptionalNullable.of(value)</code> sends the value.
 *
 * @param <T> the value type
 */
@JsonSerialize(using = OptionalNullable.Serializer.class)
@JsonDeserialize(using = OptionalNullable.Deserializer.class)
public final class OptionalNullable<T> {
    private static final OptionalNullable<?> NULL = new OptionalNullable<>(null);

    private final T value;

    private OptionalNullable(T value) {
        this.value = value;
    }

    /** A present value; {@code null} gives {@link #ofNull()}. */
    public static <T> OptionalNullable<T> of(T value) {
        return value == null ? ofNull() : new OptionalNullable<>(value);
    }

    /** An explicit JSON {@code null}. */
    @SuppressWarnings("unchecked")
    public static <T> OptionalNullable<T> ofNull() {
        return (OptionalNullable<T>) NULL;
    }

    /** The value, or {@code null} for an explicit JSON null. */
    public T value() {
        return value;
    }

    /** Whether this is an explicit JSON null. */
    public boolean isNull() {
        return value == null;
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof OptionalNullable<?> that && Objects.equals(value, that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(value);
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    /** Writes the value, or JSON {@code null}. */
    public static final class Serializer extends JsonSerializer<OptionalNullable<?>> {
        @Override
        public void serialize(OptionalNullable<?> value, JsonGenerator generator, SerializerProvider provider) throws IOException {
            if (value.value == null) {
                generator.writeNull();
            } else {
                provider.defaultSerializeValue(value.value, generator);
            }
        }
    }

    /** Reads a value or JSON {@code null}; an absent field stays a {@code null} reference. */
    public static final class Deserializer extends JsonDeserializer<OptionalNullable<?>> implements ContextualDeserializer {
        private final JavaType valueType;

        /** Used by Jackson. */
        public Deserializer() {
            this(null);
        }

        private Deserializer(JavaType valueType) {
            this.valueType = valueType;
        }

        @Override
        public JsonDeserializer<?> createContextual(DeserializationContext context, BeanProperty property) {
            JavaType type = property != null ? property.getType() : context.getContextualType();
            return new Deserializer(type.containedTypeOrUnknown(0));
        }

        @Override
        public OptionalNullable<?> getNullValue(DeserializationContext context) {
            return OptionalNullable.ofNull();
        }

        @Override
        public Object getAbsentValue(DeserializationContext context) {
            return null;
        }

        @Override
        public OptionalNullable<?> deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            return OptionalNullable.of(context.readValue(parser, valueType));
        }
    }
}
