// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A quarantined inbound message that was queued for webhook delivery.
 *
 * @param messageId Always present.
 * @param status Always present.
 * @param webhookTargetCount The number of webhooks the message is delivered to. Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ProcessInboundMessageResult(
        @JsonProperty("message_id") String messageId,
        @JsonProperty("status") String status,
        @JsonProperty("webhook_target_count") Long webhookTargetCount
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ProcessInboundMessageResult. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.messageId = messageId;
        builder.status = status;
        builder.webhookTargetCount = webhookTargetCount;
        return builder;
    }

    /** Builds a {@link ProcessInboundMessageResult}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String messageId;
        private String status;
        private Long webhookTargetCount;

        private Builder() {
        }

        /** Sets {@code message_id}. */
        public Builder messageId(String messageId) {
            this.messageId = messageId;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /** Sets {@code webhook_target_count}. */
        public Builder webhookTargetCount(Long webhookTargetCount) {
            this.webhookTargetCount = webhookTargetCount;
            return this;
        }

        /** Sets {@code webhook_target_count}. */
        public Builder webhookTargetCount(long webhookTargetCount) {
            this.webhookTargetCount = webhookTargetCount;
            return this;
        }

        /** Returns the {@link ProcessInboundMessageResult}. */
        public ProcessInboundMessageResult build() {
            return new ProcessInboundMessageResult(messageId, status, webhookTargetCount);
        }
    }
}
