// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class ProjectAccessScope {
    /** {@code "all"} */
    public static final ProjectAccessScope ALL = new ProjectAccessScope("all");

    /** {@code "selected"} */
    public static final ProjectAccessScope SELECTED = new ProjectAccessScope("selected");

    private static final Map<String, ProjectAccessScope> KNOWN;
    private static final List<ProjectAccessScope> VALUES;

    static {
        Map<String, ProjectAccessScope> known = new LinkedHashMap<>();
        known.put(ALL.value, ALL);
        known.put(SELECTED.value, SELECTED);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private ProjectAccessScope(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ProjectAccessScope of(String value) {
        Objects.requireNonNull(value, "value");
        ProjectAccessScope known = KNOWN.get(value);
        return known != null ? known : new ProjectAccessScope(value);
    }

    /** The known values, in the order of the specification. */
    public static List<ProjectAccessScope> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof ProjectAccessScope that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
