// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param data Always present.
 * @param message Always present.
 * @param apiToken Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ProjectCreatedData(
        @JsonProperty("data") ProjectData data,
        @JsonProperty("message") String message,
        @JsonProperty("api_token") String apiToken
) {

    /** Credentials (api_token) are shown as {@code [redacted]}. */
    @Override
    public String toString() {
        return "ProjectCreatedData[data=" + data
                + ", message=" + message
                + ", apiToken=" + (apiToken == null ? "null" : "[redacted]") + "]";
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ProjectCreatedData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.data = data;
        builder.message = message;
        builder.apiToken = apiToken;
        return builder;
    }

    /** Builds a {@link ProjectCreatedData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private ProjectData data;
        private String message;
        private String apiToken;

        private Builder() {
        }

        /** Sets {@code data}. */
        public Builder data(ProjectData data) {
            this.data = data;
            return this;
        }

        /** Sets {@code message}. */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /** Sets {@code api_token}. */
        public Builder apiToken(String apiToken) {
            this.apiToken = apiToken;
            return this;
        }

        /** Returns the {@link ProjectCreatedData}. */
        public ProjectCreatedData build() {
            return new ProjectCreatedData(data, message, apiToken);
        }
    }
}
