// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param id Always present.
 * @param name Always present.
 * @param deliveryMode Always present.
 * @param smtpEnabled Always present.
 * @param redactEmailContent Always present.
 * @param defaultRouteId Always present; may be null.
 * @param tokenGeneratedAt Always present; may be null.
 * @param tokenLastUsedAt Always present; may be null.
 * @param tokenLastUsedIp Always present; may be null.
 * @param routes Optional: null when absent.
 * @param routesCount Optional: null when absent.
 * @param domains Optional: null when absent.
 * @param domainsCount Optional: null when absent.
 * @param last28Days Optional and nullable: null when absent or null.
 * @param createdAt Always present.
 * @param updatedAt Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ProjectData(
        @JsonProperty("id") String id,
        @JsonProperty("name") String name,
        @JsonProperty("delivery_mode") DeliveryMode deliveryMode,
        @JsonProperty("smtp_enabled") Boolean smtpEnabled,
        @JsonProperty("redact_email_content") Boolean redactEmailContent,
        @JsonProperty("default_route_id") String defaultRouteId,
        @JsonProperty("token_generated_at") String tokenGeneratedAt,
        @JsonProperty("token_last_used_at") String tokenLastUsedAt,
        @JsonProperty("token_last_used_ip") String tokenLastUsedIp,
        @JsonProperty("routes") List<RouteData> routes,
        @JsonProperty("routes_count") Long routesCount,
        @JsonProperty("domains") List<DomainData> domains,
        @JsonProperty("domains_count") Long domainsCount,
        @JsonProperty("last_28_days") MessageStatsData last28Days,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("updated_at") String updatedAt
) {
    /** Copies lists and maps into unmodifiable collections. */
    public ProjectData {
        routes = Copies.list(routes);
        domains = Copies.list(domains);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ProjectData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.name = name;
        builder.deliveryMode = deliveryMode;
        builder.smtpEnabled = smtpEnabled;
        builder.redactEmailContent = redactEmailContent;
        builder.defaultRouteId = defaultRouteId;
        builder.tokenGeneratedAt = tokenGeneratedAt;
        builder.tokenLastUsedAt = tokenLastUsedAt;
        builder.tokenLastUsedIp = tokenLastUsedIp;
        builder.routes = routes;
        builder.routesCount = routesCount;
        builder.domains = domains;
        builder.domainsCount = domainsCount;
        builder.last28Days = last28Days;
        builder.createdAt = createdAt;
        builder.updatedAt = updatedAt;
        return builder;
    }

    /** Builds a {@link ProjectData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private String name;
        private DeliveryMode deliveryMode;
        private Boolean smtpEnabled;
        private Boolean redactEmailContent;
        private String defaultRouteId;
        private String tokenGeneratedAt;
        private String tokenLastUsedAt;
        private String tokenLastUsedIp;
        private List<RouteData> routes;
        private Long routesCount;
        private List<DomainData> domains;
        private Long domainsCount;
        private MessageStatsData last28Days;
        private String createdAt;
        private String updatedAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code delivery_mode}. */
        public Builder deliveryMode(DeliveryMode deliveryMode) {
            this.deliveryMode = deliveryMode;
            return this;
        }

        /** Sets {@code smtp_enabled}. */
        public Builder smtpEnabled(Boolean smtpEnabled) {
            this.smtpEnabled = smtpEnabled;
            return this;
        }

        /** Sets {@code redact_email_content}. */
        public Builder redactEmailContent(Boolean redactEmailContent) {
            this.redactEmailContent = redactEmailContent;
            return this;
        }

        /** Sets {@code default_route_id}. */
        public Builder defaultRouteId(String defaultRouteId) {
            this.defaultRouteId = defaultRouteId;
            return this;
        }

        /** Sets {@code token_generated_at}. */
        public Builder tokenGeneratedAt(String tokenGeneratedAt) {
            this.tokenGeneratedAt = tokenGeneratedAt;
            return this;
        }

        /** Sets {@code token_last_used_at}. */
        public Builder tokenLastUsedAt(String tokenLastUsedAt) {
            this.tokenLastUsedAt = tokenLastUsedAt;
            return this;
        }

        /** Sets {@code token_last_used_ip}. */
        public Builder tokenLastUsedIp(String tokenLastUsedIp) {
            this.tokenLastUsedIp = tokenLastUsedIp;
            return this;
        }

        /** Sets {@code routes}. */
        public Builder routes(List<RouteData> routes) {
            this.routes = routes;
            return this;
        }

        /** Sets {@code routes_count}. */
        public Builder routesCount(Long routesCount) {
            this.routesCount = routesCount;
            return this;
        }

        /** Sets {@code routes_count}. */
        public Builder routesCount(long routesCount) {
            this.routesCount = routesCount;
            return this;
        }

        /** Sets {@code domains}. */
        public Builder domains(List<DomainData> domains) {
            this.domains = domains;
            return this;
        }

        /** Sets {@code domains_count}. */
        public Builder domainsCount(Long domainsCount) {
            this.domainsCount = domainsCount;
            return this;
        }

        /** Sets {@code domains_count}. */
        public Builder domainsCount(long domainsCount) {
            this.domainsCount = domainsCount;
            return this;
        }

        /** Sets {@code last_28_days}. */
        public Builder last28Days(MessageStatsData last28Days) {
            this.last28Days = last28Days;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Sets {@code updated_at}. */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /** Returns the {@link ProjectData}. */
        public ProjectData build() {
            return new ProjectData(id, name, deliveryMode, smtpEnabled, redactEmailContent, defaultRouteId, tokenGeneratedAt, tokenLastUsedAt, tokenLastUsedIp, routes, routesCount, domains, domainsCount, last28Days, createdAt, updatedAt);
        }
    }
}
