// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import java.util.Map;

/** Query parameters of an operation, implemented by every generated <code>&lt;Op&gt;Query</code>. */
public interface QueryParameters {
    /**
     * The parameters by wire name ({@code page[size]}, {@code filter[status]}, {@code sort}) in the order of the
     * specification. Values are strings, numbers, booleans, open enums, lists or generated records; the SDK
     * serializes them with bracket syntax and leaves out {@code null}.
     *
     * @return a new, modifiable map
     */
    Map<String, Object> toParameters();
}
