// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class RbacPermission {
    /** {@code "team:manage"} */
    public static final RbacPermission TEAM_MANAGE = new RbacPermission("team:manage");

    /** {@code "billing:manage"} */
    public static final RbacPermission BILLING_MANAGE = new RbacPermission("billing:manage");

    /** {@code "security:manage"} */
    public static final RbacPermission SECURITY_MANAGE = new RbacPermission("security:manage");

    /** {@code "audit:read"} */
    public static final RbacPermission AUDIT_READ = new RbacPermission("audit:read");

    /** {@code "support:manage"} */
    public static final RbacPermission SUPPORT_MANAGE = new RbacPermission("support:manage");

    /** {@code "members:read"} */
    public static final RbacPermission MEMBERS_READ = new RbacPermission("members:read");

    /** {@code "members:manage"} */
    public static final RbacPermission MEMBERS_MANAGE = new RbacPermission("members:manage");

    /** {@code "roles:manage"} */
    public static final RbacPermission ROLES_MANAGE = new RbacPermission("roles:manage");

    /** {@code "team_tokens:read"} */
    public static final RbacPermission TEAM_TOKENS_READ = new RbacPermission("team_tokens:read");

    /** {@code "team_tokens:manage"} */
    public static final RbacPermission TEAM_TOKENS_MANAGE = new RbacPermission("team_tokens:manage");

    /** {@code "team_tokens:rotate"} */
    public static final RbacPermission TEAM_TOKENS_ROTATE = new RbacPermission("team_tokens:rotate");

    /** {@code "team_tokens:revoke"} */
    public static final RbacPermission TEAM_TOKENS_REVOKE = new RbacPermission("team_tokens:revoke");

    /** {@code "projects:create"} */
    public static final RbacPermission PROJECTS_CREATE = new RbacPermission("projects:create");

    /** {@code "team_suppressions:read"} */
    public static final RbacPermission TEAM_SUPPRESSIONS_READ = new RbacPermission("team_suppressions:read");

    /** {@code "team_suppressions:add"} */
    public static final RbacPermission TEAM_SUPPRESSIONS_ADD = new RbacPermission("team_suppressions:add");

    /** {@code "team_suppressions:remove"} */
    public static final RbacPermission TEAM_SUPPRESSIONS_REMOVE = new RbacPermission("team_suppressions:remove");

    /** {@code "projects:read"} */
    public static final RbacPermission PROJECTS_READ = new RbacPermission("projects:read");

    /** {@code "projects:manage"} */
    public static final RbacPermission PROJECTS_MANAGE = new RbacPermission("projects:manage");

    /** {@code "projects:delete"} */
    public static final RbacPermission PROJECTS_DELETE = new RbacPermission("projects:delete");

    /** {@code "routes:read"} */
    public static final RbacPermission ROUTES_READ = new RbacPermission("routes:read");

    /** {@code "routes:manage"} */
    public static final RbacPermission ROUTES_MANAGE = new RbacPermission("routes:manage");

    /** {@code "routes:delete"} */
    public static final RbacPermission ROUTES_DELETE = new RbacPermission("routes:delete");

    /** {@code "domains:read"} */
    public static final RbacPermission DOMAINS_READ = new RbacPermission("domains:read");

    /** {@code "domains:manage"} */
    public static final RbacPermission DOMAINS_MANAGE = new RbacPermission("domains:manage");

    /** {@code "domains:delete"} */
    public static final RbacPermission DOMAINS_DELETE = new RbacPermission("domains:delete");

    /** {@code "project_tokens:read"} */
    public static final RbacPermission PROJECT_TOKENS_READ = new RbacPermission("project_tokens:read");

    /** {@code "project_tokens:manage"} */
    public static final RbacPermission PROJECT_TOKENS_MANAGE = new RbacPermission("project_tokens:manage");

    /** {@code "project_tokens:rotate"} */
    public static final RbacPermission PROJECT_TOKENS_ROTATE = new RbacPermission("project_tokens:rotate");

    /** {@code "project_tokens:revoke"} */
    public static final RbacPermission PROJECT_TOKENS_REVOKE = new RbacPermission("project_tokens:revoke");

    /** {@code "webhooks:read"} */
    public static final RbacPermission WEBHOOKS_READ = new RbacPermission("webhooks:read");

    /** {@code "webhooks:manage"} */
    public static final RbacPermission WEBHOOKS_MANAGE = new RbacPermission("webhooks:manage");

    /** {@code "webhooks:delete"} */
    public static final RbacPermission WEBHOOKS_DELETE = new RbacPermission("webhooks:delete");

    /** {@code "webhooks:rotate_secret"} */
    public static final RbacPermission WEBHOOKS_ROTATE_SECRET = new RbacPermission("webhooks:rotate_secret");

    /** {@code "stats:read"} */
    public static final RbacPermission STATS_READ = new RbacPermission("stats:read");

    /** {@code "analytics:read"} */
    public static final RbacPermission ANALYTICS_READ = new RbacPermission("analytics:read");

    /** {@code "messages:read"} */
    public static final RbacPermission MESSAGES_READ = new RbacPermission("messages:read");

    /** {@code "messages:read_content"} */
    public static final RbacPermission MESSAGES_READ_CONTENT = new RbacPermission("messages:read_content");

    /** {@code "messages:send"} */
    public static final RbacPermission MESSAGES_SEND = new RbacPermission("messages:send");

    /** {@code "suppressions:read"} */
    public static final RbacPermission SUPPRESSIONS_READ = new RbacPermission("suppressions:read");

    /** {@code "suppressions:add"} */
    public static final RbacPermission SUPPRESSIONS_ADD = new RbacPermission("suppressions:add");

    /** {@code "suppressions:remove"} */
    public static final RbacPermission SUPPRESSIONS_REMOVE = new RbacPermission("suppressions:remove");

    private static final Map<String, RbacPermission> KNOWN;
    private static final List<RbacPermission> VALUES;

    static {
        Map<String, RbacPermission> known = new LinkedHashMap<>();
        known.put(TEAM_MANAGE.value, TEAM_MANAGE);
        known.put(BILLING_MANAGE.value, BILLING_MANAGE);
        known.put(SECURITY_MANAGE.value, SECURITY_MANAGE);
        known.put(AUDIT_READ.value, AUDIT_READ);
        known.put(SUPPORT_MANAGE.value, SUPPORT_MANAGE);
        known.put(MEMBERS_READ.value, MEMBERS_READ);
        known.put(MEMBERS_MANAGE.value, MEMBERS_MANAGE);
        known.put(ROLES_MANAGE.value, ROLES_MANAGE);
        known.put(TEAM_TOKENS_READ.value, TEAM_TOKENS_READ);
        known.put(TEAM_TOKENS_MANAGE.value, TEAM_TOKENS_MANAGE);
        known.put(TEAM_TOKENS_ROTATE.value, TEAM_TOKENS_ROTATE);
        known.put(TEAM_TOKENS_REVOKE.value, TEAM_TOKENS_REVOKE);
        known.put(PROJECTS_CREATE.value, PROJECTS_CREATE);
        known.put(TEAM_SUPPRESSIONS_READ.value, TEAM_SUPPRESSIONS_READ);
        known.put(TEAM_SUPPRESSIONS_ADD.value, TEAM_SUPPRESSIONS_ADD);
        known.put(TEAM_SUPPRESSIONS_REMOVE.value, TEAM_SUPPRESSIONS_REMOVE);
        known.put(PROJECTS_READ.value, PROJECTS_READ);
        known.put(PROJECTS_MANAGE.value, PROJECTS_MANAGE);
        known.put(PROJECTS_DELETE.value, PROJECTS_DELETE);
        known.put(ROUTES_READ.value, ROUTES_READ);
        known.put(ROUTES_MANAGE.value, ROUTES_MANAGE);
        known.put(ROUTES_DELETE.value, ROUTES_DELETE);
        known.put(DOMAINS_READ.value, DOMAINS_READ);
        known.put(DOMAINS_MANAGE.value, DOMAINS_MANAGE);
        known.put(DOMAINS_DELETE.value, DOMAINS_DELETE);
        known.put(PROJECT_TOKENS_READ.value, PROJECT_TOKENS_READ);
        known.put(PROJECT_TOKENS_MANAGE.value, PROJECT_TOKENS_MANAGE);
        known.put(PROJECT_TOKENS_ROTATE.value, PROJECT_TOKENS_ROTATE);
        known.put(PROJECT_TOKENS_REVOKE.value, PROJECT_TOKENS_REVOKE);
        known.put(WEBHOOKS_READ.value, WEBHOOKS_READ);
        known.put(WEBHOOKS_MANAGE.value, WEBHOOKS_MANAGE);
        known.put(WEBHOOKS_DELETE.value, WEBHOOKS_DELETE);
        known.put(WEBHOOKS_ROTATE_SECRET.value, WEBHOOKS_ROTATE_SECRET);
        known.put(STATS_READ.value, STATS_READ);
        known.put(ANALYTICS_READ.value, ANALYTICS_READ);
        known.put(MESSAGES_READ.value, MESSAGES_READ);
        known.put(MESSAGES_READ_CONTENT.value, MESSAGES_READ_CONTENT);
        known.put(MESSAGES_SEND.value, MESSAGES_SEND);
        known.put(SUPPRESSIONS_READ.value, SUPPRESSIONS_READ);
        known.put(SUPPRESSIONS_ADD.value, SUPPRESSIONS_ADD);
        known.put(SUPPRESSIONS_REMOVE.value, SUPPRESSIONS_REMOVE);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private RbacPermission(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RbacPermission of(String value) {
        Objects.requireNonNull(value, "value");
        RbacPermission known = KNOWN.get(value);
        return known != null ? known : new RbacPermission(value);
    }

    /** The known values, in the order of the specification. */
    public static List<RbacPermission> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof RbacPermission that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
