// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class RbacConflictCode {
    /** {@code "stale_resource"} */
    public static final RbacConflictCode STALE_RESOURCE = new RbacConflictCode("stale_resource");

    /** {@code "owner_protected"} */
    public static final RbacConflictCode OWNER_PROTECTED = new RbacConflictCode("owner_protected");

    /** {@code "last_owner"} */
    public static final RbacConflictCode LAST_OWNER = new RbacConflictCode("last_owner");

    /** {@code "built_in_role_immutable"} */
    public static final RbacConflictCode BUILT_IN_ROLE_IMMUTABLE = new RbacConflictCode("built_in_role_immutable");

    /** {@code "custom_role_requires_pro"} */
    public static final RbacConflictCode CUSTOM_ROLE_REQUIRES_PRO = new RbacConflictCode("custom_role_requires_pro");

    private static final Map<String, RbacConflictCode> KNOWN;
    private static final List<RbacConflictCode> VALUES;

    static {
        Map<String, RbacConflictCode> known = new LinkedHashMap<>();
        known.put(STALE_RESOURCE.value, STALE_RESOURCE);
        known.put(OWNER_PROTECTED.value, OWNER_PROTECTED);
        known.put(LAST_OWNER.value, LAST_OWNER);
        known.put(BUILT_IN_ROLE_IMMUTABLE.value, BUILT_IN_ROLE_IMMUTABLE);
        known.put(CUSTOM_ROLE_REQUIRES_PRO.value, CUSTOM_ROLE_REQUIRES_PRO);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private RbacConflictCode(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RbacConflictCode of(String value) {
        Objects.requireNonNull(value, "value");
        RbacConflictCode known = KNOWN.get(value);
        return known != null ? known : new RbacConflictCode(value);
    }

    /** The known values, in the order of the specification. */
    public static List<RbacConflictCode> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof RbacConflictCode that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
