// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param destination Always present; may be null.
 * @param verified Always present.
 * @param verifiedAt Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ReportForwardingResource(
        @JsonProperty("destination") String destination,
        @JsonProperty("verified") Boolean verified,
        @JsonProperty("verified_at") String verifiedAt
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ReportForwardingResource. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.destination = destination;
        builder.verified = verified;
        builder.verifiedAt = verifiedAt;
        return builder;
    }

    /** Builds a {@link ReportForwardingResource}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String destination;
        private Boolean verified;
        private String verifiedAt;

        private Builder() {
        }

        /** Sets {@code destination}. */
        public Builder destination(String destination) {
            this.destination = destination;
            return this;
        }

        /** Sets {@code verified}. */
        public Builder verified(Boolean verified) {
            this.verified = verified;
            return this;
        }

        /** Sets {@code verified_at}. */
        public Builder verifiedAt(String verifiedAt) {
            this.verifiedAt = verifiedAt;
            return this;
        }

        /** Returns the {@link ReportForwardingResource}. */
        public ReportForwardingResource build() {
            return new ReportForwardingResource(destination, verified, verifiedAt);
        }
    }
}
