// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Route settings available for this route type and team feature access
 *
 * @param disableHostedUnsubscribe Optional: null when absent.
 * @param trackOpens Optional: null when absent.
 * @param trackClicks Optional: null when absent.
 * @param generatePlaintextFallback Optional: null when absent.
 * @param suppressAutoResponders Optional: null when absent.
 * @param suppressDisposableRecipients Optional: null when absent.
 * @param tls Optional: null when absent.
 * @param redactEmailContent Optional: null when absent.
 * @param attachmentDelivery Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RouteDataSettings(
        @JsonProperty("disable_hosted_unsubscribe") Boolean disableHostedUnsubscribe,
        @JsonProperty("track_opens") Boolean trackOpens,
        @JsonProperty("track_clicks") Boolean trackClicks,
        @JsonProperty("generate_plaintext_fallback") Boolean generatePlaintextFallback,
        @JsonProperty("suppress_auto_responders") Boolean suppressAutoResponders,
        @JsonProperty("suppress_disposable_recipients") Boolean suppressDisposableRecipients,
        @JsonProperty("tls") TlsPolicy tls,
        @JsonProperty("redact_email_content") Boolean redactEmailContent,
        @JsonProperty("attachment_delivery") AttachmentDelivery attachmentDelivery
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this RouteDataSettings. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.disableHostedUnsubscribe = disableHostedUnsubscribe;
        builder.trackOpens = trackOpens;
        builder.trackClicks = trackClicks;
        builder.generatePlaintextFallback = generatePlaintextFallback;
        builder.suppressAutoResponders = suppressAutoResponders;
        builder.suppressDisposableRecipients = suppressDisposableRecipients;
        builder.tls = tls;
        builder.redactEmailContent = redactEmailContent;
        builder.attachmentDelivery = attachmentDelivery;
        return builder;
    }

    /** Builds a {@link RouteDataSettings}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Boolean disableHostedUnsubscribe;
        private Boolean trackOpens;
        private Boolean trackClicks;
        private Boolean generatePlaintextFallback;
        private Boolean suppressAutoResponders;
        private Boolean suppressDisposableRecipients;
        private TlsPolicy tls;
        private Boolean redactEmailContent;
        private AttachmentDelivery attachmentDelivery;

        private Builder() {
        }

        /** Sets {@code disable_hosted_unsubscribe}. */
        public Builder disableHostedUnsubscribe(Boolean disableHostedUnsubscribe) {
            this.disableHostedUnsubscribe = disableHostedUnsubscribe;
            return this;
        }

        /** Sets {@code track_opens}. */
        public Builder trackOpens(Boolean trackOpens) {
            this.trackOpens = trackOpens;
            return this;
        }

        /** Sets {@code track_clicks}. */
        public Builder trackClicks(Boolean trackClicks) {
            this.trackClicks = trackClicks;
            return this;
        }

        /** Sets {@code generate_plaintext_fallback}. */
        public Builder generatePlaintextFallback(Boolean generatePlaintextFallback) {
            this.generatePlaintextFallback = generatePlaintextFallback;
            return this;
        }

        /** Sets {@code suppress_auto_responders}. */
        public Builder suppressAutoResponders(Boolean suppressAutoResponders) {
            this.suppressAutoResponders = suppressAutoResponders;
            return this;
        }

        /** Sets {@code suppress_disposable_recipients}. */
        public Builder suppressDisposableRecipients(Boolean suppressDisposableRecipients) {
            this.suppressDisposableRecipients = suppressDisposableRecipients;
            return this;
        }

        /** Sets {@code tls}. */
        public Builder tls(TlsPolicy tls) {
            this.tls = tls;
            return this;
        }

        /** Sets {@code redact_email_content}. */
        public Builder redactEmailContent(Boolean redactEmailContent) {
            this.redactEmailContent = redactEmailContent;
            return this;
        }

        /** Sets {@code attachment_delivery}. */
        public Builder attachmentDelivery(AttachmentDelivery attachmentDelivery) {
            this.attachmentDelivery = attachmentDelivery;
            return this;
        }

        /** Returns the {@link RouteDataSettings}. */
        public RouteDataSettings build() {
            return new RouteDataSettings(disableHostedUnsubscribe, trackOpens, trackClicks, generatePlaintextFallback, suppressAutoResponders, suppressDisposableRecipients, tls, redactEmailContent, attachmentDelivery);
        }
    }
}
