// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param date Always present.
 * @param sentCount Always present.
 * @param deliveredCount Always present.
 * @param openedCount Always present.
 * @param clickedCount Always present.
 * @param hardBounceCount Always present.
 * @param spamComplaintCount Always present.
 * @param inboundReceivedCount Always present.
 * @param observedOpenedCount Optional and nullable: null when absent or null.
 * @param humanOpenedCount Optional and nullable: null when absent or null.
 * @param privacyOpenedCount Optional and nullable: null when absent or null.
 * @param effectiveOpenedCount Always present; may be null.
 * @param machineOpenedCount Always present; may be null.
 * @param machineClickedCount Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RouteStatisticData(
        @JsonProperty("date") String date,
        @JsonProperty("sent_count") Long sentCount,
        @JsonProperty("delivered_count") Long deliveredCount,
        @JsonProperty("opened_count") Long openedCount,
        @JsonProperty("clicked_count") Long clickedCount,
        @JsonProperty("hard_bounce_count") Long hardBounceCount,
        @JsonProperty("spam_complaint_count") Long spamComplaintCount,
        @JsonProperty("inbound_received_count") Long inboundReceivedCount,
        @JsonProperty("observed_opened_count") Long observedOpenedCount,
        @JsonProperty("human_opened_count") Long humanOpenedCount,
        @JsonProperty("privacy_opened_count") Long privacyOpenedCount,
        @JsonProperty("effective_opened_count") Long effectiveOpenedCount,
        @JsonProperty("machine_opened_count") Long machineOpenedCount,
        @JsonProperty("machine_clicked_count") Long machineClickedCount
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this RouteStatisticData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.date = date;
        builder.sentCount = sentCount;
        builder.deliveredCount = deliveredCount;
        builder.openedCount = openedCount;
        builder.clickedCount = clickedCount;
        builder.hardBounceCount = hardBounceCount;
        builder.spamComplaintCount = spamComplaintCount;
        builder.inboundReceivedCount = inboundReceivedCount;
        builder.observedOpenedCount = observedOpenedCount;
        builder.humanOpenedCount = humanOpenedCount;
        builder.privacyOpenedCount = privacyOpenedCount;
        builder.effectiveOpenedCount = effectiveOpenedCount;
        builder.machineOpenedCount = machineOpenedCount;
        builder.machineClickedCount = machineClickedCount;
        return builder;
    }

    /** Builds a {@link RouteStatisticData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String date;
        private Long sentCount;
        private Long deliveredCount;
        private Long openedCount;
        private Long clickedCount;
        private Long hardBounceCount;
        private Long spamComplaintCount;
        private Long inboundReceivedCount;
        private Long observedOpenedCount;
        private Long humanOpenedCount;
        private Long privacyOpenedCount;
        private Long effectiveOpenedCount;
        private Long machineOpenedCount;
        private Long machineClickedCount;

        private Builder() {
        }

        /** Sets {@code date}. */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /** Sets {@code sent_count}. */
        public Builder sentCount(Long sentCount) {
            this.sentCount = sentCount;
            return this;
        }

        /** Sets {@code sent_count}. */
        public Builder sentCount(long sentCount) {
            this.sentCount = sentCount;
            return this;
        }

        /** Sets {@code delivered_count}. */
        public Builder deliveredCount(Long deliveredCount) {
            this.deliveredCount = deliveredCount;
            return this;
        }

        /** Sets {@code delivered_count}. */
        public Builder deliveredCount(long deliveredCount) {
            this.deliveredCount = deliveredCount;
            return this;
        }

        /** Sets {@code opened_count}. */
        public Builder openedCount(Long openedCount) {
            this.openedCount = openedCount;
            return this;
        }

        /** Sets {@code opened_count}. */
        public Builder openedCount(long openedCount) {
            this.openedCount = openedCount;
            return this;
        }

        /** Sets {@code clicked_count}. */
        public Builder clickedCount(Long clickedCount) {
            this.clickedCount = clickedCount;
            return this;
        }

        /** Sets {@code clicked_count}. */
        public Builder clickedCount(long clickedCount) {
            this.clickedCount = clickedCount;
            return this;
        }

        /** Sets {@code hard_bounce_count}. */
        public Builder hardBounceCount(Long hardBounceCount) {
            this.hardBounceCount = hardBounceCount;
            return this;
        }

        /** Sets {@code hard_bounce_count}. */
        public Builder hardBounceCount(long hardBounceCount) {
            this.hardBounceCount = hardBounceCount;
            return this;
        }

        /** Sets {@code spam_complaint_count}. */
        public Builder spamComplaintCount(Long spamComplaintCount) {
            this.spamComplaintCount = spamComplaintCount;
            return this;
        }

        /** Sets {@code spam_complaint_count}. */
        public Builder spamComplaintCount(long spamComplaintCount) {
            this.spamComplaintCount = spamComplaintCount;
            return this;
        }

        /** Sets {@code inbound_received_count}. */
        public Builder inboundReceivedCount(Long inboundReceivedCount) {
            this.inboundReceivedCount = inboundReceivedCount;
            return this;
        }

        /** Sets {@code inbound_received_count}. */
        public Builder inboundReceivedCount(long inboundReceivedCount) {
            this.inboundReceivedCount = inboundReceivedCount;
            return this;
        }

        /** Sets {@code observed_opened_count}. */
        public Builder observedOpenedCount(Long observedOpenedCount) {
            this.observedOpenedCount = observedOpenedCount;
            return this;
        }

        /** Sets {@code observed_opened_count}. */
        public Builder observedOpenedCount(long observedOpenedCount) {
            this.observedOpenedCount = observedOpenedCount;
            return this;
        }

        /** Sets {@code human_opened_count}. */
        public Builder humanOpenedCount(Long humanOpenedCount) {
            this.humanOpenedCount = humanOpenedCount;
            return this;
        }

        /** Sets {@code human_opened_count}. */
        public Builder humanOpenedCount(long humanOpenedCount) {
            this.humanOpenedCount = humanOpenedCount;
            return this;
        }

        /** Sets {@code privacy_opened_count}. */
        public Builder privacyOpenedCount(Long privacyOpenedCount) {
            this.privacyOpenedCount = privacyOpenedCount;
            return this;
        }

        /** Sets {@code privacy_opened_count}. */
        public Builder privacyOpenedCount(long privacyOpenedCount) {
            this.privacyOpenedCount = privacyOpenedCount;
            return this;
        }

        /** Sets {@code effective_opened_count}. */
        public Builder effectiveOpenedCount(Long effectiveOpenedCount) {
            this.effectiveOpenedCount = effectiveOpenedCount;
            return this;
        }

        /** Sets {@code effective_opened_count}. */
        public Builder effectiveOpenedCount(long effectiveOpenedCount) {
            this.effectiveOpenedCount = effectiveOpenedCount;
            return this;
        }

        /** Sets {@code machine_opened_count}. */
        public Builder machineOpenedCount(Long machineOpenedCount) {
            this.machineOpenedCount = machineOpenedCount;
            return this;
        }

        /** Sets {@code machine_opened_count}. */
        public Builder machineOpenedCount(long machineOpenedCount) {
            this.machineOpenedCount = machineOpenedCount;
            return this;
        }

        /** Sets {@code machine_clicked_count}. */
        public Builder machineClickedCount(Long machineClickedCount) {
            this.machineClickedCount = machineClickedCount;
            return this;
        }

        /** Sets {@code machine_clicked_count}. */
        public Builder machineClickedCount(long machineClickedCount) {
            this.machineClickedCount = machineClickedCount;
            return this;
        }

        /** Returns the {@link RouteStatisticData}. */
        public RouteStatisticData build() {
            return new RouteStatisticData(date, sentCount, deliveredCount, openedCount, clickedCount, hardBounceCount, spamComplaintCount, inboundReceivedCount, observedOpenedCount, humanOpenedCount, privacyOpenedCount, effectiveOpenedCount, machineOpenedCount, machineClickedCount);
        }
    }
}
