// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The schedule state of a message after it was rescheduled or canceled.
 *
 * @param messageId Always present.
 * @param status Always present; may be null.
 * @param scheduledAt The scheduled delivery time in ISO 8601 format. Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScheduledMessage(
        @JsonProperty("message_id") String messageId,
        @JsonProperty("status") MessageStatus status,
        @JsonProperty("scheduled_at") String scheduledAt
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ScheduledMessage. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.messageId = messageId;
        builder.status = status;
        builder.scheduledAt = scheduledAt;
        return builder;
    }

    /** Builds a {@link ScheduledMessage}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String messageId;
        private MessageStatus status;
        private String scheduledAt;

        private Builder() {
        }

        /** Sets {@code message_id}. */
        public Builder messageId(String messageId) {
            this.messageId = messageId;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(MessageStatus status) {
            this.status = status;
            return this;
        }

        /** Sets {@code scheduled_at}. */
        public Builder scheduledAt(String scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /** Returns the {@link ScheduledMessage}. */
        public ScheduledMessage build() {
            return new ScheduledMessage(messageId, status, scheduledAt);
        }
    }
}
