// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An accepted message that is scheduled for later delivery.
 *
 * @param messageId Always present.
 * @param status Always present.
 * @param scheduledAt The scheduled delivery time in ISO 8601 format. Always present.
 * @param sandbox Present when the project uses Sandbox delivery. Optional: null when absent.
 * @param sandboxResult The simulated delivery result. Present when the project uses Sandbox delivery. Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScheduledSendMailResponse(
        @JsonProperty("message_id") String messageId,
        @JsonProperty("status") String status,
        @JsonProperty("scheduled_at") String scheduledAt,
        @JsonProperty("sandbox") Boolean sandbox,
        @JsonProperty("sandbox_result") SandboxResult sandboxResult
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ScheduledSendMailResponse. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.messageId = messageId;
        builder.status = status;
        builder.scheduledAt = scheduledAt;
        builder.sandbox = sandbox;
        builder.sandboxResult = sandboxResult;
        return builder;
    }

    /** Builds a {@link ScheduledSendMailResponse}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String messageId;
        private String status;
        private String scheduledAt;
        private Boolean sandbox;
        private SandboxResult sandboxResult;

        private Builder() {
        }

        /** Sets {@code message_id}. */
        public Builder messageId(String messageId) {
            this.messageId = messageId;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /** Sets {@code scheduled_at}. */
        public Builder scheduledAt(String scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /** Sets {@code sandbox}. */
        public Builder sandbox(Boolean sandbox) {
            this.sandbox = sandbox;
            return this;
        }

        /** Sets {@code sandbox_result}. */
        public Builder sandboxResult(SandboxResult sandboxResult) {
            this.sandboxResult = sandboxResult;
            return this;
        }

        /** Returns the {@link ScheduledSendMailResponse}. */
        public ScheduledSendMailResponse build() {
            return new ScheduledSendMailResponse(messageId, status, scheduledAt, sandbox, sandboxResult);
        }
    }
}
