// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Per-email settings that override the selected route settings for this email only.
 *
 * @param trackOpens Optional: null omits it.
 * @param trackClicks Optional: null omits it.
 * @param tls Optional: null omits it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SendMailRequestSettings(
        @JsonProperty("track_opens") Boolean trackOpens,
        @JsonProperty("track_clicks") Boolean trackClicks,
        @JsonProperty("tls") TlsPolicy tls
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this SendMailRequestSettings. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.trackOpens = trackOpens;
        builder.trackClicks = trackClicks;
        builder.tls = tls;
        return builder;
    }

    /** Builds a {@link SendMailRequestSettings}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Boolean trackOpens;
        private Boolean trackClicks;
        private TlsPolicy tls;

        private Builder() {
        }

        /** Sets {@code track_opens}. */
        public Builder trackOpens(Boolean trackOpens) {
            this.trackOpens = trackOpens;
            return this;
        }

        /** Sets {@code track_clicks}. */
        public Builder trackClicks(Boolean trackClicks) {
            this.trackClicks = trackClicks;
            return this;
        }

        /** Sets {@code tls}. */
        public Builder tls(TlsPolicy tls) {
            this.tls = tls;
            return this;
        }

        /** Returns the {@link SendMailRequestSettings}. */
        public SendMailRequestSettings build() {
            return new SendMailRequestSettings(trackOpens, trackClicks, tls);
        }
    }
}
