// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param name Always present.
 * @param score Always present.
 * @param options Always present.
 * @param description Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SpamSymbol(
        @JsonProperty("name") String name,
        @JsonProperty("score") Double score,
        @JsonProperty("options") List<String> options,
        @JsonProperty("description") String description
) {
    /** Copies lists and maps into unmodifiable collections. */
    public SpamSymbol {
        options = Copies.list(options);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this SpamSymbol. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.name = name;
        builder.score = score;
        builder.options = options;
        builder.description = description;
        return builder;
    }

    /** Builds a {@link SpamSymbol}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String name;
        private Double score;
        private List<String> options;
        private String description;

        private Builder() {
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code score}. */
        public Builder score(Double score) {
            this.score = score;
            return this;
        }

        /** Sets {@code score}. */
        public Builder score(double score) {
            this.score = score;
            return this;
        }

        /** Sets {@code options}. */
        public Builder options(List<String> options) {
            this.options = options;
            return this;
        }

        /** Sets {@code description}. */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /** Returns the {@link SpamSymbol}. */
        public SpamSymbol build() {
            return new SpamSymbol(name, score, options, description);
        }
    }
}
