// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param date Always present.
 * @param sent Always present.
 * @param delivered Always present.
 * @param hardBounced Always present.
 * @param spamComplaints Always present.
 * @param opened Null when tracking is not enabled for this context. Always present; may be null.
 * @param clicked Null when tracking is not enabled for this context. Always present; may be null.
 * @param inbound Always present.
 * @param transactional Null for team-scoped stats (only available when project_id is specified). Always present; may be null.
 * @param broadcast Null for team-scoped stats (only available when project_id is specified). Always present; may be null.
 * @param observedOpened Human opens plus unresolved privacy-proxy opens. Optional and nullable: null when absent or null.
 * @param humanOpened Optional and nullable: null when absent or null.
 * @param privacyOpened Optional and nullable: null when absent or null.
 * @param effectiveOpened Always present; may be null.
 * @param machineOpened Always present; may be null.
 * @param machineClicked Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record StatsDailyData(
        @JsonProperty("date") String date,
        @JsonProperty("sent") Long sent,
        @JsonProperty("delivered") Long delivered,
        @JsonProperty("hard_bounced") Long hardBounced,
        @JsonProperty("spam_complaints") Long spamComplaints,
        @JsonProperty("opened") Long opened,
        @JsonProperty("clicked") Long clicked,
        @JsonProperty("inbound") StatsInboundData inbound,
        @JsonProperty("transactional") StatsTypeData transactional,
        @JsonProperty("broadcast") StatsTypeData broadcast,
        @JsonProperty("observed_opened") Long observedOpened,
        @JsonProperty("human_opened") Long humanOpened,
        @JsonProperty("privacy_opened") Long privacyOpened,
        @JsonProperty("effective_opened") Long effectiveOpened,
        @JsonProperty("machine_opened") Long machineOpened,
        @JsonProperty("machine_clicked") Long machineClicked
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this StatsDailyData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.date = date;
        builder.sent = sent;
        builder.delivered = delivered;
        builder.hardBounced = hardBounced;
        builder.spamComplaints = spamComplaints;
        builder.opened = opened;
        builder.clicked = clicked;
        builder.inbound = inbound;
        builder.transactional = transactional;
        builder.broadcast = broadcast;
        builder.observedOpened = observedOpened;
        builder.humanOpened = humanOpened;
        builder.privacyOpened = privacyOpened;
        builder.effectiveOpened = effectiveOpened;
        builder.machineOpened = machineOpened;
        builder.machineClicked = machineClicked;
        return builder;
    }

    /** Builds a {@link StatsDailyData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String date;
        private Long sent;
        private Long delivered;
        private Long hardBounced;
        private Long spamComplaints;
        private Long opened;
        private Long clicked;
        private StatsInboundData inbound;
        private StatsTypeData transactional;
        private StatsTypeData broadcast;
        private Long observedOpened;
        private Long humanOpened;
        private Long privacyOpened;
        private Long effectiveOpened;
        private Long machineOpened;
        private Long machineClicked;

        private Builder() {
        }

        /** Sets {@code date}. */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /** Sets {@code sent}. */
        public Builder sent(Long sent) {
            this.sent = sent;
            return this;
        }

        /** Sets {@code sent}. */
        public Builder sent(long sent) {
            this.sent = sent;
            return this;
        }

        /** Sets {@code delivered}. */
        public Builder delivered(Long delivered) {
            this.delivered = delivered;
            return this;
        }

        /** Sets {@code delivered}. */
        public Builder delivered(long delivered) {
            this.delivered = delivered;
            return this;
        }

        /** Sets {@code hard_bounced}. */
        public Builder hardBounced(Long hardBounced) {
            this.hardBounced = hardBounced;
            return this;
        }

        /** Sets {@code hard_bounced}. */
        public Builder hardBounced(long hardBounced) {
            this.hardBounced = hardBounced;
            return this;
        }

        /** Sets {@code spam_complaints}. */
        public Builder spamComplaints(Long spamComplaints) {
            this.spamComplaints = spamComplaints;
            return this;
        }

        /** Sets {@code spam_complaints}. */
        public Builder spamComplaints(long spamComplaints) {
            this.spamComplaints = spamComplaints;
            return this;
        }

        /** Sets {@code opened}. */
        public Builder opened(Long opened) {
            this.opened = opened;
            return this;
        }

        /** Sets {@code opened}. */
        public Builder opened(long opened) {
            this.opened = opened;
            return this;
        }

        /** Sets {@code clicked}. */
        public Builder clicked(Long clicked) {
            this.clicked = clicked;
            return this;
        }

        /** Sets {@code clicked}. */
        public Builder clicked(long clicked) {
            this.clicked = clicked;
            return this;
        }

        /** Sets {@code inbound}. */
        public Builder inbound(StatsInboundData inbound) {
            this.inbound = inbound;
            return this;
        }

        /** Sets {@code transactional}. */
        public Builder transactional(StatsTypeData transactional) {
            this.transactional = transactional;
            return this;
        }

        /** Sets {@code broadcast}. */
        public Builder broadcast(StatsTypeData broadcast) {
            this.broadcast = broadcast;
            return this;
        }

        /** Sets {@code observed_opened}. */
        public Builder observedOpened(Long observedOpened) {
            this.observedOpened = observedOpened;
            return this;
        }

        /** Sets {@code observed_opened}. */
        public Builder observedOpened(long observedOpened) {
            this.observedOpened = observedOpened;
            return this;
        }

        /** Sets {@code human_opened}. */
        public Builder humanOpened(Long humanOpened) {
            this.humanOpened = humanOpened;
            return this;
        }

        /** Sets {@code human_opened}. */
        public Builder humanOpened(long humanOpened) {
            this.humanOpened = humanOpened;
            return this;
        }

        /** Sets {@code privacy_opened}. */
        public Builder privacyOpened(Long privacyOpened) {
            this.privacyOpened = privacyOpened;
            return this;
        }

        /** Sets {@code privacy_opened}. */
        public Builder privacyOpened(long privacyOpened) {
            this.privacyOpened = privacyOpened;
            return this;
        }

        /** Sets {@code effective_opened}. */
        public Builder effectiveOpened(Long effectiveOpened) {
            this.effectiveOpened = effectiveOpened;
            return this;
        }

        /** Sets {@code effective_opened}. */
        public Builder effectiveOpened(long effectiveOpened) {
            this.effectiveOpened = effectiveOpened;
            return this;
        }

        /** Sets {@code machine_opened}. */
        public Builder machineOpened(Long machineOpened) {
            this.machineOpened = machineOpened;
            return this;
        }

        /** Sets {@code machine_opened}. */
        public Builder machineOpened(long machineOpened) {
            this.machineOpened = machineOpened;
            return this;
        }

        /** Sets {@code machine_clicked}. */
        public Builder machineClicked(Long machineClicked) {
            this.machineClicked = machineClicked;
            return this;
        }

        /** Sets {@code machine_clicked}. */
        public Builder machineClicked(long machineClicked) {
            this.machineClicked = machineClicked;
            return this;
        }

        /** Returns the {@link StatsDailyData}. */
        public StatsDailyData build() {
            return new StatsDailyData(date, sent, delivered, hardBounced, spamComplaints, opened, clicked, inbound, transactional, broadcast, observedOpened, humanOpened, privacyOpened, effectiveOpened, machineOpened, machineClicked);
        }
    }
}
