// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param sent Always present.
 * @param hardBounced Always present.
 * @param spamComplaints Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record StatsTypeData(
        @JsonProperty("sent") Long sent,
        @JsonProperty("hard_bounced") Long hardBounced,
        @JsonProperty("spam_complaints") Long spamComplaints
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this StatsTypeData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.sent = sent;
        builder.hardBounced = hardBounced;
        builder.spamComplaints = spamComplaints;
        return builder;
    }

    /** Builds a {@link StatsTypeData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long sent;
        private Long hardBounced;
        private Long spamComplaints;

        private Builder() {
        }

        /** Sets {@code sent}. */
        public Builder sent(Long sent) {
            this.sent = sent;
            return this;
        }

        /** Sets {@code sent}. */
        public Builder sent(long sent) {
            this.sent = sent;
            return this;
        }

        /** Sets {@code hard_bounced}. */
        public Builder hardBounced(Long hardBounced) {
            this.hardBounced = hardBounced;
            return this;
        }

        /** Sets {@code hard_bounced}. */
        public Builder hardBounced(long hardBounced) {
            this.hardBounced = hardBounced;
            return this;
        }

        /** Sets {@code spam_complaints}. */
        public Builder spamComplaints(Long spamComplaints) {
            this.spamComplaints = spamComplaints;
            return this;
        }

        /** Sets {@code spam_complaints}. */
        public Builder spamComplaints(long spamComplaints) {
            this.spamComplaints = spamComplaints;
            return this;
        }

        /** Returns the {@link StatsTypeData}. */
        public StatsTypeData build() {
            return new StatsTypeData(sent, hardBounced, spamComplaints);
        }
    }
}
