// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param from Always present.
 * @param to Always present.
 * @param totals Always present.
 * @param daily Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record StatsData(
        @JsonProperty("from") String from,
        @JsonProperty("to") String to,
        @JsonProperty("totals") StatsTotalsData totals,
        @JsonProperty("daily") List<StatsDailyData> daily
) {
    /** Copies lists and maps into unmodifiable collections. */
    public StatsData {
        daily = Copies.list(daily);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this StatsData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.from = from;
        builder.to = to;
        builder.totals = totals;
        builder.daily = daily;
        return builder;
    }

    /** Builds a {@link StatsData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String from;
        private String to;
        private StatsTotalsData totals;
        private List<StatsDailyData> daily;

        private Builder() {
        }

        /** Sets {@code from}. */
        public Builder from(String from) {
            this.from = from;
            return this;
        }

        /** Sets {@code to}. */
        public Builder to(String to) {
            this.to = to;
            return this;
        }

        /** Sets {@code totals}. */
        public Builder totals(StatsTotalsData totals) {
            this.totals = totals;
            return this;
        }

        /** Sets {@code daily}. */
        public Builder daily(List<StatsDailyData> daily) {
            this.daily = daily;
            return this;
        }

        /** Returns the {@link StatsData}. */
        public StatsData build() {
            return new StatsData(from, to, totals, daily);
        }
    }
}
