// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param name Required.
 * @param routeType Required.
 * @param slug Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param settings Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundSettings Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundDomain Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundSpamThreshold Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param attachmentDelivery Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record StoreRouteData(
        @JsonProperty("name") String name,
        @JsonProperty("route_type") RouteType routeType,
        @JsonProperty("slug") OptionalNullable<String> slug,
        @JsonProperty("settings") OptionalNullable<UpdateRouteSettingsData> settings,
        @JsonProperty("inbound_settings") OptionalNullable<UpdateRouteInboundSettingsData> inboundSettings,
        @JsonProperty("inbound_domain") OptionalNullable<String> inboundDomain,
        @JsonProperty("inbound_spam_threshold") OptionalNullable<Double> inboundSpamThreshold,
        @JsonProperty("attachment_delivery") OptionalNullable<AttachmentDelivery> attachmentDelivery
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this StoreRouteData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.name = name;
        builder.routeType = routeType;
        builder.slug = slug;
        builder.settings = settings;
        builder.inboundSettings = inboundSettings;
        builder.inboundDomain = inboundDomain;
        builder.inboundSpamThreshold = inboundSpamThreshold;
        builder.attachmentDelivery = attachmentDelivery;
        return builder;
    }

    /** Builds a {@link StoreRouteData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String name;
        private RouteType routeType;
        private OptionalNullable<String> slug;
        private OptionalNullable<UpdateRouteSettingsData> settings;
        private OptionalNullable<UpdateRouteInboundSettingsData> inboundSettings;
        private OptionalNullable<String> inboundDomain;
        private OptionalNullable<Double> inboundSpamThreshold;
        private OptionalNullable<AttachmentDelivery> attachmentDelivery;

        private Builder() {
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code route_type}. */
        public Builder routeType(RouteType routeType) {
            this.routeType = routeType;
            return this;
        }

        /** Sets {@code slug}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder slug(String slug) {
            this.slug = OptionalNullable.of(slug);
            return this;
        }

        /** Sets {@code settings}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder settings(UpdateRouteSettingsData settings) {
            this.settings = OptionalNullable.of(settings);
            return this;
        }

        /** Sets {@code inbound_settings}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundSettings(UpdateRouteInboundSettingsData inboundSettings) {
            this.inboundSettings = OptionalNullable.of(inboundSettings);
            return this;
        }

        /** Sets {@code inbound_domain}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundDomain(String inboundDomain) {
            this.inboundDomain = OptionalNullable.of(inboundDomain);
            return this;
        }

        /** Sets {@code inbound_spam_threshold}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundSpamThreshold(Double inboundSpamThreshold) {
            this.inboundSpamThreshold = OptionalNullable.of(inboundSpamThreshold);
            return this;
        }

        /** Sets {@code inbound_spam_threshold}. */
        public Builder inboundSpamThreshold(double inboundSpamThreshold) {
            this.inboundSpamThreshold = OptionalNullable.of(inboundSpamThreshold);
            return this;
        }

        /** Sets {@code attachment_delivery}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder attachmentDelivery(AttachmentDelivery attachmentDelivery) {
            this.attachmentDelivery = OptionalNullable.of(attachmentDelivery);
            return this;
        }

        /** Returns the {@link StoreRouteData}. */
        public StoreRouteData build() {
            return new StoreRouteData(name, routeType, slug, settings, inboundSettings, inboundDomain, inboundSpamThreshold, attachmentDelivery);
        }
    }
}
