// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param email Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param emails Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param reason Required.
 * @param scope Required.
 * @param routeId Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param projectId Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param appliesTo Mail category to block. Manual suppressions default to <code>all</code>. Use <code>broadcast</code> only at team scope, project scope, or on a broadcast route. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record StoreSuppressionData(
        @JsonProperty("email") OptionalNullable<String> email,
        @JsonProperty("emails") OptionalNullable<List<String>> emails,
        @JsonProperty("reason") SuppressionCreateReason reason,
        @JsonProperty("scope") SuppressionCreateScope scope,
        @JsonProperty("route_id") OptionalNullable<String> routeId,
        @JsonProperty("project_id") OptionalNullable<String> projectId,
        @JsonProperty("applies_to") OptionalNullable<SuppressionAppliesTo> appliesTo
) {
    /** Copies lists and maps into unmodifiable collections. */
    public StoreSuppressionData {
        emails = emails == null || emails.isNull() ? emails : OptionalNullable.of(Copies.list(emails.value()));
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this StoreSuppressionData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.email = email;
        builder.emails = emails;
        builder.reason = reason;
        builder.scope = scope;
        builder.routeId = routeId;
        builder.projectId = projectId;
        builder.appliesTo = appliesTo;
        return builder;
    }

    /** Builds a {@link StoreSuppressionData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private OptionalNullable<String> email;
        private OptionalNullable<List<String>> emails;
        private SuppressionCreateReason reason;
        private SuppressionCreateScope scope;
        private OptionalNullable<String> routeId;
        private OptionalNullable<String> projectId;
        private OptionalNullable<SuppressionAppliesTo> appliesTo;

        private Builder() {
        }

        /** Sets {@code email}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder email(String email) {
            this.email = OptionalNullable.of(email);
            return this;
        }

        /** Sets {@code emails}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder emails(List<String> emails) {
            this.emails = OptionalNullable.of(emails);
            return this;
        }

        /** Sets {@code reason}. */
        public Builder reason(SuppressionCreateReason reason) {
            this.reason = reason;
            return this;
        }

        /** Sets {@code scope}. */
        public Builder scope(SuppressionCreateScope scope) {
            this.scope = scope;
            return this;
        }

        /** Sets {@code route_id}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder routeId(String routeId) {
            this.routeId = OptionalNullable.of(routeId);
            return this;
        }

        /** Sets {@code project_id}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder projectId(String projectId) {
            this.projectId = OptionalNullable.of(projectId);
            return this;
        }

        /** Sets {@code applies_to}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder appliesTo(SuppressionAppliesTo appliesTo) {
            this.appliesTo = OptionalNullable.of(appliesTo);
            return this;
        }

        /** Returns the {@link StoreSuppressionData}. */
        public StoreSuppressionData build() {
            return new StoreSuppressionData(email, emails, reason, scope, routeId, projectId, appliesTo);
        }
    }
}
