// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Reason that the recipient is suppressed.
 *
 * An open enum: values that the API adds later decode as well and keep their raw value.
 */
public final class SuppressionReason {
    /** {@code "spam_complaint"} */
    public static final SuppressionReason SPAM_COMPLAINT = new SuppressionReason("spam_complaint");

    /** {@code "hard_bounce"} */
    public static final SuppressionReason HARD_BOUNCE = new SuppressionReason("hard_bounce");

    /** {@code "unsubscribe"} */
    public static final SuppressionReason UNSUBSCRIBE = new SuppressionReason("unsubscribe");

    /** {@code "manual"} */
    public static final SuppressionReason MANUAL = new SuppressionReason("manual");

    /** {@code "disposable_email"} */
    public static final SuppressionReason DISPOSABLE_EMAIL = new SuppressionReason("disposable_email");

    private static final Map<String, SuppressionReason> KNOWN;
    private static final List<SuppressionReason> VALUES;

    static {
        Map<String, SuppressionReason> known = new LinkedHashMap<>();
        known.put(SPAM_COMPLAINT.value, SPAM_COMPLAINT);
        known.put(HARD_BOUNCE.value, HARD_BOUNCE);
        known.put(UNSUBSCRIBE.value, UNSUBSCRIBE);
        known.put(MANUAL.value, MANUAL);
        known.put(DISPOSABLE_EMAIL.value, DISPOSABLE_EMAIL);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private SuppressionReason(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SuppressionReason of(String value) {
        Objects.requireNonNull(value, "value");
        SuppressionReason known = KNOWN.get(value);
        return known != null ? known : new SuppressionReason(value);
    }

    /** The known values, in the order of the specification. */
    public static List<SuppressionReason> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof SuppressionReason that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
