// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class SuppressionReviewResponseStatus {
    /** {@code "review_ticket_created"} */
    public static final SuppressionReviewResponseStatus REVIEW_TICKET_CREATED = new SuppressionReviewResponseStatus("review_ticket_created");

    /** {@code "review_ticket_exists"} */
    public static final SuppressionReviewResponseStatus REVIEW_TICKET_EXISTS = new SuppressionReviewResponseStatus("review_ticket_exists");

    private static final Map<String, SuppressionReviewResponseStatus> KNOWN;
    private static final List<SuppressionReviewResponseStatus> VALUES;

    static {
        Map<String, SuppressionReviewResponseStatus> known = new LinkedHashMap<>();
        known.put(REVIEW_TICKET_CREATED.value, REVIEW_TICKET_CREATED);
        known.put(REVIEW_TICKET_EXISTS.value, REVIEW_TICKET_EXISTS);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private SuppressionReviewResponseStatus(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SuppressionReviewResponseStatus of(String value) {
        Objects.requireNonNull(value, "value");
        SuppressionReviewResponseStatus known = KNOWN.get(value);
        return known != null ? known : new SuppressionReviewResponseStatus(value);
    }

    /** The known values, in the order of the specification. */
    public static List<SuppressionReviewResponseStatus> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof SuppressionReviewResponseStatus that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
