// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param id Always present.
 * @param available Always present.
 * @param subject Always present; may be null.
 * @param createdAt Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SuppressionSourceMessageData(
        @JsonProperty("id") String id,
        @JsonProperty("available") Boolean available,
        @JsonProperty("subject") String subject,
        @JsonProperty("created_at") String createdAt
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this SuppressionSourceMessageData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.available = available;
        builder.subject = subject;
        builder.createdAt = createdAt;
        return builder;
    }

    /** Builds a {@link SuppressionSourceMessageData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private Boolean available;
        private String subject;
        private String createdAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code available}. */
        public Builder available(Boolean available) {
            this.available = available;
            return this;
        }

        /** Sets {@code subject}. */
        public Builder subject(String subject) {
            this.subject = subject;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Returns the {@link SuppressionSourceMessageData}. */
        public SuppressionSourceMessageData build() {
            return new SuppressionSourceMessageData(id, available, subject, createdAt);
        }
    }
}
