// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Reason that the recipient is suppressed. The <code>disposable_email</code> reason is reserved for route policies.
 *
 * An open enum: values that the API adds later decode as well and keep their raw value.
 */
public final class SuppressionCreateReason {
    /** {@code "spam_complaint"} */
    public static final SuppressionCreateReason SPAM_COMPLAINT = new SuppressionCreateReason("spam_complaint");

    /** {@code "hard_bounce"} */
    public static final SuppressionCreateReason HARD_BOUNCE = new SuppressionCreateReason("hard_bounce");

    /** {@code "unsubscribe"} */
    public static final SuppressionCreateReason UNSUBSCRIBE = new SuppressionCreateReason("unsubscribe");

    /** {@code "manual"} */
    public static final SuppressionCreateReason MANUAL = new SuppressionCreateReason("manual");

    private static final Map<String, SuppressionCreateReason> KNOWN;
    private static final List<SuppressionCreateReason> VALUES;

    static {
        Map<String, SuppressionCreateReason> known = new LinkedHashMap<>();
        known.put(SPAM_COMPLAINT.value, SPAM_COMPLAINT);
        known.put(HARD_BOUNCE.value, HARD_BOUNCE);
        known.put(UNSUBSCRIBE.value, UNSUBSCRIBE);
        known.put(MANUAL.value, MANUAL);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private SuppressionCreateReason(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SuppressionCreateReason of(String value) {
        Objects.requireNonNull(value, "value");
        SuppressionCreateReason known = KNOWN.get(value);
        return known != null ? known : new SuppressionCreateReason(value);
    }

    /** The known values, in the order of the specification. */
    public static List<SuppressionCreateReason> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof SuppressionCreateReason that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
