// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Where the suppression applies.
 *
 * An open enum: values that the API adds later decode as well and keep their raw value.
 */
public final class SuppressionScope {
    /** {@code "global"} */
    public static final SuppressionScope GLOBAL = new SuppressionScope("global");

    /** {@code "team"} */
    public static final SuppressionScope TEAM = new SuppressionScope("team");

    /** {@code "project"} */
    public static final SuppressionScope PROJECT = new SuppressionScope("project");

    /** {@code "route"} */
    public static final SuppressionScope ROUTE = new SuppressionScope("route");

    /** {@code "subscription_group"} */
    public static final SuppressionScope SUBSCRIPTION_GROUP = new SuppressionScope("subscription_group");

    private static final Map<String, SuppressionScope> KNOWN;
    private static final List<SuppressionScope> VALUES;

    static {
        Map<String, SuppressionScope> known = new LinkedHashMap<>();
        known.put(GLOBAL.value, GLOBAL);
        known.put(TEAM.value, TEAM);
        known.put(PROJECT.value, PROJECT);
        known.put(ROUTE.value, ROUTE);
        known.put(SUBSCRIPTION_GROUP.value, SUBSCRIPTION_GROUP);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private SuppressionScope(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SuppressionScope of(String value) {
        Objects.requireNonNull(value, "value");
        SuppressionScope known = KNOWN.get(value);
        return known != null ? known : new SuppressionScope(value);
    }

    /** The known values, in the order of the specification. */
    public static List<SuppressionScope> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof SuppressionScope that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
