// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param id Always present.
 * @param name Always present.
 * @param type Always present.
 * @param plan Always present.
 * @param includedVolume Number of emails included in the team's monthly plan. Always present.
 * @param tier Deprecated alias for <code>included_volume</code>. Always present.
 * @param verifiedAt Always present; may be null.
 * @param features Optional: null when absent.
 * @param addons Optional: null when absent.
 * @param createdAt Always present.
 * @param domainsCount Optional: null when absent.
 * @param projectsCount Optional: null when absent.
 * @param membersCount Optional: null when absent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TeamData(
        @JsonProperty("id") String id,
        @JsonProperty("name") String name,
        @JsonProperty("type") TeamType type,
        @JsonProperty("plan") Plan plan,
        @JsonProperty("included_volume") Long includedVolume,
        @JsonProperty("tier") Long tier,
        @JsonProperty("verified_at") String verifiedAt,
        @JsonProperty("features") List<String> features,
        @JsonProperty("addons") List<TeamAddonData> addons,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("domains_count") Long domainsCount,
        @JsonProperty("projects_count") Long projectsCount,
        @JsonProperty("members_count") Long membersCount
) {
    /** Copies lists and maps into unmodifiable collections. */
    public TeamData {
        features = Copies.list(features);
        addons = Copies.list(addons);
    }

    /**
     * Deprecated alias for <code>included_volume</code>
     *
     * @return {@code tier}
     * @deprecated Deprecated by the API.
     */
    @Deprecated
    public Long tier() {
        return tier;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this TeamData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.name = name;
        builder.type = type;
        builder.plan = plan;
        builder.includedVolume = includedVolume;
        builder.tier = tier;
        builder.verifiedAt = verifiedAt;
        builder.features = features;
        builder.addons = addons;
        builder.createdAt = createdAt;
        builder.domainsCount = domainsCount;
        builder.projectsCount = projectsCount;
        builder.membersCount = membersCount;
        return builder;
    }

    /** Builds a {@link TeamData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private String name;
        private TeamType type;
        private Plan plan;
        private Long includedVolume;
        private Long tier;
        private String verifiedAt;
        private List<String> features;
        private List<TeamAddonData> addons;
        private String createdAt;
        private Long domainsCount;
        private Long projectsCount;
        private Long membersCount;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code type}. */
        public Builder type(TeamType type) {
            this.type = type;
            return this;
        }

        /** Sets {@code plan}. */
        public Builder plan(Plan plan) {
            this.plan = plan;
            return this;
        }

        /** Sets {@code included_volume}. */
        public Builder includedVolume(Long includedVolume) {
            this.includedVolume = includedVolume;
            return this;
        }

        /** Sets {@code included_volume}. */
        public Builder includedVolume(long includedVolume) {
            this.includedVolume = includedVolume;
            return this;
        }

        /** Sets {@code tier}. */
        @Deprecated
        public Builder tier(Long tier) {
            this.tier = tier;
            return this;
        }

        /** Sets {@code tier}. */
        @Deprecated
        public Builder tier(long tier) {
            this.tier = tier;
            return this;
        }

        /** Sets {@code verified_at}. */
        public Builder verifiedAt(String verifiedAt) {
            this.verifiedAt = verifiedAt;
            return this;
        }

        /** Sets {@code features}. */
        public Builder features(List<String> features) {
            this.features = features;
            return this;
        }

        /** Sets {@code addons}. */
        public Builder addons(List<TeamAddonData> addons) {
            this.addons = addons;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Sets {@code domains_count}. */
        public Builder domainsCount(Long domainsCount) {
            this.domainsCount = domainsCount;
            return this;
        }

        /** Sets {@code domains_count}. */
        public Builder domainsCount(long domainsCount) {
            this.domainsCount = domainsCount;
            return this;
        }

        /** Sets {@code projects_count}. */
        public Builder projectsCount(Long projectsCount) {
            this.projectsCount = projectsCount;
            return this;
        }

        /** Sets {@code projects_count}. */
        public Builder projectsCount(long projectsCount) {
            this.projectsCount = projectsCount;
            return this;
        }

        /** Sets {@code members_count}. */
        public Builder membersCount(Long membersCount) {
            this.membersCount = membersCount;
            return this;
        }

        /** Sets {@code members_count}. */
        public Builder membersCount(long membersCount) {
            this.membersCount = membersCount;
            return this;
        }

        /** Returns the {@link TeamData}. */
        public TeamData build() {
            return new TeamData(id, name, type, plan, includedVolume, tier, verifiedAt, features, addons, createdAt, domainsCount, projectsCount, membersCount);
        }
    }
}
