// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param id Always present.
 * @param name Always present.
 * @param email Always present.
 * @param role Always present.
 * @param projectAccess Always present.
 * @param joinedAt Always present; may be null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TeamMemberData(
        @JsonProperty("id") String id,
        @JsonProperty("name") String name,
        @JsonProperty("email") String email,
        @JsonProperty("role") TeamMemberDataRole role,
        @JsonProperty("project_access") TeamMemberProjectAccessData projectAccess,
        @JsonProperty("joined_at") String joinedAt
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this TeamMemberData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.name = name;
        builder.email = email;
        builder.role = role;
        builder.projectAccess = projectAccess;
        builder.joinedAt = joinedAt;
        return builder;
    }

    /** Builds a {@link TeamMemberData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private String name;
        private String email;
        private TeamMemberDataRole role;
        private TeamMemberProjectAccessData projectAccess;
        private String joinedAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code email}. */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /** Sets {@code role}. */
        public Builder role(TeamMemberDataRole role) {
            this.role = role;
            return this;
        }

        /** Sets {@code project_access}. */
        public Builder projectAccess(TeamMemberProjectAccessData projectAccess) {
            this.projectAccess = projectAccess;
            return this;
        }

        /** Sets {@code joined_at}. */
        public Builder joinedAt(String joinedAt) {
            this.joinedAt = joinedAt;
            return this;
        }

        /** Returns the {@link TeamMemberData}. */
        public TeamMemberData build() {
            return new TeamMemberData(id, name, email, role, projectAccess, joinedAt);
        }
    }
}
