// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param currentPeriod Always present.
 * @param historicalUsage Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TeamUsageDetailData(
        @JsonProperty("current_period") TeamUsagePeriodData currentPeriod,
        @JsonProperty("historical_usage") List<TeamUsagePeriodData> historicalUsage
) {
    /** Copies lists and maps into unmodifiable collections. */
    public TeamUsageDetailData {
        historicalUsage = Copies.list(historicalUsage);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this TeamUsageDetailData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.currentPeriod = currentPeriod;
        builder.historicalUsage = historicalUsage;
        return builder;
    }

    /** Builds a {@link TeamUsageDetailData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private TeamUsagePeriodData currentPeriod;
        private List<TeamUsagePeriodData> historicalUsage;

        private Builder() {
        }

        /** Sets {@code current_period}. */
        public Builder currentPeriod(TeamUsagePeriodData currentPeriod) {
            this.currentPeriod = currentPeriod;
            return this;
        }

        /** Sets {@code historical_usage}. */
        public Builder historicalUsage(List<TeamUsagePeriodData> historicalUsage) {
            this.historicalUsage = historicalUsage;
            return this;
        }

        /** Returns the {@link TeamUsageDetailData}. */
        public TeamUsageDetailData build() {
            return new TeamUsageDetailData(currentPeriod, historicalUsage);
        }
    }
}
