// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * The reusable roles of the team.
 *
 * @param data Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TeamRoleListResponse(
        @JsonProperty("data") List<TeamRoleData> data
) {
    /** Copies lists and maps into unmodifiable collections. */
    public TeamRoleListResponse {
        data = Copies.list(data);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this TeamRoleListResponse. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.data = data;
        return builder;
    }

    /** Builds a {@link TeamRoleListResponse}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private List<TeamRoleData> data;

        private Builder() {
        }

        /** Sets {@code data}. */
        public Builder data(List<TeamRoleData> data) {
            this.data = data;
            return this;
        }

        /** Returns the {@link TeamRoleListResponse}. */
        public TeamRoleListResponse build() {
            return new TeamRoleListResponse(data);
        }
    }
}
