// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param usage Always present.
 * @param lastIncrementedAt Always present; may be null.
 * @param periodStart Always present.
 * @param periodEnd Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TeamUsagePeriodData(
        @JsonProperty("usage") Long usage,
        @JsonProperty("last_incremented_at") String lastIncrementedAt,
        @JsonProperty("period_start") String periodStart,
        @JsonProperty("period_end") String periodEnd
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this TeamUsagePeriodData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.usage = usage;
        builder.lastIncrementedAt = lastIncrementedAt;
        builder.periodStart = periodStart;
        builder.periodEnd = periodEnd;
        return builder;
    }

    /** Builds a {@link TeamUsagePeriodData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private Long usage;
        private String lastIncrementedAt;
        private String periodStart;
        private String periodEnd;

        private Builder() {
        }

        /** Sets {@code usage}. */
        public Builder usage(Long usage) {
            this.usage = usage;
            return this;
        }

        /** Sets {@code usage}. */
        public Builder usage(long usage) {
            this.usage = usage;
            return this;
        }

        /** Sets {@code last_incremented_at}. */
        public Builder lastIncrementedAt(String lastIncrementedAt) {
            this.lastIncrementedAt = lastIncrementedAt;
            return this;
        }

        /** Sets {@code period_start}. */
        public Builder periodStart(String periodStart) {
            this.periodStart = periodStart;
            return this;
        }

        /** Sets {@code period_end}. */
        public Builder periodEnd(String periodEnd) {
            this.periodEnd = periodEnd;
            return this;
        }

        /** Returns the {@link TeamUsagePeriodData}. */
        public TeamUsagePeriodData build() {
            return new TeamUsagePeriodData(usage, lastIncrementedAt, periodStart, periodEnd);
        }
    }
}
