// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param scope Always present.
 * @param projects Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TeamMemberProjectAccessData(
        @JsonProperty("scope") ProjectAccessScope scope,
        @JsonProperty("projects") List<TeamMemberProjectAccessDataProjectsItem> projects
) {
    /** Copies lists and maps into unmodifiable collections. */
    public TeamMemberProjectAccessData {
        projects = Copies.list(projects);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this TeamMemberProjectAccessData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.scope = scope;
        builder.projects = projects;
        return builder;
    }

    /** Builds a {@link TeamMemberProjectAccessData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private ProjectAccessScope scope;
        private List<TeamMemberProjectAccessDataProjectsItem> projects;

        private Builder() {
        }

        /** Sets {@code scope}. */
        public Builder scope(ProjectAccessScope scope) {
            this.scope = scope;
            return this;
        }

        /** Sets {@code projects}. */
        public Builder projects(List<TeamMemberProjectAccessDataProjectsItem> projects) {
            this.projects = projects;
            return this;
        }

        /** Returns the {@link TeamMemberProjectAccessData}. */
        public TeamMemberProjectAccessData build() {
            return new TeamMemberProjectAccessData(scope, projects);
        }
    }
}
