// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param projectIds Required.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateDomainProjectsData(
        @JsonProperty("project_ids") List<String> projectIds
) {
    /** Copies lists and maps into unmodifiable collections. */
    public UpdateDomainProjectsData {
        projectIds = Copies.list(projectIds);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateDomainProjectsData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.projectIds = projectIds;
        return builder;
    }

    /** Builds a {@link UpdateDomainProjectsData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private List<String> projectIds;

        private Builder() {
        }

        /** Sets {@code project_ids}. */
        public Builder projectIds(List<String> projectIds) {
            this.projectIds = projectIds;
            return this;
        }

        /** Returns the {@link UpdateDomainProjectsData}. */
        public UpdateDomainProjectsData build() {
            return new UpdateDomainProjectsData(projectIds);
        }
    }
}
