// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param name Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param smtpEnabled Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param redactEmailContent Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param deliveryMode Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param defaultRouteId Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateProjectData(
        @JsonProperty("name") OptionalNullable<String> name,
        @JsonProperty("smtp_enabled") OptionalNullable<Boolean> smtpEnabled,
        @JsonProperty("redact_email_content") OptionalNullable<Boolean> redactEmailContent,
        @JsonProperty("delivery_mode") OptionalNullable<DeliveryMode> deliveryMode,
        @JsonProperty("default_route_id") OptionalNullable<String> defaultRouteId
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateProjectData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.name = name;
        builder.smtpEnabled = smtpEnabled;
        builder.redactEmailContent = redactEmailContent;
        builder.deliveryMode = deliveryMode;
        builder.defaultRouteId = defaultRouteId;
        return builder;
    }

    /** Builds a {@link UpdateProjectData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private OptionalNullable<String> name;
        private OptionalNullable<Boolean> smtpEnabled;
        private OptionalNullable<Boolean> redactEmailContent;
        private OptionalNullable<DeliveryMode> deliveryMode;
        private OptionalNullable<String> defaultRouteId;

        private Builder() {
        }

        /** Sets {@code name}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder name(String name) {
            this.name = OptionalNullable.of(name);
            return this;
        }

        /** Sets {@code smtp_enabled}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder smtpEnabled(Boolean smtpEnabled) {
            this.smtpEnabled = OptionalNullable.of(smtpEnabled);
            return this;
        }

        /** Sets {@code redact_email_content}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder redactEmailContent(Boolean redactEmailContent) {
            this.redactEmailContent = OptionalNullable.of(redactEmailContent);
            return this;
        }

        /** Sets {@code delivery_mode}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder deliveryMode(DeliveryMode deliveryMode) {
            this.deliveryMode = OptionalNullable.of(deliveryMode);
            return this;
        }

        /** Sets {@code default_route_id}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder defaultRouteId(String defaultRouteId) {
            this.defaultRouteId = OptionalNullable.of(defaultRouteId);
            return this;
        }

        /** Returns the {@link UpdateProjectData}. */
        public UpdateProjectData build() {
            return new UpdateProjectData(name, smtpEnabled, redactEmailContent, deliveryMode, defaultRouteId);
        }
    }
}
