// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param scope Required.
 * @param projectIds Optional: null omits it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateTeamMemberAssignmentDataProjectAccess(
        @JsonProperty("scope") ProjectAccessScope scope,
        @JsonProperty("project_ids") List<String> projectIds
) {
    /** Copies lists and maps into unmodifiable collections. */
    public UpdateTeamMemberAssignmentDataProjectAccess {
        projectIds = Copies.list(projectIds);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateTeamMemberAssignmentDataProjectAccess. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.scope = scope;
        builder.projectIds = projectIds;
        return builder;
    }

    /** Builds a {@link UpdateTeamMemberAssignmentDataProjectAccess}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private ProjectAccessScope scope;
        private List<String> projectIds;

        private Builder() {
        }

        /** Sets {@code scope}. */
        public Builder scope(ProjectAccessScope scope) {
            this.scope = scope;
            return this;
        }

        /** Sets {@code project_ids}. */
        public Builder projectIds(List<String> projectIds) {
            this.projectIds = projectIds;
            return this;
        }

        /** Returns the {@link UpdateTeamMemberAssignmentDataProjectAccess}. */
        public UpdateTeamMemberAssignmentDataProjectAccess build() {
            return new UpdateTeamMemberAssignmentDataProjectAccess(scope, projectIds);
        }
    }
}
