// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param name Optional: null omits it.
 * @param url Optional: null omits it.
 * @param events Optional: null omits it.
 * @param enabled Optional: null omits it.
 * @param includeMachineEvents Optional: null omits it.
 * @param deliveryModeFilter Optional: null omits it.
 * @param scope Optional: null omits it.
 * @param projectIds Optional: null omits it.
 * @param routeIds Optional: null omits it.
 * @param routeId Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param basicAuth Write-only credentials. Omit to keep credentials. Null removes Basic Auth. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateWebhookData(
        @JsonProperty("name") String name,
        @JsonProperty("url") String url,
        @JsonProperty("events") List<WebhookEvent> events,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("include_machine_events") Boolean includeMachineEvents,
        @JsonProperty("delivery_mode_filter") WebhookDeliveryModeFilter deliveryModeFilter,
        @JsonProperty("scope") WebhookScope scope,
        @JsonProperty("project_ids") List<String> projectIds,
        @JsonProperty("route_ids") List<String> routeIds,
        @JsonProperty("route_id") OptionalNullable<String> routeId,
        @JsonProperty("basic_auth") OptionalNullable<WebhookBasicAuthData> basicAuth
) {
    /** Copies lists and maps into unmodifiable collections. */
    public UpdateWebhookData {
        events = Copies.list(events);
        projectIds = Copies.list(projectIds);
        routeIds = Copies.list(routeIds);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateWebhookData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.name = name;
        builder.url = url;
        builder.events = events;
        builder.enabled = enabled;
        builder.includeMachineEvents = includeMachineEvents;
        builder.deliveryModeFilter = deliveryModeFilter;
        builder.scope = scope;
        builder.projectIds = projectIds;
        builder.routeIds = routeIds;
        builder.routeId = routeId;
        builder.basicAuth = basicAuth;
        return builder;
    }

    /** Builds a {@link UpdateWebhookData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String name;
        private String url;
        private List<WebhookEvent> events;
        private Boolean enabled;
        private Boolean includeMachineEvents;
        private WebhookDeliveryModeFilter deliveryModeFilter;
        private WebhookScope scope;
        private List<String> projectIds;
        private List<String> routeIds;
        private OptionalNullable<String> routeId;
        private OptionalNullable<WebhookBasicAuthData> basicAuth;

        private Builder() {
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code url}. */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /** Sets {@code events}. */
        public Builder events(List<WebhookEvent> events) {
            this.events = events;
            return this;
        }

        /** Sets {@code enabled}. */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /** Sets {@code include_machine_events}. */
        public Builder includeMachineEvents(Boolean includeMachineEvents) {
            this.includeMachineEvents = includeMachineEvents;
            return this;
        }

        /** Sets {@code delivery_mode_filter}. */
        public Builder deliveryModeFilter(WebhookDeliveryModeFilter deliveryModeFilter) {
            this.deliveryModeFilter = deliveryModeFilter;
            return this;
        }

        /** Sets {@code scope}. */
        public Builder scope(WebhookScope scope) {
            this.scope = scope;
            return this;
        }

        /** Sets {@code project_ids}. */
        public Builder projectIds(List<String> projectIds) {
            this.projectIds = projectIds;
            return this;
        }

        /** Sets {@code route_ids}. */
        public Builder routeIds(List<String> routeIds) {
            this.routeIds = routeIds;
            return this;
        }

        /** Sets {@code route_id}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder routeId(String routeId) {
            this.routeId = OptionalNullable.of(routeId);
            return this;
        }

        /** Sets {@code basic_auth}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder basicAuth(WebhookBasicAuthData basicAuth) {
            this.basicAuth = OptionalNullable.of(basicAuth);
            return this;
        }

        /** Returns the {@link UpdateWebhookData}. */
        public UpdateWebhookData build() {
            return new UpdateWebhookData(name, url, events, enabled, includeMachineEvents, deliveryModeFilter, scope, projectIds, routeIds, routeId, basicAuth);
        }
    }
}
