// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param name Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param settings Route settings. <code>track_opens</code> and <code>track_clicks</code> apply to transactional and broadcast routes when email tracking is available. <code>generate_plaintext_fallback</code> opts in to generated plaintext fallbacks for HTML-only outbound messages; customer-provided plaintext is always preserved. <code>suppress_auto_responders</code> adds outbound headers that suppress auto-responders. <code>suppress_disposable_recipients</code> skips matching recipients for each message without adding them to suppression lists. <code>tls</code> controls whether TLS is opportunistic or enforced. <code>disable_hosted_unsubscribe</code> applies to broadcast routes when enabled for the team. <code>redact_email_content</code> requires email redaction access. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundSettings Inbound route settings. Only accepted for inbound routes. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundDomain Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundSpamThreshold Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param attachmentDelivery Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateRouteData(
        @JsonProperty("name") OptionalNullable<String> name,
        @JsonProperty("settings") OptionalNullable<UpdateRouteSettingsData> settings,
        @JsonProperty("inbound_settings") OptionalNullable<UpdateRouteInboundSettingsData> inboundSettings,
        @JsonProperty("inbound_domain") OptionalNullable<String> inboundDomain,
        @JsonProperty("inbound_spam_threshold") OptionalNullable<Double> inboundSpamThreshold,
        @JsonProperty("attachment_delivery") OptionalNullable<AttachmentDelivery> attachmentDelivery
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateRouteData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.name = name;
        builder.settings = settings;
        builder.inboundSettings = inboundSettings;
        builder.inboundDomain = inboundDomain;
        builder.inboundSpamThreshold = inboundSpamThreshold;
        builder.attachmentDelivery = attachmentDelivery;
        return builder;
    }

    /** Builds a {@link UpdateRouteData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private OptionalNullable<String> name;
        private OptionalNullable<UpdateRouteSettingsData> settings;
        private OptionalNullable<UpdateRouteInboundSettingsData> inboundSettings;
        private OptionalNullable<String> inboundDomain;
        private OptionalNullable<Double> inboundSpamThreshold;
        private OptionalNullable<AttachmentDelivery> attachmentDelivery;

        private Builder() {
        }

        /** Sets {@code name}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder name(String name) {
            this.name = OptionalNullable.of(name);
            return this;
        }

        /** Sets {@code settings}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder settings(UpdateRouteSettingsData settings) {
            this.settings = OptionalNullable.of(settings);
            return this;
        }

        /** Sets {@code inbound_settings}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundSettings(UpdateRouteInboundSettingsData inboundSettings) {
            this.inboundSettings = OptionalNullable.of(inboundSettings);
            return this;
        }

        /** Sets {@code inbound_domain}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundDomain(String inboundDomain) {
            this.inboundDomain = OptionalNullable.of(inboundDomain);
            return this;
        }

        /** Sets {@code inbound_spam_threshold}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundSpamThreshold(Double inboundSpamThreshold) {
            this.inboundSpamThreshold = OptionalNullable.of(inboundSpamThreshold);
            return this;
        }

        /** Sets {@code inbound_spam_threshold}. */
        public Builder inboundSpamThreshold(double inboundSpamThreshold) {
            this.inboundSpamThreshold = OptionalNullable.of(inboundSpamThreshold);
            return this;
        }

        /** Sets {@code attachment_delivery}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder attachmentDelivery(AttachmentDelivery attachmentDelivery) {
            this.attachmentDelivery = OptionalNullable.of(attachmentDelivery);
            return this;
        }

        /** Returns the {@link UpdateRouteData}. */
        public UpdateRouteData build() {
            return new UpdateRouteData(name, settings, inboundSettings, inboundDomain, inboundSpamThreshold, attachmentDelivery);
        }
    }
}
