// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param inboundDomain Custom receiving domain for inbound routes, such as support.example.com or *.m.example.com. Address patterns such as *&#64;*.m.example.com are normalized. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param inboundSpamThreshold Inbound spam threshold for inbound routes. Higher values are more permissive. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param attachmentDelivery Inbound attachment delivery mode. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateRouteInboundSettingsData(
        @JsonProperty("inbound_domain") OptionalNullable<String> inboundDomain,
        @JsonProperty("inbound_spam_threshold") OptionalNullable<Double> inboundSpamThreshold,
        @JsonProperty("attachment_delivery") OptionalNullable<AttachmentDelivery> attachmentDelivery
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateRouteInboundSettingsData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.inboundDomain = inboundDomain;
        builder.inboundSpamThreshold = inboundSpamThreshold;
        builder.attachmentDelivery = attachmentDelivery;
        return builder;
    }

    /** Builds a {@link UpdateRouteInboundSettingsData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private OptionalNullable<String> inboundDomain;
        private OptionalNullable<Double> inboundSpamThreshold;
        private OptionalNullable<AttachmentDelivery> attachmentDelivery;

        private Builder() {
        }

        /** Sets {@code inbound_domain}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundDomain(String inboundDomain) {
            this.inboundDomain = OptionalNullable.of(inboundDomain);
            return this;
        }

        /** Sets {@code inbound_spam_threshold}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder inboundSpamThreshold(Double inboundSpamThreshold) {
            this.inboundSpamThreshold = OptionalNullable.of(inboundSpamThreshold);
            return this;
        }

        /** Sets {@code inbound_spam_threshold}. */
        public Builder inboundSpamThreshold(double inboundSpamThreshold) {
            this.inboundSpamThreshold = OptionalNullable.of(inboundSpamThreshold);
            return this;
        }

        /** Sets {@code attachment_delivery}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder attachmentDelivery(AttachmentDelivery attachmentDelivery) {
            this.attachmentDelivery = OptionalNullable.of(attachmentDelivery);
            return this;
        }

        /** Returns the {@link UpdateRouteInboundSettingsData}. */
        public UpdateRouteInboundSettingsData build() {
            return new UpdateRouteInboundSettingsData(inboundDomain, inboundSpamThreshold, attachmentDelivery);
        }
    }
}
