// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param trackOpens Enable open tracking for transactional and broadcast routes. Requires email tracking access. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param trackClicks Enable click tracking for transactional and broadcast routes. Requires email tracking access. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param generatePlaintextFallback Opt in to generated plaintext fallbacks for HTML-only outbound messages on transactional and broadcast routes. Customer-provided plaintext is always preserved. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param suppressAutoResponders Add outbound headers that suppress auto-responders for transactional and broadcast routes. Customer-provided header values are preserved. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param suppressDisposableRecipients Skip disposable email recipients for transactional and broadcast routes. This check applies to each message and does not add recipients to suppression lists. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param tls TLS delivery policy for transactional and broadcast routes. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param disableHostedUnsubscribe Disable Lettermint-hosted unsubscribe link injection for broadcast routes. Available only when enabled for the team. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 * @param redactEmailContent Redact email content in the dashboard for this route. Requires email redaction access. Optional and nullable: leave it unset to omit it, or pass null to send JSON null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateRouteSettingsData(
        @JsonProperty("track_opens") OptionalNullable<Boolean> trackOpens,
        @JsonProperty("track_clicks") OptionalNullable<Boolean> trackClicks,
        @JsonProperty("generate_plaintext_fallback") OptionalNullable<Boolean> generatePlaintextFallback,
        @JsonProperty("suppress_auto_responders") OptionalNullable<Boolean> suppressAutoResponders,
        @JsonProperty("suppress_disposable_recipients") OptionalNullable<Boolean> suppressDisposableRecipients,
        @JsonProperty("tls") OptionalNullable<TlsPolicy> tls,
        @JsonProperty("disable_hosted_unsubscribe") OptionalNullable<Boolean> disableHostedUnsubscribe,
        @JsonProperty("redact_email_content") OptionalNullable<Boolean> redactEmailContent
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this UpdateRouteSettingsData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.trackOpens = trackOpens;
        builder.trackClicks = trackClicks;
        builder.generatePlaintextFallback = generatePlaintextFallback;
        builder.suppressAutoResponders = suppressAutoResponders;
        builder.suppressDisposableRecipients = suppressDisposableRecipients;
        builder.tls = tls;
        builder.disableHostedUnsubscribe = disableHostedUnsubscribe;
        builder.redactEmailContent = redactEmailContent;
        return builder;
    }

    /** Builds a {@link UpdateRouteSettingsData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private OptionalNullable<Boolean> trackOpens;
        private OptionalNullable<Boolean> trackClicks;
        private OptionalNullable<Boolean> generatePlaintextFallback;
        private OptionalNullable<Boolean> suppressAutoResponders;
        private OptionalNullable<Boolean> suppressDisposableRecipients;
        private OptionalNullable<TlsPolicy> tls;
        private OptionalNullable<Boolean> disableHostedUnsubscribe;
        private OptionalNullable<Boolean> redactEmailContent;

        private Builder() {
        }

        /** Sets {@code track_opens}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder trackOpens(Boolean trackOpens) {
            this.trackOpens = OptionalNullable.of(trackOpens);
            return this;
        }

        /** Sets {@code track_clicks}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder trackClicks(Boolean trackClicks) {
            this.trackClicks = OptionalNullable.of(trackClicks);
            return this;
        }

        /** Sets {@code generate_plaintext_fallback}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder generatePlaintextFallback(Boolean generatePlaintextFallback) {
            this.generatePlaintextFallback = OptionalNullable.of(generatePlaintextFallback);
            return this;
        }

        /** Sets {@code suppress_auto_responders}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder suppressAutoResponders(Boolean suppressAutoResponders) {
            this.suppressAutoResponders = OptionalNullable.of(suppressAutoResponders);
            return this;
        }

        /** Sets {@code suppress_disposable_recipients}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder suppressDisposableRecipients(Boolean suppressDisposableRecipients) {
            this.suppressDisposableRecipients = OptionalNullable.of(suppressDisposableRecipients);
            return this;
        }

        /** Sets {@code tls}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder tls(TlsPolicy tls) {
            this.tls = OptionalNullable.of(tls);
            return this;
        }

        /** Sets {@code disable_hosted_unsubscribe}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder disableHostedUnsubscribe(Boolean disableHostedUnsubscribe) {
            this.disableHostedUnsubscribe = OptionalNullable.of(disableHostedUnsubscribe);
            return this;
        }

        /** Sets {@code redact_email_content}. {@code null} sends JSON null; leave it unset to omit the field. */
        public Builder redactEmailContent(Boolean redactEmailContent) {
            this.redactEmailContent = OptionalNullable.of(redactEmailContent);
            return this;
        }

        /** Returns the {@link UpdateRouteSettingsData}. */
        public UpdateRouteSettingsData build() {
            return new UpdateRouteSettingsData(trackOpens, trackClicks, generatePlaintextFallback, suppressAutoResponders, suppressDisposableRecipients, tls, disableHostedUnsubscribe, redactEmailContent);
        }
    }
}
