// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.Map;

/**
 * @param message Errors overview. Always present.
 * @param errors A detailed description of each field that failed validation. Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ValidationError(
        @JsonProperty("message") String message,
        @JsonProperty("errors") Map<String, List<String>> errors
) {
    /** Copies lists and maps into unmodifiable collections. */
    public ValidationError {
        errors = Copies.map(errors);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this ValidationError. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.message = message;
        builder.errors = errors;
        return builder;
    }

    /** Builds a {@link ValidationError}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String message;
        private Map<String, List<String>> errors;

        private Builder() {
        }

        /** Sets {@code message}. */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /** Sets {@code errors}. */
        public Builder errors(Map<String, List<String>> errors) {
            this.errors = errors;
            return this;
        }

        /** Returns the {@link ValidationError}. */
        public ValidationError build() {
            return new ValidationError(message, errors);
        }
    }
}
