// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param id Always present.
 * @param webhookId Always present.
 * @param eventType Always present.
 * @param sourceScope Always present; may be null.
 * @param sourceProjectId Always present; may be null.
 * @param sourceRouteId Always present; may be null.
 * @param status Always present.
 * @param sandbox Always present.
 * @param attemptNumber Always present.
 * @param httpStatusCode Always present; may be null.
 * @param durationMs Always present; may be null.
 * @param deliveredAt Always present; may be null.
 * @param createdAt Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WebhookDeliveryListData(
        @JsonProperty("id") String id,
        @JsonProperty("webhook_id") String webhookId,
        @JsonProperty("event_type") WebhookEvent eventType,
        @JsonProperty("source_scope") String sourceScope,
        @JsonProperty("source_project_id") String sourceProjectId,
        @JsonProperty("source_route_id") String sourceRouteId,
        @JsonProperty("status") WebhookDeliveryStatus status,
        @JsonProperty("sandbox") Boolean sandbox,
        @JsonProperty("attempt_number") Long attemptNumber,
        @JsonProperty("http_status_code") Long httpStatusCode,
        @JsonProperty("duration_ms") Long durationMs,
        @JsonProperty("delivered_at") String deliveredAt,
        @JsonProperty("created_at") String createdAt
) {

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this WebhookDeliveryListData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.webhookId = webhookId;
        builder.eventType = eventType;
        builder.sourceScope = sourceScope;
        builder.sourceProjectId = sourceProjectId;
        builder.sourceRouteId = sourceRouteId;
        builder.status = status;
        builder.sandbox = sandbox;
        builder.attemptNumber = attemptNumber;
        builder.httpStatusCode = httpStatusCode;
        builder.durationMs = durationMs;
        builder.deliveredAt = deliveredAt;
        builder.createdAt = createdAt;
        return builder;
    }

    /** Builds a {@link WebhookDeliveryListData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private String webhookId;
        private WebhookEvent eventType;
        private String sourceScope;
        private String sourceProjectId;
        private String sourceRouteId;
        private WebhookDeliveryStatus status;
        private Boolean sandbox;
        private Long attemptNumber;
        private Long httpStatusCode;
        private Long durationMs;
        private String deliveredAt;
        private String createdAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code webhook_id}. */
        public Builder webhookId(String webhookId) {
            this.webhookId = webhookId;
            return this;
        }

        /** Sets {@code event_type}. */
        public Builder eventType(WebhookEvent eventType) {
            this.eventType = eventType;
            return this;
        }

        /** Sets {@code source_scope}. */
        public Builder sourceScope(String sourceScope) {
            this.sourceScope = sourceScope;
            return this;
        }

        /** Sets {@code source_project_id}. */
        public Builder sourceProjectId(String sourceProjectId) {
            this.sourceProjectId = sourceProjectId;
            return this;
        }

        /** Sets {@code source_route_id}. */
        public Builder sourceRouteId(String sourceRouteId) {
            this.sourceRouteId = sourceRouteId;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(WebhookDeliveryStatus status) {
            this.status = status;
            return this;
        }

        /** Sets {@code sandbox}. */
        public Builder sandbox(Boolean sandbox) {
            this.sandbox = sandbox;
            return this;
        }

        /** Sets {@code attempt_number}. */
        public Builder attemptNumber(Long attemptNumber) {
            this.attemptNumber = attemptNumber;
            return this;
        }

        /** Sets {@code attempt_number}. */
        public Builder attemptNumber(long attemptNumber) {
            this.attemptNumber = attemptNumber;
            return this;
        }

        /** Sets {@code http_status_code}. */
        public Builder httpStatusCode(Long httpStatusCode) {
            this.httpStatusCode = httpStatusCode;
            return this;
        }

        /** Sets {@code http_status_code}. */
        public Builder httpStatusCode(long httpStatusCode) {
            this.httpStatusCode = httpStatusCode;
            return this;
        }

        /** Sets {@code duration_ms}. */
        public Builder durationMs(Long durationMs) {
            this.durationMs = durationMs;
            return this;
        }

        /** Sets {@code duration_ms}. */
        public Builder durationMs(long durationMs) {
            this.durationMs = durationMs;
            return this;
        }

        /** Sets {@code delivered_at}. */
        public Builder deliveredAt(String deliveredAt) {
            this.deliveredAt = deliveredAt;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Returns the {@link WebhookDeliveryListData}. */
        public WebhookDeliveryListData build() {
            return new WebhookDeliveryListData(id, webhookId, eventType, sourceScope, sourceProjectId, sourceRouteId, status, sandbox, attemptNumber, httpStatusCode, durationMs, deliveredAt, createdAt);
        }
    }
}
