// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class WebhookEvent {
    /** {@code "message.created"} */
    public static final WebhookEvent MESSAGE_CREATED = new WebhookEvent("message.created");

    /** {@code "message.sent"} */
    public static final WebhookEvent MESSAGE_SENT = new WebhookEvent("message.sent");

    /** {@code "message.delivered"} */
    public static final WebhookEvent MESSAGE_DELIVERED = new WebhookEvent("message.delivered");

    /** {@code "message.auto_replied"} */
    public static final WebhookEvent MESSAGE_AUTO_REPLIED = new WebhookEvent("message.auto_replied");

    /** {@code "message.hard_bounced"} */
    public static final WebhookEvent MESSAGE_HARD_BOUNCED = new WebhookEvent("message.hard_bounced");

    /** {@code "message.soft_bounced"} */
    public static final WebhookEvent MESSAGE_SOFT_BOUNCED = new WebhookEvent("message.soft_bounced");

    /** {@code "message.spam_complaint"} */
    public static final WebhookEvent MESSAGE_SPAM_COMPLAINT = new WebhookEvent("message.spam_complaint");

    /** {@code "message.failed"} */
    public static final WebhookEvent MESSAGE_FAILED = new WebhookEvent("message.failed");

    /** {@code "message.suppressed"} */
    public static final WebhookEvent MESSAGE_SUPPRESSED = new WebhookEvent("message.suppressed");

    /** {@code "message.unsubscribed"} */
    public static final WebhookEvent MESSAGE_UNSUBSCRIBED = new WebhookEvent("message.unsubscribed");

    /** {@code "message.opened"} */
    public static final WebhookEvent MESSAGE_OPENED = new WebhookEvent("message.opened");

    /** {@code "message.clicked"} */
    public static final WebhookEvent MESSAGE_CLICKED = new WebhookEvent("message.clicked");

    /** {@code "message.inbound"} */
    public static final WebhookEvent MESSAGE_INBOUND = new WebhookEvent("message.inbound");

    /** {@code "message.policy_rejected"} */
    public static final WebhookEvent MESSAGE_POLICY_REJECTED = new WebhookEvent("message.policy_rejected");

    /** {@code "message.scheduled"} */
    public static final WebhookEvent MESSAGE_SCHEDULED = new WebhookEvent("message.scheduled");

    /** {@code "message.rescheduled"} */
    public static final WebhookEvent MESSAGE_RESCHEDULED = new WebhookEvent("message.rescheduled");

    /** {@code "message.canceled"} */
    public static final WebhookEvent MESSAGE_CANCELED = new WebhookEvent("message.canceled");

    /** {@code "message.released"} */
    public static final WebhookEvent MESSAGE_RELEASED = new WebhookEvent("message.released");

    /** {@code "suppression.added"} */
    public static final WebhookEvent SUPPRESSION_ADDED = new WebhookEvent("suppression.added");

    /** {@code "suppression.removed"} */
    public static final WebhookEvent SUPPRESSION_REMOVED = new WebhookEvent("suppression.removed");

    /** {@code "webhook.test"} */
    public static final WebhookEvent WEBHOOK_TEST = new WebhookEvent("webhook.test");

    private static final Map<String, WebhookEvent> KNOWN;
    private static final List<WebhookEvent> VALUES;

    static {
        Map<String, WebhookEvent> known = new LinkedHashMap<>();
        known.put(MESSAGE_CREATED.value, MESSAGE_CREATED);
        known.put(MESSAGE_SENT.value, MESSAGE_SENT);
        known.put(MESSAGE_DELIVERED.value, MESSAGE_DELIVERED);
        known.put(MESSAGE_AUTO_REPLIED.value, MESSAGE_AUTO_REPLIED);
        known.put(MESSAGE_HARD_BOUNCED.value, MESSAGE_HARD_BOUNCED);
        known.put(MESSAGE_SOFT_BOUNCED.value, MESSAGE_SOFT_BOUNCED);
        known.put(MESSAGE_SPAM_COMPLAINT.value, MESSAGE_SPAM_COMPLAINT);
        known.put(MESSAGE_FAILED.value, MESSAGE_FAILED);
        known.put(MESSAGE_SUPPRESSED.value, MESSAGE_SUPPRESSED);
        known.put(MESSAGE_UNSUBSCRIBED.value, MESSAGE_UNSUBSCRIBED);
        known.put(MESSAGE_OPENED.value, MESSAGE_OPENED);
        known.put(MESSAGE_CLICKED.value, MESSAGE_CLICKED);
        known.put(MESSAGE_INBOUND.value, MESSAGE_INBOUND);
        known.put(MESSAGE_POLICY_REJECTED.value, MESSAGE_POLICY_REJECTED);
        known.put(MESSAGE_SCHEDULED.value, MESSAGE_SCHEDULED);
        known.put(MESSAGE_RESCHEDULED.value, MESSAGE_RESCHEDULED);
        known.put(MESSAGE_CANCELED.value, MESSAGE_CANCELED);
        known.put(MESSAGE_RELEASED.value, MESSAGE_RELEASED);
        known.put(SUPPRESSION_ADDED.value, SUPPRESSION_ADDED);
        known.put(SUPPRESSION_REMOVED.value, SUPPRESSION_REMOVED);
        known.put(WEBHOOK_TEST.value, WEBHOOK_TEST);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private WebhookEvent(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static WebhookEvent of(String value) {
        Objects.requireNonNull(value, "value");
        WebhookEvent known = KNOWN.get(value);
        return known != null ? known : new WebhookEvent(value);
    }

    /** The known values, in the order of the specification. */
    public static List<WebhookEvent> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof WebhookEvent that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
