// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param id Always present.
 * @param scope Always present.
 * @param projectIds Always present.
 * @param routeIds Always present.
 * @param routeId Use route_ids. Always present; may be null.
 * @param name Always present.
 * @param url Always present.
 * @param hasBasicAuth Always present.
 * @param events Always present.
 * @param enabled Always present.
 * @param deliveryModeFilter Always present.
 * @param lastCalledAt Always present; may be null.
 * @param createdAt Always present.
 * @param updatedAt Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WebhookListData(
        @JsonProperty("id") String id,
        @JsonProperty("scope") WebhookScope scope,
        @JsonProperty("project_ids") List<String> projectIds,
        @JsonProperty("route_ids") List<String> routeIds,
        @JsonProperty("route_id") String routeId,
        @JsonProperty("name") String name,
        @JsonProperty("url") String url,
        @JsonProperty("has_basic_auth") Boolean hasBasicAuth,
        @JsonProperty("events") List<String> events,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("delivery_mode_filter") WebhookDeliveryModeFilter deliveryModeFilter,
        @JsonProperty("last_called_at") String lastCalledAt,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("updated_at") String updatedAt
) {
    /** Copies lists and maps into unmodifiable collections. */
    public WebhookListData {
        projectIds = Copies.list(projectIds);
        routeIds = Copies.list(routeIds);
        events = Copies.list(events);
    }

    /**
     * Use route_ids.
     *
     * @return {@code route_id}
     * @deprecated Deprecated by the API.
     */
    @Deprecated
    public String routeId() {
        return routeId;
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this WebhookListData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.scope = scope;
        builder.projectIds = projectIds;
        builder.routeIds = routeIds;
        builder.routeId = routeId;
        builder.name = name;
        builder.url = url;
        builder.hasBasicAuth = hasBasicAuth;
        builder.events = events;
        builder.enabled = enabled;
        builder.deliveryModeFilter = deliveryModeFilter;
        builder.lastCalledAt = lastCalledAt;
        builder.createdAt = createdAt;
        builder.updatedAt = updatedAt;
        return builder;
    }

    /** Builds a {@link WebhookListData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private WebhookScope scope;
        private List<String> projectIds;
        private List<String> routeIds;
        private String routeId;
        private String name;
        private String url;
        private Boolean hasBasicAuth;
        private List<String> events;
        private Boolean enabled;
        private WebhookDeliveryModeFilter deliveryModeFilter;
        private String lastCalledAt;
        private String createdAt;
        private String updatedAt;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code scope}. */
        public Builder scope(WebhookScope scope) {
            this.scope = scope;
            return this;
        }

        /** Sets {@code project_ids}. */
        public Builder projectIds(List<String> projectIds) {
            this.projectIds = projectIds;
            return this;
        }

        /** Sets {@code route_ids}. */
        public Builder routeIds(List<String> routeIds) {
            this.routeIds = routeIds;
            return this;
        }

        /** Sets {@code route_id}. */
        @Deprecated
        public Builder routeId(String routeId) {
            this.routeId = routeId;
            return this;
        }

        /** Sets {@code name}. */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /** Sets {@code url}. */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /** Sets {@code has_basic_auth}. */
        public Builder hasBasicAuth(Boolean hasBasicAuth) {
            this.hasBasicAuth = hasBasicAuth;
            return this;
        }

        /** Sets {@code events}. */
        public Builder events(List<String> events) {
            this.events = events;
            return this;
        }

        /** Sets {@code enabled}. */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /** Sets {@code delivery_mode_filter}. */
        public Builder deliveryModeFilter(WebhookDeliveryModeFilter deliveryModeFilter) {
            this.deliveryModeFilter = deliveryModeFilter;
            return this;
        }

        /** Sets {@code last_called_at}. */
        public Builder lastCalledAt(String lastCalledAt) {
            this.lastCalledAt = lastCalledAt;
            return this;
        }

        /** Sets {@code created_at}. */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Sets {@code updated_at}. */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /** Returns the {@link WebhookListData}. */
        public WebhookListData build() {
            return new WebhookListData(id, scope, projectIds, routeIds, routeId, name, url, hasBasicAuth, events, enabled, deliveryModeFilter, lastCalledAt, createdAt, updatedAt);
        }
    }
}
