// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param username Required.
 * @param password Required.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WebhookBasicAuthData(
        @JsonProperty("username") String username,
        @JsonProperty("password") String password
) {

    /** Credentials (password) are shown as {@code [redacted]}. */
    @Override
    public String toString() {
        return "WebhookBasicAuthData[username=" + username
                + ", password=" + (password == null ? "null" : "[redacted]") + "]";
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this WebhookBasicAuthData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.username = username;
        builder.password = password;
        return builder;
    }

    /** Builds a {@link WebhookBasicAuthData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String username;
        private String password;

        private Builder() {
        }

        /** Sets {@code username}. */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /** Sets {@code password}. */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /** Returns the {@link WebhookBasicAuthData}. */
        public WebhookBasicAuthData build() {
            return new WebhookBasicAuthData(username, password);
        }
    }
}
