// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * @param id Always present.
 * @param webhookId Always present.
 * @param eventType Always present.
 * @param sourceScope Always present; may be null.
 * @param sourceProjectId Always present; may be null.
 * @param sourceRouteId Always present; may be null.
 * @param status Always present.
 * @param sandbox Always present.
 * @param attemptNumber Always present.
 * @param httpStatusCode Always present; may be null.
 * @param durationMs Always present; may be null.
 * @param payload Always present.
 * @param responseBody Always present; may be null.
 * @param responseHeaders Always present; may be null.
 * @param errorMessage Always present; may be null.
 * @param deliveredAt Always present; may be null.
 * @param timestamp Always present.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WebhookDeliveryData(
        @JsonProperty("id") String id,
        @JsonProperty("webhook_id") String webhookId,
        @JsonProperty("event_type") WebhookEvent eventType,
        @JsonProperty("source_scope") String sourceScope,
        @JsonProperty("source_project_id") String sourceProjectId,
        @JsonProperty("source_route_id") String sourceRouteId,
        @JsonProperty("status") WebhookDeliveryStatus status,
        @JsonProperty("sandbox") Boolean sandbox,
        @JsonProperty("attempt_number") Long attemptNumber,
        @JsonProperty("http_status_code") Long httpStatusCode,
        @JsonProperty("duration_ms") Long durationMs,
        @JsonProperty("payload") List<String> payload,
        @JsonProperty("response_body") String responseBody,
        @JsonProperty("response_headers") List<String> responseHeaders,
        @JsonProperty("error_message") String errorMessage,
        @JsonProperty("delivered_at") String deliveredAt,
        @JsonProperty("timestamp") String timestamp
) {
    /** Copies lists and maps into unmodifiable collections. */
    public WebhookDeliveryData {
        payload = Copies.list(payload);
        responseHeaders = Copies.list(responseHeaders);
    }

    /** Returns an empty builder. */
    public static Builder builder() {
        return new Builder();
    }

    /** Returns a builder with the values of this WebhookDeliveryData. */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.webhookId = webhookId;
        builder.eventType = eventType;
        builder.sourceScope = sourceScope;
        builder.sourceProjectId = sourceProjectId;
        builder.sourceRouteId = sourceRouteId;
        builder.status = status;
        builder.sandbox = sandbox;
        builder.attemptNumber = attemptNumber;
        builder.httpStatusCode = httpStatusCode;
        builder.durationMs = durationMs;
        builder.payload = payload;
        builder.responseBody = responseBody;
        builder.responseHeaders = responseHeaders;
        builder.errorMessage = errorMessage;
        builder.deliveredAt = deliveredAt;
        builder.timestamp = timestamp;
        return builder;
    }

    /** Builds a {@link WebhookDeliveryData}. Not thread-safe; the built value is immutable. */
    public static final class Builder {
        private String id;
        private String webhookId;
        private WebhookEvent eventType;
        private String sourceScope;
        private String sourceProjectId;
        private String sourceRouteId;
        private WebhookDeliveryStatus status;
        private Boolean sandbox;
        private Long attemptNumber;
        private Long httpStatusCode;
        private Long durationMs;
        private List<String> payload;
        private String responseBody;
        private List<String> responseHeaders;
        private String errorMessage;
        private String deliveredAt;
        private String timestamp;

        private Builder() {
        }

        /** Sets {@code id}. */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /** Sets {@code webhook_id}. */
        public Builder webhookId(String webhookId) {
            this.webhookId = webhookId;
            return this;
        }

        /** Sets {@code event_type}. */
        public Builder eventType(WebhookEvent eventType) {
            this.eventType = eventType;
            return this;
        }

        /** Sets {@code source_scope}. */
        public Builder sourceScope(String sourceScope) {
            this.sourceScope = sourceScope;
            return this;
        }

        /** Sets {@code source_project_id}. */
        public Builder sourceProjectId(String sourceProjectId) {
            this.sourceProjectId = sourceProjectId;
            return this;
        }

        /** Sets {@code source_route_id}. */
        public Builder sourceRouteId(String sourceRouteId) {
            this.sourceRouteId = sourceRouteId;
            return this;
        }

        /** Sets {@code status}. */
        public Builder status(WebhookDeliveryStatus status) {
            this.status = status;
            return this;
        }

        /** Sets {@code sandbox}. */
        public Builder sandbox(Boolean sandbox) {
            this.sandbox = sandbox;
            return this;
        }

        /** Sets {@code attempt_number}. */
        public Builder attemptNumber(Long attemptNumber) {
            this.attemptNumber = attemptNumber;
            return this;
        }

        /** Sets {@code attempt_number}. */
        public Builder attemptNumber(long attemptNumber) {
            this.attemptNumber = attemptNumber;
            return this;
        }

        /** Sets {@code http_status_code}. */
        public Builder httpStatusCode(Long httpStatusCode) {
            this.httpStatusCode = httpStatusCode;
            return this;
        }

        /** Sets {@code http_status_code}. */
        public Builder httpStatusCode(long httpStatusCode) {
            this.httpStatusCode = httpStatusCode;
            return this;
        }

        /** Sets {@code duration_ms}. */
        public Builder durationMs(Long durationMs) {
            this.durationMs = durationMs;
            return this;
        }

        /** Sets {@code duration_ms}. */
        public Builder durationMs(long durationMs) {
            this.durationMs = durationMs;
            return this;
        }

        /** Sets {@code payload}. */
        public Builder payload(List<String> payload) {
            this.payload = payload;
            return this;
        }

        /** Sets {@code response_body}. */
        public Builder responseBody(String responseBody) {
            this.responseBody = responseBody;
            return this;
        }

        /** Sets {@code response_headers}. */
        public Builder responseHeaders(List<String> responseHeaders) {
            this.responseHeaders = responseHeaders;
            return this;
        }

        /** Sets {@code error_message}. */
        public Builder errorMessage(String errorMessage) {
            this.errorMessage = errorMessage;
            return this;
        }

        /** Sets {@code delivered_at}. */
        public Builder deliveredAt(String deliveredAt) {
            this.deliveredAt = deliveredAt;
            return this;
        }

        /** Sets {@code timestamp}. */
        public Builder timestamp(String timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /** Returns the {@link WebhookDeliveryData}. */
        public WebhookDeliveryData build() {
            return new WebhookDeliveryData(id, webhookId, eventType, sourceScope, sourceProjectId, sourceRouteId, status, sandbox, attemptNumber, httpStatusCode, durationMs, payload, responseBody, responseHeaders, errorMessage, deliveredAt, timestamp);
        }
    }
}
