// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package co.lettermint.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** An open enum: values that the API adds later decode as well and keep their raw value. */
public final class WebhookDeliveryStatus {
    /** {@code "pending"} */
    public static final WebhookDeliveryStatus PENDING = new WebhookDeliveryStatus("pending");

    /** {@code "success"} */
    public static final WebhookDeliveryStatus SUCCESS = new WebhookDeliveryStatus("success");

    /** {@code "failed"} */
    public static final WebhookDeliveryStatus FAILED = new WebhookDeliveryStatus("failed");

    /** {@code "client_error"} */
    public static final WebhookDeliveryStatus CLIENT_ERROR = new WebhookDeliveryStatus("client_error");

    /** {@code "server_error"} */
    public static final WebhookDeliveryStatus SERVER_ERROR = new WebhookDeliveryStatus("server_error");

    /** {@code "timeout"} */
    public static final WebhookDeliveryStatus TIMEOUT = new WebhookDeliveryStatus("timeout");

    private static final Map<String, WebhookDeliveryStatus> KNOWN;
    private static final List<WebhookDeliveryStatus> VALUES;

    static {
        Map<String, WebhookDeliveryStatus> known = new LinkedHashMap<>();
        known.put(PENDING.value, PENDING);
        known.put(SUCCESS.value, SUCCESS);
        known.put(FAILED.value, FAILED);
        known.put(CLIENT_ERROR.value, CLIENT_ERROR);
        known.put(SERVER_ERROR.value, SERVER_ERROR);
        known.put(TIMEOUT.value, TIMEOUT);
        KNOWN = Collections.unmodifiableMap(known);
        VALUES = List.copyOf(known.values());
    }

    private final String value;

    private WebhookDeliveryStatus(String value) {
        this.value = value;
    }

    /** Returns the constant for a known value, or a new instance that keeps an unknown value. */
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static WebhookDeliveryStatus of(String value) {
        Objects.requireNonNull(value, "value");
        WebhookDeliveryStatus known = KNOWN.get(value);
        return known != null ? known : new WebhookDeliveryStatus(value);
    }

    /** The known values, in the order of the specification. */
    public static List<WebhookDeliveryStatus> values() {
        return VALUES;
    }

    /** The raw value, as sent by the API. */
    @JsonValue
    public String value() {
        return value;
    }

    /** Whether this SDK version knows the value. */
    public boolean isKnown() {
        return KNOWN.containsKey(value);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof WebhookDeliveryStatus that && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    /** The raw value. */
    @Override
    public String toString() {
        return value;
    }
}
